### ISSUE TITLE
Unsuported post request

### ISSUE THREAD

**Issue by Napas** [facebook/facebook-php-ads-sdk#100]
I am trying to create custom audience and get this error:

     [FacebookAds\Http\Exception\AuthorizationException] Unsupported post request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api  

Here are my CustomAudience object dump before calling create method:

    object(FacebookAds\Object\CustomAudience)#689 (4) {
      ["changedFields":protected]=>
      array(7) {
        ["name"]=>
        string(27) "test_audience_55afa5296769e"
        ["description"]=>
        string(15) "Custom audience"
        ["subtype"]=>
        string(7) "PARTNER"
        ["opt_out_link"]=>
        string(26) "http://example.com"
        ["details"]=>
        string(43) "Custom audience test_audience_55afa5296769e"
        ["is_private"]=>
        bool(true)
        ["rev_share_policy_id"]=>
        int(xxxx)
      }
      ["api":protected]=>
      object(FacebookAds\Api)#701 (4) { ... }
      ["parentId":protected]=>
      int(xxxxxxxx)
      ["data":protected]=>
      array(22) {
        ["account_id"]=>
        NULL
        ["approximate_count"]=>
        NULL
        ["data_source"]=>
        NULL
        ["delivery_status"]=>
        NULL
        ["description"]=>
        string(15) "Custom audience"
        ["id"]=>
        NULL
        ["lookalike_audience_ids"]=>
        NULL
        ["lookalike_spec"]=>
        NULL
        ["name"]=>
        string(27) "test_audience_55afa5296769e"
        ["operation_status"]=>
        NULL
        ["opt_out_link"]=>
        string(26) "http://example.com"
        ["origin_audience_id"]=>
        NULL
        ["permission_for_actions"]=>
        NULL
        ["pixel_id"]=>
        NULL
        ["prefill"]=>
        NULL
        ["retention_days"]=>
        NULL
        ["rule"]=>
        NULL
        ["subtype"]=>
        string(7) "PARTNER"
        ["time_updated"]=>
        NULL
        ["details"]=>
        string(43) "Custom audience test_audience_55afa5296769e"
        ["is_private"]=>
        bool(true)
        ["rev_share_policy_id"]=>
        int(xxxx)
      }
    }

**Comment by pruno** [comment]
Hey @Napas,

Partner custom audiences are not a public API feature. Please contact your Facebook point of contact to get support over this.
