### ISSUE TITLE
Fatal error: Call to undefined method FacebookAds\Object\AdCampaign::getStats() 

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [facebook/facebook-php-ads-sdk#107]
HI,
I TRIED TO FETCH STATES OF CAMPAIGNS.

BUT I GET ERROR

Fatal error: Call to undefined method FacebookAds\Object\AdCampaign::getStats() 

MYCODE IS 

$fields = array(
'start_time','actions','spent','clicks','impressions','end_time',
);
$params = array();
$campaign = new AdCampaign("6024730380269");
$stats = $campaign->getStats($fields, $params);

**Comment by pruno** [comment]
Hi @nilaybrahmbhatt,

stats API has been deprecated in v2.4 in favor of the insights edge.

Full 2.4 API change-log: https://developers.facebook.com/docs/marketing-api/changelog#v2_4
Insights API: https://developers.facebook.com/docs/marketing-api/insights/v2.4
Main SDK commit: https://github.com/facebook/facebook-php-ads-sdk/commit/597a47021fe89062aa8ca6b163cc861b6974d6ff
