### ISSUE TITLE
Video upload using AdVideo class

### ISSUE THREAD

**Issue by shanmukhark** [facebook/facebook-php-ads-sdk#109]
When I try to upload a video using AdVideo class, end up getting this error very often. 
'Operation timed out after 60000 milliseconds with 0 bytes received' 
Video is around 20MB and how best we can upload the video using AdVideo class?

Regards,
Shanmukh.

**Comment by pruno** [comment]
Hi @shanmukhark,
This is the essential to upload a video:

~~~php
$video = new AdVideo(null, 'act_<AD_ACCOUNT_ID>');
$video->{AdVideoFields::NAME} = 'My video';
$video->{AdVideoFields::SOURCE} = '/local/path/to/file';
$video->create();

echo 'Video ID: '.$video->{AdVideoFields::ID}.PHP_EOL;
~~~

Closing this, feel free to reopen if you need additional support.

**Comment by shanmukhark** [comment]
Yes, I have used this class in a very similar way. But I received exception 'Operation timed out after 60000 milliseconds with 0 bytes received'  exactly after 60 seconds, however video upload (20MB Video) might take more time. How to handle this? Does this class support chunked upload? Or do I need to extend the default timeout parameter?
