### ISSUE TITLE
v2.4 New CPC bidding not being reflected in PowerEditor or Ads Manager

### ISSUE THREAD

**Issue by xplinscott** [facebook/facebook-php-ads-sdk#113]
According to the changelog for v2.4 the change to CPC bidding is as follows:

> Updating CPC to focus on link clicks - in order to make our advertisers' campaigns on Facebook more effective, we are updating the definition of cost per click (CPC). Today, when an advertiser runs a CPC  ad, Facebook counts any action taken within the ad unit as a click: a like, a comment, a share, “continue reading”, a video view, a link click, etc. Starting v2.4, we are updating our definition of CPC ads to separate link clicks from engagement clicks (including likes and comments), and CPC will only include link clicks. To continue to optimize for likes, comments, shares, etc. as well as link clicks, advertisers can use billing_event=POST_ENGAGEMENT and optimization_goal=POST_ENGAGEMENT (or in v2.3 terms, CPA for Page Post Engagement).

> Legacy ad sets bidding the v2.3- definition of CPC will be represented in v2.4 as having billing_event=POST_ENGAGEMENT and optimization_goal=POST_ENGAGEMENT

Following this we've been creating adsets for CPC bidding as:

```php
$adset = new AdSet(null, 'act_<ACCOUNT_ID>');
$adset->setData([
    AdSetFields::OPTIMIZATION_GOAL => OptimizationGoals::LINK_CLICKS,
    AdSetFields::BILLING_EVENT => BillingEvents::LINK_CLICKS,
    ...,
]);
$adset->create();
```
On both Power Editor and the Ads Manager it's showing these newly created AdSets as having a BidType of CPA. Are we doing this wrong?

**Comment by paulbain** [comment]
Yes from looking at the validation doc, your code is correct. For CPA now you have to specify the same optimization goal as your billing event. In the case of CPC which is now really link clicks, your billing event should be link clicks as this is what you want to be charged for.

**Comment by stonevo** [comment]
I had the same problems and i raise a bug in facebook and they said the Ads Manager and Power Editor still use the old version v2.3

https://developers.facebook.com/bugs/471193563049110
