### ISSUE TITLE
Can I create a AdCreative duplicate?

### ISSUE THREAD

**Issue by Mirko09** [facebook/facebook-php-ads-sdk#120]
I have AdCreative.

How do I create a duplicate using the SDK? Read existing AdCreative and create new AdCreative using old params - not a good idea. Is there a better option?

**Comment by pruno** [comment]
@Mirko09,

tl;dr; the API do not have a clone functionality

what's the end goal? creatives may be used for multiple ads. If you just need to replicate the same creatives under different AdSets for targeting reason, there is no need to duplicate the creative.

**Comment by Mirko09** [comment]
I want to set url_tags params if it is empty. But API does not allow it. How can I do this?

**Comment by Mirko09** [comment]
Ok. Duplicate is a bad idea in any case. How to update AdCreative.url_tags?

**Comment by pruno** [comment]
@Mirko09: the API allows it.

~~~php
$creative = new AdCreative(<AD_CREATIVE_ID>);
$creative->read([AdCreativeFields::URL_TAGS]);
if ($creative->{AdCreativeFields::URL_TAGS} === null) {
  $creative->{AdCreativeFields::URL_TAGS} = 'key1=val1&key2=val2';
  $creative->save();
}
~~~

If you still encounter errors, can you please share the error?

**Comment by Mirko09** [comment]
@pruno 
Unfortunately, the API not allows it.
https://developers.facebook.com/docs/marketing-api/adcreative/v2.4#update

I can only update a field AdCreativeFields::NAME.

How can I update AdCreativeFields::URL_TAGS? It is impossible? Can you add this feature, please?

**Comment by pruno** [comment]
@Mirko09, you'r right, unfortunately i think the only way is to download them, copy the data (augmenting with the url_tag), create new ones and re-map the adgroups

**Comment by d3m3tr1s** [comment]
Sorry, this thread closed, but I would like to ask still, how to make sure you don't loose social credibility like 
Shares #, Comments #, Likes # for an Ad when you clone AdCreative and re-map Ad to it?

**Comment by ConcourseMedia** [comment]
any update on this? What d3m3tr1s asked

**Comment by dmitrywicked** [comment]
@ConcourseMedia yes we have figured out that call should be like

`$fb->request('POST', "/<AD_ID>", ['creative' => json_encode($curCreative)]);`

where $curCreative is an array of previously extracted creative with updated url_tag param

**Comment by bilaliqbal-te** [comment]
@dmitrywicked should we need to create new Ad Creative? If so, what about the old one?

**Comment by silvios** [comment]
@bilaliqbal-te Good question. @dmitrywicked From what I can tell using the Facebook GUI, facebook deletes the old one, and attaches the new adcreative to the ad.

You can see this happen by editing an ad creative in the interface, then querying the ad id, via the API. you can see that only 1 ad creative is attached. And that one is the new one thats created from the edit.

I would love to know what you do though.
