### ISSUE TITLE
How can I make my Adset Optimized for CPC using api v2.4

### ISSUE THREAD

**Issue by taimoor13** [facebook/facebook-php-ads-sdk#125]
**CAMPAIGN OBJECTIVE: WEBSITE CONVERSION**
I am using the below parameters to create an adset, but API is giving me error **that API 2.4 no more allow optimizing_goal for CLICKS**
```php
$data[AdSetFields::OPTIMIZATION_GOAL] = 'CLICKS';
        $data[AdSetFields::BILLING_EVENT] = 'CLICKS';
        $data[AdSetFields::PROMOTED_OBJECT] = array(
			'pixel_id' => $_GET["pixel_id"]				
	);
```
when I use LINK_CLICKS for both **OPTIMIZATION_GOAL** & **BILLING_EVENT** , it creates the adset but when I check this newly created adset in power editor of Facebook its show me *optimized for = CPA !!!*

@paulbain @pruno

**Comment by paulbain** [comment]
Please take a look at the validation documentation to see the valid combinations:
https://developers.facebook.com/docs/marketing-api/validation/v2.4

CPA for link clicks == CPC
