### ISSUE TITLE
curl_setopt_array(): supplied argument is not a valid cURL handle resource AbstractCurl.php

### ISSUE THREAD

**Issue by chicag0** [facebook/facebook-php-ads-sdk#126]
When doing $adSet->getInsights() about 50% of the time I get an error:

curl_setopt_array(): supplied argument is not a valid cURL handle resource AbstractCurl.php on Line 109

If I keep refreshing the page, it will eventually return the data.  I am able to grab data from the API many other places but seem to run into this issue often.  Any idea what might be causing?

**Comment by pruno** [comment]
@chicag0,

which version of PHP are you running? The SDK runs 2 different encapsulations for curl 5.4 and 5.5+

https://github.com/facebook/facebook-php-ads-sdk/tree/master/src/FacebookAds/Http/Adapter/Curl

Are you using Implicit Fetching on cursors? https://github.com/facebook/facebook-php-ads-sdk#implicit-fetching

**Comment by chicag0** [comment]
I'm using 5.6.7.

I've just tried with implicit fetching and the issue is still there.  I must be doing something else wrong.

All I'm trying to do is get ad insights for a single ad group.  Is there a way to do that without using cursors?

**Comment by pruno** [comment]
not really, but cursors are not the issue here.
Can you tell whether this happens for the first request in the script or a succeeding one?

**Comment by chicag0** [comment]
Here is a stack trace, if you see anything obvious?
![stack](https://cloud.githubusercontent.com/assets/5142516/9685651/a8712044-52ed-11e5-880d-104f1ae314ea.png)

I'll dig in a little deeper and see if I can tell where it is happening.
