### ISSUE TITLE
Filter results on last 7 days

### ISSUE THREAD

**Issue by yamsellem** [facebook/facebook-php-ads-sdk#129]
Is there a way to filter results to get only late ones, say those who has been modified in the last 7 days (for example)? I've noticed that a updated_on field is present on several entities, it may serves as a reference for this filter.

```php
$account->getAdCampaigns(array(
    AdCampaignFields::ID,
    AdCampaignFields::NAME)
  ), 
  array(
    'limit' => $max, 
    'since' => 'last_7_days'
  )
);
```

**Comment by pruno** [comment]
not directly from the ad account edge, but you can use the activity log API to find the IDs: https://developers.facebook.com/docs/marketing-api/activity-log/v2.4

than querying the IDs as:

~~~php
$cursor = AdCampaign::readIds(
  [$id1, $id2, ...],
  [AdCampaignFields::ID, AdCampaignFields::NAME]
);
~~~

**Comment by yamsellem** [comment]
@pruno thanks for your answer.

Fetching the activity log can be done through:
```php
$account->getActivities($fields, array('since' => $since));
```

And fetching some campaign (or other) by ids, can be done through:
```php
AdCampaig::readIds($ids, $fields, array('limit' => $max));
```

Careful, though, this is not returning a cursor (as we should expect — you've used one in your example, and I was expecting the same), it seems it's returning every entity.

I guess this is because the resource does not return any cursor:

````http
curl -G \
-d "ids=<AD_SET_1>, <AD_SET_2>, <AD_SET_3>" \
-d "fields=name,campaign_status" \
-d "access_token=<ACCESS_TOKEN>" \
"https://graph.facebook.com/<API_VERSION>/"
```
