### ISSUE TITLE
Business Manager Objects

### ISSUE THREAD

**Issue by Ashpants** [facebook/facebook-php-ads-sdk#13]
Currently the SDK doesn't support the business manager.

At first glance, it looks like we would need:

1) a systemuser object which would allow systemuser creation and system user token generation.

2) a page object to add a page to the businessmanager as an owner or agency.

Are there any plans currently to implement these new objects?

**Comment by alexkappa** [comment]
@paulbain is there any update on this?

**Comment by paulbain** [comment]
It's in the works, hopefully more news soon!

**Comment by paulbain** [comment]
Added in v2.4!
