### ISSUE TITLE
Do not throw an exception on existing field access not returned by the api

### ISSUE THREAD

**Issue by yamsellem** [facebook/facebook-php-ads-sdk#130]
Accessing to a field can throw exception like `"actions is not a field of FacebookAds\\Object\\Insights"`.

This is wrong: actions is a field of Insights, it's accessible for several objects, but, when the field is not returned by facebook api, the sdk throw this exception.

The issue is in [AbstractObject](https://github.com/facebook/facebook-php-ads-sdk/blob/master/src/FacebookAds/Object/AbstractObject.php#L49). The presence of the field in the enum should be asserted if the api result is null before throwing an exception.

And this leads to ugly catch in client code:
```php
try {
  $actions = $entity->{InsightsFields::ACTIONS};
} catch(\InvalidArgumentException $e) {
  $actions = null;
};
```

**Comment by chicag0** [comment]
Thanks, I tested this and it solved an issue I was having.

**Comment by pruno** [comment]
Fixed by https://github.com/facebook/facebook-php-ads-sdk/commit/134eca31ad46821f7d12efc743a87b4900296de9
