### ISSUE TITLE
Possible to update Adset location targeting?

### ISSUE THREAD

**Issue by chicag0** [facebook/facebook-php-ads-sdk#133]
Is it possible to update the location targeting of an adset?

I am attempting to update a number of lat/lng pairs but it doesnt seem to save.  When I update other fields on the adset, it works.  Is this possible?

Also, is it possible to create conversion id (for pixel tracking) via the api?  I do not see any mention in the docs.

**Comment by pruno** [comment]
Hi @chicag0 

What objective are you using for the campaign? can you share your code to reproduce?

to create a conversion pixel through the API
API reference: https://developers.facebook.com/docs/marketing-api/offsite-pixels/v2.4
SDK object: https://github.com/facebook/facebook-php-ads-sdk/blob/master/src/FacebookAds/Object/AdConversionPixel.php

**Comment by chicag0** [comment]
Hi @pruno,

Thanks for the link to the pixel, not sure how I missed that in the docs.  

Here is a sample of how I am attempting to update the lat/lng location targeting of an adset:

```
$adset = new AdSet($adsetId, $account->id);
$custom_locations = array(
   array(
     'radius' => 30,
     'latitude' => '36'
    'longitude' => '-76'
  ),
);
$adset->{AdSetFields::TARGETING} = array(
			  	// https://developers.facebook.com/docs/marketing-api/targeting-specs/v2.4#location
			    TargetingSpecsFields::GEO_LOCATIONS => array(
			      'countries' => NULL, 
			      'custom_locations' => $custom_locations,
			      'location_types'	=>	array('home'), // home, recent, travel_in
			    ),
		    );
```

I had to modify it a bit so there may be some minor syntax errors.

Basically this is the same way I change any other adset options.  This code appears to save, because the adset is returned correctly, but the changes never happen on FB side.  My objective is 'website clicks'.  I want to update my adsets location targeting throughout the day rather than have to create a new ad and wait for it to get approved.

**Comment by pruno** [comment]
Assuming after this you are calling

~~~php
$adset->update();
~~~

or 

~~~php
$adset->save();
~~~

and [36, -76] are not the actual coordinates you are setting (they are in water).

this should work.

can you double check your fields name? as you said this is not exactly the code you are running.

The best way of debugging it might be use the SDK cURL logger

~~~php
Api::instance()->setLogger(new CurlLogger());
~~~

this will dump to STDOUT a cURL cmd that is equivalent to the request the SDK is making
