### ISSUE TITLE
Error Reading Adset

### ISSUE THREAD

**Issue by fdask** [facebook/facebook-php-ads-sdk#139]
Another issue against the v2.5 sdk, and version 2.5.0 of this...

The documentation (https://developers.facebook.com/docs/marketing-api/reference/ad-campaign#Reading) for reading an ad set gives me errors.

When I try the following code, I get exceptions about fields not existing.

$adset = new AdSet($adset_id);
$params = array(
  'date_format' => 'U',
);
$adset->read(array(
  'start_time',
  'end_time',
  'status',
  'campaign_id',
), $params);

PHP Fatal error:  Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message '(#100) Tried accessing nonexisting field (end_time) on node type (AdCampaignGroup)' in /var/www/html/adsystem/system/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php:137

It's not just end_time, but a whole wack of the fields listed in the AdSetFields.php file give me the same error.  I started by trying to pull all of them, but ended up only successfully getting the following:

AdSetFields::ACCOUNT_ID,
AdSetFields::CREATED_TIME,
AdSetFields::ID,
AdSetFields::NAME,
AdSetFields::START_TIME,
AdSetFields::UPDATED_TIME,
AdSetFields::PROMOTED_OBJECT,
AdSetFields::ADLABELS

Everything else caused an exception like the one above.  Whats up here?

**Comment by pruno** [comment]
Judging by the error, it seems that your $adset_id might be a campaign ID, please double-check it.

From the error:  ... AdCampaignGroup ... which is the legacy name of Campaign
