### ISSUE TITLE
Error Updating Campaign status on 2.5.* SDK

### ISSUE THREAD

**Issue by server-may-cry** [facebook/facebook-php-ads-sdk#142]
status is not a field of FacebookAds\Object\Campaign
facebook/php-ads-sdk version "2.5.0"

when trying to update Campaign
use FacebookAds\Object\Campaign;
$campaign = new Campaign($ad['fb_campaign_id']);
$campaign->setData([
          Campaign::STATUS_PARAM_NAME => Campaign::STATUS_ACTIVE,
]);
$campaign->update();

**Comment by paulbain** [comment]
the status isn't actually a field of the Campaign object anymore so you can't use the data field. 
Instead you need to pass it as a parameter in the save, update or create functions:

    $campaign = new Campaign($ad['fb_campaign_id']);
    $campaign->update(array(
        Campaign::STATUS_PARAM_NAME => Campaign::STATUS_ACTIVE
    ));

I agree that this is not seem particularly logical.
