### ISSUE TITLE
Life Time Budget is not correct

### ISSUE THREAD

**Issue by salahy** [facebook/facebook-php-ads-sdk#145]
I am trying to get the life time budget for the adsets, I am getting all the other info correctly, but for the life time budget I am getting extra two zeros, for example I have two adsets 
500$ and 100$ 
but I am getting from the API 50000 and 10000.

**Comment by fdask** [comment]
The amounts are in cents.  So your dollars * 100.

**Comment by pruno** [comment]
Hi @salahy,

USD are represented as cents in our API. the number you are receiving  are correct. You can find the complete maps of currencies offsets here: https://developers.facebook.com/docs/marketing-api/currencies
