### ISSUE TITLE
Updating Spend Cap for Campaign

### ISSUE THREAD

**Issue by nicholasscottfish** [facebook/facebook-php-ads-sdk#146]
Hi there, i'm wondering if you can please help me. I'm trying to update the spend cap of a campaign using the PHP SDK, however from reading other issues it seems the documentation is slightly out of date.

I'm currently attempting:

```php
    /**
     * @param $campaignId
     * @param $spendCapValue
     *
     * @return bool
     */
    public function modifySpendCapById($campaignId, $spendCapValue)
    {
        $campaign = new FacebookCampaign($campaignId);

        $campaign->setData([
           CampaignFields::SPEND_CAP => $spendCapValue
        ]);

        $campaign->update();

        return true;
    }
```

but i'm receiving the following error:

```json
    {
        "message": "Invalid parameter",
        "code": 100,
        "status_code": 500
    }
```

I understand that's because the SPEND_CAP parameter is not valid, however, NAME allows me to update the name. Please could you direct me on how this should be done?

Thanks,

Nick

**Comment by paulbain** [comment]
What is the value of the spend cap? The minimum is $100 in your currency, so this may be the problem. 
The other thing to check is whether the campaign id is actually a campaign, and not some other object like an adset.

**Comment by nicholasscottfish** [comment]
Hi there @paulbain, thanks for the quick response. The value of the spend cap is '2000', ie. $200 right? As for the campaign id it is definitely a campaign object, I am using this same ID to perform status updates etc.

Is there a problem with the format of the update request?

Cheers,

Nick

**Comment by paulbain** [comment]
can you add the following code to your project and paste the output? It should exclude the access token automatically, but including the campaign Id shouldn't be a problem. 

    Api::instance()->setLogger(new FacebookAds\Logger\CurlLogger());

**Comment by nicholasscottfish** [comment]
Hmm...

I've pasted that in above the code and i'm now getting this response:

```json
    {
        "message": "Use of undefined constant STDOUT - assumed 'STDOUT'",
        "status_code": 500
    }
```

Here's my code:

```php
    /**
     * @param $campaignId
     * @param $spendCapValue
     *
     * @return bool
     */
    public function modifySpendCapById($campaignId, $spendCapAmount)
    {
        $campaign = new FacebookCampaign($campaignId);
        
        Api::instance()->setLogger(new CurlLogger());
        
        $campaign->setData([
           CampaignFields::SPEND_CAP => $spendCapAmount
        ]);

        $campaign->update();

        return true;
    }
```

If I move that line below the update I just get the invalid_parameter 500 respsonse.

**Comment by paulbain** [comment]
Strange that STDOUT isn't defined in your environment. Can you send me your campaign ID and I'll look on my side what's going on.

**Comment by nicholasscottfish** [comment]
I have just done a bit more digging of my own and I think you might have been on the right tracks when talking about spend cap value. I have just had the same error message when trying to increase and adset bid amount to greater than that of the adset daily budget.

I have since tried the call with the following data input and been successful:

```json
    {  
       "spendCapAmount":"10000"
    }
```

So 10000 equals $100 is that correct, anything below is and I should expect the invalid parameter error? Is there a high end limit to this, such as a max spend cap?

Thanks for your help on this.

**Comment by paulbain** [comment]
Ah yes, should have mentioned, values are in pence. I'm not aware of any max spend cap, as by default, spend caps are unlimited on the campaign level.

**Comment by nicholasscottfish** [comment]
Okay, thanks for your help @paulbain. Any other issues and i'll let you know. Cheers.
