### ISSUE TITLE
Update Adset Location Targeting without resetting other targeting

### ISSUE THREAD

**Issue by chicag0** [facebook/facebook-php-ads-sdk#149]
I am updating my adsets targeting throughout the day using Latitude/Longitude pairs.  It seems like it resets my other targeting though (age, gender, etc).

Do I have to send age,gender and other targeting items when updating locations, or is there a way to reuse the existing targeting while only changing locations?

**Comment by pruno** [comment]
yes, targeting is a single field in the adset object. when updating, fields are overwritten, not merged.

PS: updating your adset during the day can easily screw your delivery, you should probably use day_parting and create multiple adsets, scheduled for different timings

https://developers.facebook.com/docs/marketing-api/adset/pacing/v2.5

**Comment by abhishekgoel137** [comment]
This is how you do it

adset = new AdSet($ad_set_id);

$fields = array(
	AdSetFields::TARGETING,
);

$data = $adset->read($fields);

$targeting_data = $data->targeting;

$targeting_data['geo_locations'] = array(
		// 'countries' => array('IN'),
		'regions' => array(array('key' => '1725')),
		'cities' => array(
			array(
				'key' => '1035921',
			)
		),
    );


$adset->{AdSetFields::TARGETING} = $targeting_data;

$adset->update();
