### ISSUE TITLE
$defaultUseImplicitFetch is defaulted to false

### ISSUE THREAD

**Issue by mcross1882** [facebook/facebook-php-ads-sdk#155]
Within the `Cursor` class the static variable `defaultUseImplicitFetch` is set to `false` by default. However since the `Cursor` class is an `Iterable` and will likely be used as such this seems counterproductive. In order to pull a full result set (e.g. a product_id breakdown report) `setUseImplicitFetch` must be used to ensure an implicit fetch . This means a user will have to call this method before looping through the `Cursor` class.

https://github.com/facebook/facebook-php-ads-sdk/blob/master/src/FacebookAds/Cursor.php#L66

Is there a specific reason for this?

**Comment by pruno** [comment]
Hi @mcross1882,

one of the principles about the SDK design is to make transparent whenever the an HTTP request is performed.
Moreover implicit fetching capability was added in a second step and we needed to grant no sudden behavioral changes.
We feel the static interface is reasonable enough to enable it:

~~~php
Cursor::setDefaultUseImplicitFetch(true);
~~~

you can call this anytime, just after or before the SDK init is advised.

I hope this answer your question.
