### ISSUE TITLE
 Undefined class constant 'UNIQUE_ACTIONS'

### ISSUE THREAD

**Issue by AlexNoahMob** [facebook/facebook-php-ads-sdk#156]
Hi  
     I want to get 'UNIQUE_ACTIONS' throught PHP SDK ,but have got Undefined class constant 'UNIQUE_ACTIONS' . I have check the InsightsFields Class , can not find this Field. But I can got it from graph api url . Is there another way  to get this fileds. 

Thanks
Alex

**Comment by pruno** [comment]
hi @AlexNoahMob, 

do you fancy sending a pull request with it?

**Comment by AlexNoahMob** [comment]
Hi @pruno 

 Thanks for U  reply ^_^

 I want to get   ”UNIQUE_ACTIONS“ Fields from adset ， defined as follows
 $fields = array(
      InsightsFields::SPEND,
      InsightsFields::IMPRESSIONS,
      InsightsFields::CAMPAIGN_NAME,
      InsightsFields::COST_PER_ACTION_TYPE,
      InsightsFields::UNIQUE_ACTIONS,
    );

 have got remind  “Undefined class constant” ，I have check the InsightsFields Class，Really don't have this field. But I can got it from  graph api Explorer  url . Is there another way to get this fileds.


Thanks
Alex

**Comment by duliomatos** [comment]
Contributed by @77web pull request https://github.com/facebook/facebook-php-ads-sdk/pull/171, it's merged on master.
