### ISSUE TITLE
Documentation of Parameters for getLeads / getLeadgenForms

### ISSUE THREAD

**Issue by rbaindourov** [facebook/facebook-php-ads-sdk#159]
Hi There,
By comparing my leads in the web interface, and what the API returns, it seems that there is a paging mechanism that I need to use. I have discovered that there is a $limit parameter looking at your [tests](https://github.com/facebook/facebook-php-ads-sdk/blob/f6db8781157c9508591c107b47a6a8117085d1b1/test/FacebookAdsTest/Object/LeadTest.php) for the `getLeadgenForms()`.

But I have not seen anything in the [guide](https://developers.facebook.com/docs/marketing-api/guides/lead-ads/v2.5).

Where can I see a list of all the function parameters documented?
I am not able to discover anything on this method doing a site [restricted search in google](https://www.google.com/search?q=site%3Adeveloper.facebook.com+getLeads%28&ie=utf-8&oe=utf-8#q=site%3Adevelopers.facebook.com+getLeads)

Are you gentlemen planning on generating searchable phpdoc's from the structured comments, and adding more information as to what parameters can be passed for each function? 

I know that may blow up your source code, but we really need more examples or docs. 

For the time being I just increased the limit to 10000. But I would really appreciate a better understanding of how to use the API correctly.

Thank You!

EDIT: 
I see now that the FacebookAds\Cursor object has a `$cursor->fetchAfter();`
And that I can iterate through all the data by setting `Cursor::setDefaultUseImplicitFetch(true);`
But I still need more info on date restricting getLeads query to the API, and how many total leads are in the result set. 

Does setting the limit simply set the initial page size, or is that the complete end of the cursor?

**Comment by rbaindourov** [comment]
I think I found all the answers I need on in the [paging portion of the documentation](https://developers.facebook.com/docs/graph-api/using-graph-api/v2.5#paging)

Seems that I should be able to pass in `since`, `until` as well as `limit` as possible parameters to most endpoints.

So there is no way for me to know the total count of a query? 
I just have to keep paging until I reach the end?

By the way, the site has a lot of green text, and some of it is a link and some of it isn't.

**Comment by duliomatos** [comment]
Hello @rbaindourov, using `since`, `until` (or `limit`) and using pagination as you are doing now is the correct way to do it on our APIs. For something like leads, it makes more sense to use these time parameters (since/until) as you would usually fetch the leads that were created since the last time you checked.

We are always working on improving the docs, thx for the feedback!

**Comment by rbaindourov** [comment]
Thank You!

**Comment by mbiagetti** [comment]
hi @rbaindourov !

I have the same problems with the pagination of the leads (getLeads on LeadgenForm object). How you solve this problem?

I'm trying to request only new leads starting from a certain point (time-based pagination or cursor-based) storing a pointer in our system, but i'm not be able to pass the correct pointer. 

As sample, I use the following code:

```php
        $now= strtotime("now");
        $leads  = $form->getLeads(['created_time'], ['limit' => 1, 'since' => $now]);

```

but return me old leads.  can you help me with some tips?

@duliomatos any advice on this?

Thanks in advice for your help!

**Comment by rbaindourov** [comment]
@mbiagetti I made an example project you can look at in my github. 
https://github.com/rbaindourov/facebook-marketing-api-example
Let me know if that doesn't contain an example.
