### ISSUE TITLE
AdTargeting Search

### ISSUE THREAD

**Issue by liorpr** [facebook/facebook-php-ads-sdk#161]
Hi, trying to pull Interest Targeting with TargetingSearch::search...

I get an exception when I try to send an empty string or null as the q parameter,
although using the API it works fine (just getting empty data, that's what I want)...

https://developers.facebook.com/docs/marketing-api/targeting-search/v2.5#interests

**Comment by duliomatos** [comment]
Hey @liorpr, what's the use case for pushing an empty param for Interest Targeting instead of considering it an error? It is desirable that the SDK be more strict than the direct API if it avoids errors.

**Comment by liorpr** [comment]
Just sending this from a search input in my application and wish to send it regardless if it's empty ot not and get the data with no specific handling...Guess we can close this issue If it's desirable behavior...
