### ISSUE TITLE
Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message 'Invalid OAuth access token.'

### ISSUE THREAD

**Issue by jtgui12** [facebook/facebook-php-ads-sdk#162]
Hello,

Can you help me please.
I did everything of the facebook docs. But I get this message:
Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message 'Invalid OAuth access token.'

Here is my code:

<?php
//require_once 'src/Facebook/autoload.php';
include 'vendor/autoload.php';
// Add to header of your file
use FacebookAds\Api;
use FacebookAds\Object\AdAccount;
use FacebookAds\Object\AdUser;

// Add after echo "You are logged in "

// Initialize a new Session and instantiate an Api object
Api::init(
  '***********************', // App ID
  '{**********************}', // app-secret
  $_SESSION['******'] // Your user access token which is numbers right ?
);

//$account = new AdAccount('act_5291585038833333');
// Add after Api::init()
$me = new AdUser('me');
$my_adaccount = $me->getAdAccounts()->current();

print_r($my_adaccount->getData());

Please it's very first code to use the Facebook SDK but I have a problem at this early stage.
Help me!
Many thanks!!

**Comment by duliomatos** [comment]
Hey @jtgui12, it seems you're having problems with your access token rather than the SDK.

You could use this tool to debug the token: https://developers.facebook.com/tools/debug/
And would probably benefit from trying out Graph Explorer(don't forget to select you app): https://developers.facebook.com/tools/explorer

**Comment by jtgui12** [comment]
Thanks @duliomatos for your message. But really I test everything. I don't understand why it didn't work.
Here my full error:

MacBook-Pro-de-J:~ jordan$ php test.php

Fatal error: Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message 'Invalid OAuth access token.' in /Users/jordan
/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php:137
Stack trace:
#0 /Users/jordan
/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Client.php(216): FacebookAds\Http\Exception\RequestException::create(Array, 400)
#1 /Users/jordan/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Request.php(282): FacebookAds\Http\Client->sendRequest(Object(FacebookAds\Http\Request))
#2 /Users/jordan/vendor/facebook/php-ads-sdk/src/FacebookAds/Api.php(152): FacebookAds\Http\Request->execute()
#3 /Users/jordan/vendor/facebook/php-ads-sdk/src/FacebookAds/Api.php(194): FacebookAds\Api->executeRequest(Object(FacebookAds\Http\Request))
#4 /Users/jordan/vendor/facebook/php-ads-sdk/src/FacebookAds/Object/AbstractCrudObject.php(373): FacebookAds\Api->call('/me/adaccounts', 'GET', Array)
#5 /Users/jordan/vendor/facebook/ph in /Users/jordan/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php on line 137

Do you want to make a screenshare with me to help me please ?
Thanks a lot for your support!

**Comment by duliomatos** [comment]
Sorry @jtgui12, this forum for SDK related bugs or requests... I recommend that you try both of the tools I  shared or just follow section 6 of Ads API quickstart: https://developers.facebook.com/docs/marketing-api/quickstart.

Best.
