### ISSUE TITLE
Missing Available Ad Formats

### ISSUE THREAD

**Issue by allentsai** [facebook/facebook-php-ads-sdk#163]
`MOBILE_FEED_BASIC `, `MOBILE_NATIVE `, and `INSTAGRAM_STANDARD` are ad formats available via v2.5, but are not found in FacebookAds\Object\Values\AdFormats.php

This isn't really a bug, but I've been using `AdFormats::getInstance()->getValues()` for some parameter validation, and because the above formats do not exist in the class, manual addition to the array of valid formats is required.

**Comment by duliomatos** [comment]
Hello @allentsai, thx for spotting this. I'll fix it ;-)

**Comment by allentsai** [comment]
Oh yeah, this is open source, huh... I should just fix it myself, never submitted an PR to a public repo before D:

**Comment by allentsai** [comment]
I've created a PR with the update here:
https://github.com/facebook/facebook-php-ads-sdk/pull/165
Also fixed a typo...
