### ISSUE TITLE
Fatal error: Class 'FacebookAds\Object\AdCampaign' not found in /Users/jordan

### ISSUE THREAD

**Issue by jtgui12** [facebook/facebook-php-ads-sdk#164]
Hello Everyone,

Can someone help me on this ?
I have a problem to get simple analytics of my campaigns.
I receive this message: 
Fatal error: Class 'FacebookAds\Object\AdCampaign' not found in /Users/jordan

And my php code is:
<?php
include 'vendor/autoload.php';
// Add to header of your file
use FacebookAds\Api;
use FacebookAds\Object\AdAccount;
use FacebookAds\Object\AdUser;
use FacebookAds\Object\Campaign;
use FacebookAds\Object\Fields\CampaignFields;
use FacebookAds\Object\Values\AdObjectives;
use FacebookAds\Object\AdSet;
use FacebookAds\Object\Fields\AdSetFields;
use FacebookAds\Object\Fields\TargetingSpecsFields;
use FacebookAds\Object\TargetingSpecs;
use FacebookAds\Object\Values\OptimizationGoals;
use FacebookAds\Object\Values\PageTypes;
use FacebookAds\Object\Values\BillingEvents;
use FacebookAds\Object\Values\InsightsLevels;
use FacebookAds\Object\AdCampaign;
use FacebookAds\Object\Values\InsightsPresets;
use FacebookAds\Object\Fields\InsightsFields;
// Add after echo "You are logged in "
$access_token = '*******';
$app_id = '1525006754476982';
$client_secret = '********';
Api::init($app_id, $client_secret, $access_token);
$campaign = new AdCampaign('6033258891498');
$campaign->read(array(
  CampaignFields::ID,
  CampaignFields::NAME,
  CampaignFields::OBJECTIVE,
));
$params = array(
  'time_range' => array(
    'since' => '2015-12-01',
    'until' => '2015-12-13',
  ),
 );
$fields = array(
  InsightsFields::IMPRESSIONS,
  InsightsFields::UNIQUE_CLICKS,
  InsightsFields::REACH,
);
$insights = $campaign->getInsights($fields, $params);
print_r($insights);

Please can you help me on this?
Many thanks!!!

**Comment by duliomatos** [comment]
Hey @jtgui12, this seems to be a setup issue rather than a bug. Can you check your installation and composer settings making sure you're following our README? https://github.com/facebook/facebook-php-ads-sdk

**Comment by vantaiit** [comment]
Me too

**Comment by vitaltheatre** [comment]
[pnordh](https://github.com/pnordh) commented [on Sep 6, 2017](https://github.com/facebook/facebook-php-business-sdk/issues/356#issuecomment-327405843)
The AdCampaign class was renamed in https://github.com/facebook/facebook-php-business-sdk/commit/225ed62295a203c3ce30b7be3f6eb890eced3f90 to Campaign in order to be consistent with the endpoints.
