### ISSUE TITLE
Error during create Ad

### ISSUE THREAD

**Issue by AcidS76** [facebook/facebook-php-ads-sdk#166]
Good day,
i'm trying to run the example "adgroup_creation.php" included in this last version (2.5) but i get many errors. The first is when i try to set "CampaignFields::STATUS" because it seems this constant doesn't exists so i have to replace with "effective_status". The same problem i have when i try to set "AdSetFields::STATUS". 

But the big problems arrive now. I'm trying to create AdSet using geolocation and i use this code:

$dato =  array(
'access_token' => $access_token,
'q' => "Siena",
'type' => 'adgeolocation',
'location_types' => "['city']"
);

$http = new HTTPProxy();
$citta_str = $http->connect("https://graph.facebook.com/v2.5/search", $dato, "GET");
$citta_vet = json_decode($citta_str, true);
$key_city="";
if(count($citta_vet['data']) > 0) {
	$citta_vet=$citta_vet['data'][0];
	$key_city=$citta_vet['key'];
	$targeting = new TargetingSpecs();
	$radius="20";
	$vett_to_send=array('key'=>$key_city, 'radius'=>$radius,'distance_unit'=>'kilometer');
	$targeting->{TargetingSpecsFields::GEO_LOCATIONS} = array('countries' => array('IT'), 'cities' => $vett_to_send);
}

$adset = new AdSet(null, $account->id);
$adset->setData(array(
  AdSetFields::NAME => 'My First AdSet',
  AdSetFields::CAMPAIGN_ID => $campaign->id,
  effective_status => AdSet::STATUS_ACTIVE,
  AdSetFields::DAILY_BUDGET => '150',
  AdSetFields::TARGETING => $targeting,
  AdSetFields::OPTIMIZATION_GOAL => OptimizationGoals::REACH,
  AdSetFields::BILLING_EVENT => BillingEvents::IMPRESSIONS,
  AdSetFields::BID_AMOUNT => 2,
  AdSetFields::START_TIME =>
    (new \DateTime("+1 week"))->format(\DateTime::ISO8601),
  AdSetFields::END_TIME =>
    (new \DateTime("+2 week"))->format(\DateTime::ISO8601),
));

$adset->validate()->create();

but in creation step, i get this error: 
[22-Dec-2015 12:19:46 Europe/Berlin] PHP Fatal error:  Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message 'Invalid parameter' in /var/www/test/api/facebook/facebook-php-ads-sdk-master_new/src/FacebookAds/Http/Exception/RequestException.php:137
Stack trace:
#0 /var/www/test/api/facebook/facebook-php-ads-sdk-master_new/src/FacebookAds/Http/Client.php(216): FacebookAds\Http\Exception\RequestException::create(Array, 500)
#1 /var/www/test/api/facebook/facebook-php-ads-sdk-master_new/src/FacebookAds/Http/Request.php(282): FacebookAds\Http\Client->sendRequest(Object(FacebookAds\Http\Request))
#2 /var/www/test/api/facebook/facebook-php-ads-sdk-master_new/src/FacebookAds/Api.php(152): FacebookAds\Http\Request->execute()
#3 /var/www/test/api/facebook/facebook-php-ads-sdk-master_new/src/FacebookAds/Api.php(194): FacebookAds\Api->executeRequest(Object(FacebookAds\Http\Request))
#4 /var/www/test/api/facebook/facebook-php-ads-sdk-master_new/src/FacebookAds/Object/AbstractCrudObject.php(236): FacebookAds\Api->call('/act_35434324/a... in /var/www/test/api/facebook/facebook-php-ads-sdk-master_new/src/FacebookAds/Http/Exception/RequestException.php on line 137

It works if i search by interest as in the example file.

The other problem i have is related to the "step 7"

$ad = new Ad(null, $account->id);
$ad->setData(array(
  AdFields::CREATIVE =>
    array('creative_id' => $creative->id),
  AdFields::NAME => 'My First Ad',
  AdFields::ADSET_ID => $adset->id,
));
$ad->create();

Even here i get here i get this error

[22-Dec-2015 12:26:59 Europe/Berlin] PHP Fatal error:  Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message 'Invalid parameter' in /var/www/test/api/facebook/facebook-php-ads-sdk-master_new/src/FacebookAds/Http/Exception/RequestException.php:137
Stack trace:
#0 /var/www/test/api/facebook/facebook-php-ads-sdk-master_new/src/FacebookAds/Http/Client.php(216): FacebookAds\Http\Exception\RequestException::create(Array, 500)
#1 /var/www/test/api/facebook/facebook-php-ads-sdk-master_new/src/FacebookAds/Http/Request.php(282): FacebookAds\Http\Client->sendRequest(Object(FacebookAds\Http\Request))
#2 /var/www/test/api/facebook/facebook-php-ads-sdk-master_new/src/FacebookAds/Api.php(152): FacebookAds\Http\Request->execute()
#3 /var/www/test/api/facebook/facebook-php-ads-sdk-master_new/src/FacebookAds/Api.php(194): FacebookAds\Api->executeRequest(Object(FacebookAds\Http\Request))
#4 /var/www/test/api/facebook/facebook-php-ads-sdk-master_new/src/FacebookAds/Object/AbstractCrudObject.php(236): FacebookAds\Api->call('/act_35434324/a... in /var/www/test/api/facebook/facebook-php-ads-sdk-master_new/src/FacebookAds/Http/Exception/RequestException.php on line 137

Can i solve these problems in some ways? Could you help me? Thanks

**Comment by duliomatos** [comment]
Hello @AcidS76, sorry for the delay and thx for pointing out this issue. STATUS was split in two as you noticed, I'll create an issue to fix the examples.

Are you still facing these exceptions by following the examples? If positive, can you help with more details of the  by sharing a log using the CurlLogger exemplified here? curl_log.php

In the step 7 I would check if all the id's are not null.

**Comment by duliomatos** [comment]
@AcidS76, just updated `adgroup_creation.php` [here](https://github.com/facebook/facebook-php-ads-sdk/blob/master/examples/adgroup_creation.php). Should work not and will be a better starting point for you.

**Comment by faisal847** [comment]
@duliomatos can you help me i have the following code for creating adset but getting invalid parameter always....

$adset->setData(array(
  AdSetFields::NAME => 'My First AdSet',
  AdSetFields::CAMPAIGN_ID => $campaign->id,
  AdSetFields::DAILY_BUDGET => '150',
  AdSetFields::TARGETING => $targeting,
  AdSetFields::OPTIMIZATION_GOAL => OptimizationGoals::REACH,
  AdSetFields::BILLING_EVENT => BillingEvents::IMPRESSIONS,
  AdSetFields::BID_AMOUNT => 100,
  AdSetFields::START_TIME =>
    (new \DateTime("+1 week"))->format(\DateTime::ISO8601),
  AdSetFields::END_TIME =>
    (new \DateTime("+2 week"))->format(\DateTime::ISO8601),
));

$adset->validate()->create(array(
  AdSet::STATUS_PARAM_NAME => AdSet::STATUS_ACTIVE,
));

echo 'AdSet  ID: '. $adset->id . "\n";

Please help as i am not able to track the parameter.

**Comment by duliomatos** [comment]
@faisal847, can you share which sdk version are you using and try on `2.5.2` if not using it yet?

One trick I you can use is to setup CurLogger to see what's happening behind the scene:
```
use FacebookAds\Logger\CurlLogger;
Api::instance()->setLogger(new CurlLogger());
```
If you can share the CurlLogger output, it would also help.

**Comment by faisal847** [comment]
@duliomatos, we are using 2.5.* version. I have setup the CurlLogger but again we are getting invalid parameter only

**Comment by duliomatos** [comment]
Can u share the curlLogger output, redacting sensitive info?

**Comment by faisal847** [comment]
i am getting nothing except "Invalid parameter" after initiating the CurlLogger don't know why. Can i share you the traces i get? would it help?

**Comment by duliomatos** [comment]
It would help

**Comment by faisal847** [comment]
#0 /var/www/html/magentoce/facebook-php-ads-sdk-master/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Client.php(216): FacebookAds\Http\Exception\RequestException::create(Array, 400)
#1 /var/www/html/magentoce/facebook-php-ads-sdk-master/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Request.php(282): FacebookAds\Http\Client->sendRequest(Object(FacebookAds\Http\Request))
#2 /var/www/html/magentoce/facebook-php-ads-sdk-master/src/FacebookAds/Api.php(151): FacebookAds\Http\Request->execute()
#3 /var/www/html/magentoce/facebook-php-ads-sdk-master/src/FacebookAds/Api.php(193): FacebookAds\Api->executeRequest(Object(FacebookAds\Http\Request))
#4 /var/www/html/magentoce/facebook-php-ads-sdk-master/vendor/facebook/php-ads-sdk/src/FacebookAds/Object/AbstractCrudObject.php(236): FacebookAds\Api->call('/act_1116091278...', 'POST', Array)
#5 /var/www/html/magentoce/facebook-php-ads-sdk-master/vendor/facebook/php-ads-sdk/src/FacebookAds/Object/AbstractCrudObject.php(327): FacebookAds\Object\AbstractCrudObject->create(Array)
#6 /var/www/html/magentoce/facebook-php-ads-sdk-master/vendor/facebook/php-ads-sdk/src/FacebookAds/Object/Traits/ObjectValidation.php(48): FacebookAds\Object\AbstractCrudObject->save(Array)
#7 /var/www/html/magentoce/app/code/local/Ens/Fbapp/Block/Traffic.php(229): FacebookAds\Object\AdSet->validate()

**Comment by faisal847** [comment]
@duliomatos i have a confusion. i want to show a catalog on my facebook page same as like shopify did on their page. you can see it here: https://www.facebook.com/shopify/

My confusion is that i have programmatically uploaded the csv file as documented and made a catalog as well. In this case, do we need campaign and adsets? if negative, how can we show the uploaded CSV on my facebook page? please guide me in this

**Comment by faisal847** [comment]
@duliomatos this is the curl log i get while creating the adset:

curl \
  -F 'account_id=act_<account_id>' \
  -F 'name=My First AdSet' \
  -F 'billing_event=IMPRESSIONS' \
  -F 'campaign_id=<campaign_id>' \
  -F 'targeting={"geo_locations":{"countries":["GB"]},"interests":[{"id":"<id>","name":"Facebook"}]}' \
  -F 'access_token=<access_token>' \
  -F 'appsecret_proof=<appsecret_proof>' \
  https://graph.facebook.com/v2.6/act_<account_id>/adsets


i have redacted my id's, on frontend i am getting invalid parameter.

Please help
