### ISSUE TITLE
Get total Spent in another timezone that accounts

### ISSUE THREAD

**Issue by chicag0** [facebook/facebook-php-ads-sdk#175]
Our database stores most dates as UTC, but some of our vendors use different timezones (PDT).

I would LOVE to be able to get an AdSets amount spent in another timezone that the one my account is sent to.

**Comment by duliomatos** [comment]
Hey @chicag0, the metrics follows the timezone for your account (how to change here: https://www.facebook.com/business/help/754049591334898). You probably could use Insights api and if you break down hourly to emulate any timezone  (https://developers.facebook.com/docs/marketing-api/reference/ad-account/insights/).
