### ISSUE TITLE
Unable to retrieve AD_NAME from getInsightsAsync job

### ISSUE THREAD

**Issue by jesusjjf** [facebook/facebook-php-ads-sdk#177]
I am unable to retrieve the ad name from the results in the async job.
Looks like everything else is collecting fine.
I am asking for the `AD_NAME` in the fields `array`.

```php
use Facebook\Facebook;
use FacebookAds\Api;
use FacebookAds\Object\AdAccount;
use FacebookAds\Object\Fields\InsightsFields;
use FacebookAds\Object\Values\InsightsLevels;

$account = new AdAccount('act_xxxxxxxxxxxx');
$cursor = $account->getInsightsAsync(
  array(
    InsightsFields::AD_ID,
    InsightsFields::AD_NAME,
    InsightsFields::REACH,
    InsightsFields::SPEND
  ),
  array(
    'level' => InsightsLevels::AD,
    'time_range' => array(
      'since' => '2015-12-27',
      'until' => '2016-01-27'
    )
  )
);
$cursor->read();
while(!$cursor->isComplete()) {
  sleep(1);
  $cursor->read();
}
$cursor = $cursor->getResult();
echo '<table class="table table-striped"><thead><tr>';
echo '<th>Ad Id</th><th>Ad Name</th><th>Reach</th><th>Spend</th>';
echo '</tr></thead><tbody>';
foreach ($cursor as $i=>$c) {
  echo '<tr>';
  echo '<td>' . $c->{InsightsFields::AD_ID} . '</td>';
  echo '<td>' . $c->{InsightsFields::AD_NAME} . '</td>';
  echo '<td>' . $c->{InsightsFields::REACH} . '</td>';
  echo '<td>' . $c->{InsightsFields::SPEND} . '</td>';
  echo '</tr>';
}
echo '</tbody></table>';
```

And the table output:

Ad Id | Ad Name | Reach | Spend 
------|---------|-------|------
12345 |         | 123   | 12.34
12345 |         | 123   | 12.34
12345 |         | 123   | 12.34
12345 |         | 123   | 12.34

**Comment by jesusjjf** [comment]
I am getting an additional error as well 
```
Fatal error: Undefined class constant 'DEEPLINK_CLICKS'
```

I am using `php-ads-sdk` version `2.5.1` and I can see that my local copy of the library is missing several constants in the `FacebookAds/Object/Fields/InsightsFields.php` file. 

I have tried upgrading all the packages - `composer update`, but I am getting the same result.

**Comment by jesusjjf** [comment]
I am unable to get it to work with `composer`.
After executing `composer require facebook/php-ads-sdk` , I deleted it with `rm -rf vendor/facebook/php-ads-sdk` and then did a git clone it in the same spot from the live repo and worked perfectly.

Not sure why `composer` is not installing the latest version of the library.

**Comment by duliomatos** [comment]
Thx for reporting @jesusjjf. In the next bug fix release we should have these fixes available to composer very soon.
