### ISSUE TITLE
Unable to get name of ad account

### ISSUE THREAD

**Issue by benjamin-schaefer** [facebook/facebook-php-ads-sdk#178]
Hello,
what I want to do is getting a list of all ad accounts for a user. I use the following code:
  `echo "<br>Account ID: ".$account->{AdAccountFields::ACCOUNT_ID};
   echo "<br>Account Name: ".$account->{AdAccountFields::NAME};`
I get the correct account ID, but the name is always empty. In the marketing api reference on https://developers.facebook.com/docs/marketing-api/reference/ad-account, I find the following description for the attribute "name":

> Name of the account. If the account name is not set, the name of the first admin visible to the user will be returned

Any ideas why the name is empty?

Kindly regards, Benjamin

**Comment by duliomatos** [comment]
Hello @benjamin-schaefer, when you real any entity you should pass the fields you want available. e.g.

```php
use FacebookAds\Object\AdAccount;
use FacebookAds\Object\Fields\AdAccountFields;

$account = new AdAccount($ad_account_id);
$fields = array(
  AdAccountFields::NAME,
);

$account->read($fields);

echo $account->{AdAccountFields::NAME}.PHP_EOL;
```

**Comment by duliomatos** [comment]
Closing for now, you should also be able to get the names if you pass the pass the name field when calling `AdUser->getAdAccounts()`.
