### ISSUE TITLE
Unable to create Custom Audiece

### ISSUE THREAD

**Issue by codingquark** [facebook/facebook-php-ads-sdk#180]
While creating new blank [custom audience](https://developers.facebook.com/docs/marketing-api/reference/custom-audience#Creating), I'm getting:

```
AuthorizationException in RequestException.php line 137:
(#2654) Failed to create custom audience
```

Permissions available with my access token are: `read_page_mailboxes, ads_management, ads_read, manage_pages, read_audience_network_insights, public_profile` (generated from access token debugger).

With the same token, I can make custom audience from Graph API Explorer (via act_xxx/customaudiences end point).

My PHP is code almost identical to that given in the docs' example.

```php
$audience = new CustomAudience(null, $accountId);

$audience->setData(array(
    CustomAudienceFields::NAME => $name,
    CustomAudienceFields::SUBTYPE => CustomAudienceSubtypes::CUSTOM,
));

$response = $audience->create();
```

Because I'm able to create audiences from the tool and not from the SDK, seems like a bug to me.

**Comment by duliomatos** [comment]
Hello @codingquark! Yeah, you should experience the same behavior on both the sdk and graph explorer. Are you initializing the API code with both the access token and the app secret?
One obvious check is to make sure the person that owns the token do has permission for this ad account.

**Comment by codingquark** [comment]
Thanks for the reply @duliomatos :)

It's my own ad account and token.

I am able to make other calls such as fetching the list of existing custom audiences etc. Here is how I'm initializing the API:

```php
AdsApi::init('app_id', 'app_secret', 'access_token');
```

**Comment by codingquark** [comment]
Thanks for the reply @duliomatos :)

It's my own ad account and access token I'm using.

I'm able to make other calls such as fetching the list of existing custom audiences. This is how I'm initializing the API:

```php
AdsApi::init('app_id', 'app_secret', 'access_token');
```

**Comment by duliomatos** [comment]
@codingquark Your code looks good, you should get the same behavior. Did you try using the exactly same token to compare between sdk and graph explorer? Make sure you select your app before generating the token in graph explorer, and you could compare the token to find if anything is missing in this tool: https://developers.facebook.com/tools/debug/accesstoken. Let me know if this is still an issue.

**Comment by duliomatos** [comment]
Closing as does not appears to be an sdk bug.

**Comment by codingquark** [comment]
The task has been delegated to another guy. If he reports the same issue, I'll report back here.
