### ISSUE TITLE
Using a proxy

### ISSUE THREAD

**Issue by yamsellem** [facebook/facebook-php-ads-sdk#183]
Is there a way to use a proxy with the sdk?

This is not stated anywhere :-(.
Thanks.

**Comment by pruno** [comment]
Network settings depends on the used, HTTP adapter. The one Bundled with the SDK use the PHP curl library and allow you to set options through

~~~php
$opts = Api::instance()->getClient()->getAdapter->getOpts();
~~~

This returns an arrayObject (reference), so something like this should do it: http://stackoverflow.com/questions/5211887/how-to-use-curl-via-a-proxy

~~~php
Api::instance()->getClient()->getAdapter->getOpts()->offsetSet(CURLOPT_PROXY, '<YOUR_PROXY>')
~~~

**Comment by duliomatos** [comment]
Closing... let us know of anything else

**Comment by fattalgazi** [comment]
I think getClient is removed from Api, could not find the right way. How can we set it now? 

Message: Call to undefined method FacebookAds\Api::getClient()

**Comment by fattalgazi** [comment]
Ok I found.

Api::instance()->getHttpClient()->getAdapter()->getOpts()->offsetSet(CURLOPT_INTERFACE, 'blabla');
