### ISSUE TITLE
Unsupported request for Adset->getAdCreatives

### ISSUE THREAD

**Issue by AloneCoder** [facebook/facebook-php-ads-sdk#184]
Hi!
I've upgraded to ads api v2.5.1 
And while trying to get adset's creatives I get an error "An error has occured: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api"
I'm using a sample code from your docs 
```php
$adSet = new FacebookAds\Object\AdSet($idFacebookAdset);
$adCreatives = $adSet->getAdCreatives([FacebookAds\Object\Fields\AdCreativeFields::NAME]);
```
AdSet object is fetched properly
What i've missed?

**Comment by paulbain** [comment]
It's almost certain that the ID you passed into the AdSet object is not correct. 
The adset is not actually fetched on instantiation so it would not error. 

Try doing the following to see if that is the case:

```
$adSet = new FacebookAds\Object\AdSet($idFacebookAdset);
$adSet->read(['name']);
```

**Comment by AloneCoder** [comment]
Nope, as i said earlier AdSet is fetched without any errors 
```php
$adSet = new FacebookAds\Object\AdSet($idFacebookAdset);
$adSet->read(['name']);
var_dump($adSet);
$adСreatives = $adSet->getAdCreatives([FacebookAds\Object\Fields\AdCreativeFields::NAME]);
```
Output is
```
class FacebookAds\Object\AdSet#26 (4) {
.....
protected $data =>
  array(26) {
        .....
    'name' =>  string(47) "%AdsetName%"
 }

}
```

**Comment by paulbain** [comment]
If you try the ID in the graph explorer and add `?metadata=1` what kind of object does it say it is?

**Comment by AloneCoder** [comment]
Thank you
You were right, it was a Campaign ID

But it's strange - if I init Ad/Adset/Campaign with the same id and try to read object's name - it works %)

**Comment by paulbain** [comment]
that's because the request is really doing `/<YOUR_ID>?fields=name` under the hood, and `name` is a valid field on all of these objects. 

Objects don't have a type in the standard response so we cannot validate this in the SDK.
