### ISSUE TITLE
getAdAccounts on User return only first 24 ad accounts

### ISSUE THREAD

**Issue by loncar** [facebook/facebook-php-ads-sdk#185]
I have code similar to that example from developers guide (https://github.com/facebook/facebook-php-ads-sdk/blob/master/DEVELOPER_GUIDE.md#1-reading-adaccounts):

```
$user = new AdUser('me');
$user->read(array(AdUserFields::ID));

$accounts = $user->getAdAccounts(array(
  AdAccountFields::ID,
  AdAccountFields::NAME,
));

// Print out the accounts
echo "Accounts:\n";
foreach($accounts as $account) {
  echo $account->id . ' - ' .$account->name."\n";
}
```
so $accounts is actually Cursor object that should loop and fetch data from all result pages?
My facebook user have more than 50 ad accounts and if fail to load them all. Is this a proper way to paginate through response or it is a bug?

Thanks

**Comment by loncar** [comment]
Sorry, I have look at source code and see that there are param for implicit fetch. So code should look like this :

```
$accounts = $user->getAdAccounts(array(
  AdAccountFields::ID,
  AdAccountFields::NAME,
));

$accounts->setUseImplicitFetch(true); // after it all it will look thought all pages

foreach...
```
I will close this issue.

**Comment by souflam** [comment]
@Ioncar You saved my Day :D, thnks :)
