### ISSUE TITLE
New Tag/Release requested

### ISSUE THREAD

**Issue by mbiagetti** [facebook/facebook-php-ads-sdk#189]
Hi!
I'm currently use this library with the last tagged version. Looking to the Facebook doc i see features of this library that are only on the master branch version (As example the  Custom Audience MultikeySchemaFields). 

Can you make a new tag of the library please? Or Are you planned to do a release/tag? 

Thank in advice

**Comment by duliomatos** [comment]
@mbiagetti, let us fix the issue you reported last week as well and tag a new release. Will keep this open until we have the fix and a new release.
