### ISSUE TITLE
Problem with CustomAudiences and Cursor implicit Fetch

### ISSUE THREAD

**Issue by mbiagetti** [facebook/facebook-php-ads-sdk#190]
Hi,
I want to retrieve the full list of the custom audience (with name and description attribute) of an account user.

If I run the following code:

```
Cursor::setDefaultUseImplicitFetch(true);
$account = new AdAccount('act_...');
$data = $account->getCustomAudiences(['name', 'description']);

```

I receive the following error:

> {"error":{"code":2500,"message":"Syntax error \u0022Expected end of string instead of \u0022%\u0022.\u0022 at character 4: name%2Cdescription","exception":"FacebookAds\\Http\\Exception\\AuthorizationException"}}

No problem without explicit the name and description fields as example:

`$data = $account->getCustomAudiences();`

or directly:

`$elems =$account->read(['customaudiences.limit(999){name,description}']);`

Thank in advice

**Comment by duliomatos** [comment]
Thx for reporting, @mbiagetti and @dbronnikov, I'm digging into this.

**Comment by mbiagetti** [comment]
thanks @duliomatos, work like a charm!

**Comment by duliomatos** [comment]
@mbiagetti, cool thx for confirming :-) will push 2.5.2 with the fix
