### ISSUE TITLE
You are missing some campaign objectives?

### ISSUE THREAD

**Issue by newerton** [facebook/facebook-php-ads-sdk#195]
Missing:
BRAND_AWARENESS (in Pull request)
EXTERNAL
LEAD_GENERATION

**Comment by duliomatos** [comment]
Thx for reporting @newerton. We are improving the way these API constants are synced with the SDK, I'll fix this with all the new objectives.

**Comment by newerton** [comment]
Thanks Dulio! (L)

Obrigado Dulio!  :+1:
