### ISSUE TITLE
Travis-ci integration?

### ISSUE THREAD

**Issue by bjeavons** [facebook/facebook-php-ads-sdk#20]
Have you considered travis-ci integration for automated testing and reporting?

Since the tests currently use a live FB app and ad account any automated testing may require:

1. an available test app and ad account for travis' use
1. or, configure travis testing to not require remote calls and thus no app, account, or access token

I suspect option 2 is the most likely.

**Comment by bjeavons** [comment]
Nice! https://github.com/facebook/facebook-php-ads-sdk/commit/9a023d9e5cf4ee97bd792ded28e24a18fc325f12

**Comment by pruno** [comment]
;)
