### ISSUE TITLE
Do i need campign creation in showing my catalog on facebook page?

### ISSUE THREAD

**Issue by faisal847** [facebook/facebook-php-ads-sdk#200]
i have a confusion. i want to show a catalog on my facebook page same as like shopify did on their page. you can see it here: https://www.facebook.com/shopify/

My confusion is that i have programmatically uploaded the csv file as documented and made a catalog as well. In this case, do we need campaign and adsets? if negative, how can we show the uploaded CSV on my facebook page? please guide me in this

**Comment by faisal847** [comment]
@pruno can you guide me in this please?

**Comment by duliomatos** [comment]
@faisal847, yeah, this catalog setup is for creating ads based on your products. We call this product Dynamic Product Ads. More info here about Dynamic Product Ads: https://www.facebook.com/business/a/online-sales/dynamic-product-ads
More info about API implementation of DPA: https://developers.facebook.com/docs/marketing-api/dynamic-product-ads/v2.6.
