### ISSUE TITLE
Location by Address

### ISSUE THREAD

**Issue by newerton** [facebook/facebook-php-ads-sdk#202]
I researched all the API, and found how to return a certain address.
Can anybody help me?

Sorry My English.

**Comment by duliomatos** [comment]
Hey @newerton, can you share what you are trying to achieve?

**Comment by newerton** [comment]
@duliomatos 
I'm using the class 'TargetingSearch', to get the country, State and City.
This same class, won't return Avenues or Streets.

I have to get this information using the Google Maps API?

**Comment by duliomatos** [comment]
It seems to be not supported. Please go through our docs to learn about these capabilities: https://developers.facebook.com/docs/marketing-api/targeting-search/v2.6#geo
