### ISSUE TITLE
getting 'name lookup timed out' while creating adcreative.

### ISSUE THREAD

**Issue by faisal847** [facebook/facebook-php-ads-sdk#203]
i am getting name lookup timed out errror while creating adCreative. 

Please help

**Comment by duliomatos** [comment]
Hey @faisal847,

This forum is for identifying bugs in the PHP SDK, so I would like to ask more details to find out if there is something wrong with the PHP code.

Can you please share more and try the same call using Graph Explorer? https://developers.facebook.com/tools/explorer/

**Comment by faisal847** [comment]
After redacting my id's, the following is my code:

$accessTokenForApi = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
            Api::init('xxxxxxxxxxxxxxxxxxx','xxxxxxxxxxxxxxxxxxxxxxxxx',$accessTokenForApi);
            $object_story_spec = new ObjectStorySpec();
            $object_story_spec->setData(array(
              ObjectStorySpecFields::PAGE_ID => xxxxxxxxxxxxxxxxxxxx,
              ObjectStorySpecFields::TEMPLATE_DATA => (new TemplateData())->setData(array(
                TemplateDataFields::MESSAGE => 'Test',
                TemplateDataFields::LINK => 'https://www.facebook.com/xxxxxxxxxxxxxxx',
                TemplateDataFields::NAME => 'Headline',
                TemplateDataFields::DESCRIPTION => 'Description',
                TemplateDataFields::MAX_PRODUCT_COUNT => 3,
              )),
            ));
            echo "/n";
            // print_r($object_story_spec);exit();
            // print_r($object_story_spec);
            // echo "Ts4t";exit();
            $creative = new AdCreative(null, $accountId2);
            $creative->setData(array(
                AdCreativeFields::NAME => 'Sample Promoted Post',
                AdCreativeFields::OBJECT_STORY_SPEC => $object_story_spec,
                AdCreativeFields::PRODUCT_SET_ID => $productSetId,
            ));
            $creative->create();
