### ISSUE TITLE
getting 'failed creating formpost data' while calling adImage

### ISSUE THREAD

**Issue by faisal847** [facebook/facebook-php-ads-sdk#205]
I am getting 'failed creating formpost data' and the following are the curl logs:

curl \
  -F 'name=xxxxxxxxxxxxxxxxxxxxx' \
  -F 'url=https://xxxxx.xxxxxxxxxxxxxxxxx.com/xxxxxxxxxxxxx' \
  -F 'filename=@https://xxx.xxxxxxx.com/xxxxx/media/blog/blog_1.jpg' \
  -F 'access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxmyeaZCSAWZAQ0dGcikaZAQwuLdbcWz2iZCW0cCKrtc7ZBrESuowNU7R7A5QkNe9wroysbCxxxxxxxxOiZCppn9btKZANsPfH2vsh15y939TUzYgQpzZBTb8zzeFFgxV5JZCUN7wHRjypMZAxxxxxxxxx' \
  -F 'appsecret_proof=1xxxxxxx31c20db37137xxxxxxxx49ee' \
  https://graph.facebook.com/v2.6/act_11xxxxxxxxxxxx0/adimages

Please help as i am not getting what's wrong with this as the path of the image is absolutely right.

**Comment by faisal847** [comment]
Resolved.

**Comment by nkmswot** [comment]
How do you get it resolved? Plz explain.. I'm also getting the same error.
