### ISSUE TITLE
getting Invalid Parameter while creating Ad

### ISSUE THREAD

**Issue by faisal847** [facebook/facebook-php-ads-sdk#206]
$ad = new Ad(null, $accountId2);
        $ad->setData(array(
          AdFields::CREATIVE => array('creative_id' => $creative->id),
          AdFields::NAME => 'My First Ad',
          AdFields::ADSET_ID => $adsetId,
        ));
        echo "no problem before create function";
        $ad->create();
        echo 'Ad ID:' . $ad->id . "\n";

the above is my code and below is the curl log: 

curl \
  -F 'creative={"creative_id":"xxxxxxxxxxxxxxx"}' \
  -F 'name=My First Ad' \
  -F 'adset_id=xxxxxxxxxxxxxx' \
  -F 'access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' \
  -F 'appsecret_proof=xxxxxxxxxxxxxxxxxxxxxxx' \
  https://graph.facebook.com/v2.6/act_111xxxxxxxxxxxxxxxxxx/ads

I am getting "Invalid parameter" response. Can anybody tell me what is wrong with the above?

**Comment by faisal847** [comment]
can anybody help me in this please?

**Comment by duliomatos** [comment]
Hello @faisal847. Can you share the code for the creative? Your code for the Ad has all the required params but there should be some validation based on the creative parameters.

**Comment by faisal847** [comment]
@duliomatos here is my code for adImage and adCreative

$image = new AdImage(null, $accountId2);
        $imgpath=dirname(__FILE__) . DIRECTORY_SEPARATOR . "/1.jpg";
        $image->setData(array(AdImageFields::FILENAME=>$imgpath,
            AdImageFields::NAME=>'FaisalShabirJan',
            AdImageFields::URL=>'https://xxx.xxxxxxxx.com/mxaxx'));
        try {
            $image->create();
        } catch (Exception $e) {
            echo $e->getMessage();
        }
        echo 'Image Hash: '.$hashimage=$image->{AdImageFields::HASH}.PHP_EOL. "\n";
        echo "adset id: ".$adsetId."\n";
        echo "account id: ".$accountId2."\n";

        $creative = new AdCreative(null, $accountId2);
        $creative->setData(array(
          AdCreativeFields::NAME => 'Sample Creative',
          AdCreativeFields::TITLE => 'my title',
          AdCreativeFields::BODY => 'my body',
          AdCreativeFields::OBJECT_URL => 'https://xxx.xxxxxxxx.com/mxaxx',
          AdCreativeFields::LINK_URL => 'https://xxx.xxxxxxxx.com/mxaxx',
          AdCreativeFields::IMAGE_HASH => $hashimage,
        ));
        $creative->create();
        echo "Creative ID:".$creative->id . "\n";

**Comment by faisal847** [comment]
@duliomatos please help as i am not able to get which parameter is invalid

**Comment by duliomatos** [comment]
Hey @faisal847, I've tested code similar to yours and it works. The exception should have more information about what happened, such as when I tried an invalid image_hash:

```
  HTTP status Code: 400
  Is transient: false
  Code: 100
  Error Subcode: 1487174
  Error User Title: Invalid Image Hash
  Error User Message: Image with Hash 234542 does not exist or does not belong to this account.
```

**Comment by faisal847** [comment]
Hello @duliomatos, i have resolved the issue, the issue was because of the
audience size was too small. I debugged and resolved. Thanks a lot :)

**Comment by duliomatos** [comment]
:-)

**Comment by bleedingbulb** [comment]
how you fix the audience size
