### ISSUE TITLE
You are calling a deprecated version of the Ads API. 

### ISSUE THREAD

**Issue by redsoxfan2499** [facebook/facebook-php-ads-sdk#208]
getting the error message: You are calling a deprecated version of the Ads API.  I went into the code and found a VERSION constant in the API.php file and changed it to 2.6 from 2.5.1 but still does not work. 
Any help would be greatly appreciated.

**Comment by duliomatos** [comment]
Hello @redsoxfan2499, both of these versions should work. The SDK version you are using is probably on v2.4 or earlier. If you are you using composer as a dependency manager can you check your composer.json and try to update the package?

**Comment by thegeorgelee** [comment]
I am having the same issue:
$ php composer.phar info
facebook/php-ads-sdk 2.5.2 PHP SDK for Facebook ads
facebook/php-sdk-v4  5.1.2 Facebook SDK for PHP

And my composer.json file states the following:
{
  "require": {
    "facebook/php-sdk-v4" : "~5.0",
    "facebook/php-ads-sdk": "2.5.*"
  }
}

$ php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

However I am getting this on api calls
(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v2.5.

Any ideas on how to fix this issue?  Is there something else I should look at?

**Comment by duliomatos** [comment]
Closing for now @redsoxfan2499. Pls check your SDK version on composer and reach out if needed. Thx!
