### ISSUE TITLE
You are calling a deprecated version of the Ads API. Please update to the latest version: v2.6.

### ISSUE THREAD

**Issue by dujiadui** [facebook/facebook-php-ads-sdk#210]
Hi:
Follow https://developers.facebook.com/docs/marketing-api/quickstart guide
In step 8. Get Ad Account, it show "You are calling a deprecated version of the Ads API. Please update to the latest version: v2.6. the sdks". but the sdks is just download, where can i see my sdks version?and what should I do.

**Comment by duliomatos** [comment]
Hey @dujiadui! 

How did you get the SDK? If you are you using composer:

(You can follow the instructions on `README.me`)
Add the following to your composer.json file:
```json
{
    "require": {
        "facebook/php-ads-sdk": "2.6.*"
    }
}
```

Or please just go here to download:
https://github.com/facebook/facebook-php-ads-sdk/releases/tag/2.6.0

**Comment by duliomatos** [comment]
@dujiadui, did it help?

**Comment by duliomatos** [comment]
Closing, reach out if needed
