### ISSUE TITLE
Call to Action - Ad Creative

### ISSUE THREAD

**Issue by newerton** [facebook/facebook-php-ads-sdk#212]
APPLY_NOW is New or Deprecated?
I not found in the Changelog or Documentation.

![image](https://cloud.githubusercontent.com/assets/4175945/15550411/b48b4228-2287-11e6-94c7-658948ee7d53.png)

Send a PR?

**Comment by duliomatos** [comment]
Hey @newerton, thx for being so close to the community ;-)
I'll check it out, which branch of the SDK (master/legacy) or released version are you using?

**Comment by newerton** [comment]
@duliomatos I'm always the last version 2.6,

**Comment by goodwintheus** [comment]
Hi there folks,

I'm really new on here and I was wondering if you might be able to help me out. I run a small cinema in New Zealand and we are trying to set up our adverts on Facebook so they activated/deactivated based on real time weather. There are many online weather companies that provide an API- currently using weather triggers like that for google, but I can't for the life of me figure of how to do it on Facebook. I really appreciate you help and anything to get me started/in the right direction would be a huge help.

Thanks,

Theus

**Comment by mcross1882** [comment]
@newerton I believe this field has been deprecated as it is no longer in the [documentation for call to actions](https://developers.facebook.com/docs/marketing-api/reference/ad-creative-link-data-call-to-action/).

To validate you could send a request using the `APPLY_NOW` as a `call_to_action` value and see if the API accepts it.

**Comment by duliomatos** [comment]
Hey @newerton, just use the constant `BOOK_TRAVEL` instead, it will show the caption you want.
