### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by hekan** [facebook/facebook-php-ads-sdk#214]
Guys, how to get better explanation of errors?
I'm receiving "invalid parameter" during Ad object creation. The data seems to be good, so I have to detect which field has an error. Ver. 2.6

[ $data = array(
          AdFields::NAME => 'My Ad 06.06',
          AdFields::ADSET_ID => $ad_set_id,
          AdFields::CREATIVE => array(
                    'creative_id' => $ad_creative_id,
          ),
        );

        $ad = new Ad(null, 'act_'.$this->account_id);
        $ad->setData($data);

        $ad->create(array(
            Ad::STATUS_PARAM_NAME => Ad::STATUS_PAUSED,
        ));](url)

**Comment by hekan** [comment]
I didn't specify instagram_actor_id in AdCreative section, that was an erorr. Although I added     print_r($error_data); into Exception/RequestException.php's "create" function, and after that the whole error description become visible

**Comment by mcross1882** [comment]
With the previous versions (and possibly current) you can use `getErrorUserMessage` or `getErrorUserTitle` methods from the `RequestException` for more detailed error messaging. These will give you more than the `An unknown error` message that the generic message provides.

See these tests for more examples 

https://github.com/facebook/facebook-php-ads-sdk/blob/470970bed4bb4e5d293de420793f7e8bae5b35d7/test/FacebookAdsTest/Http/Exception/RequestExceptionTest.php#L56-L66

**Comment by duliomatos** [comment]
Hey @hekan, thx for raising the concern on how detailed are the error messages, I'm sharing this feedback with the API team. Closing as the solution was found.
