### ISSUE TITLE
Start_time for adset

### ISSUE THREAD

**Issue by hekan** [facebook/facebook-php-ads-sdk#216]
Guys, I can't set starting_time for the adset. When adset is created, the start date is:
[start_time] => 2016-06-11T13:00:00+0600
But then, when I read adset by id or observe it in ads manager, the start_date turns to creation date (today's one). Has anyone faced with this trouble

**Comment by mcross1882** [comment]
Hello @hekan without seeing more of your code I am unable to give a helpful diagnosis. However be sure you are setting the [`start_time` properly](https://github.com/facebook/facebook-php-ads-sdk/blob/master/test/FacebookAdsTest/Object/AdSetTest.php#L71). I have not experienced any issues with the SDK overwriting the `start_time`. So my best bet is this field is being passed incorrectly and Facebook is defaulting it.

**Comment by hekan** [comment]
Hi @mcross1882 ! Here's my code:
```
  $adset->setData(array(
            AdSetFields::NAME => $name,
            AdSetFields::OPTIMIZATION_GOAL => OptimizationGoals::LINK_CLICKS,
            AdSetFields::BILLING_EVENT => BillingEvents::LINK_CLICKS,
            AdSetFields::IS_AUTOBID => true,
            AdSetFields::DAILY_BUDGET => 4000,
            AdSetFields::CAMPAIGN_ID =>*********,
            AdSetFields::TARGETING => $targeting,
            AdSetFields::START_TIME => $start_time,
            AdSetFields::END_TIME => $end_time,
        ));
```
Start_time and end_time variables are set with following functions:
[public function getStartDate($day, $month)
    {
        $date_of_birth = $day . '.' . $month . '.' . $this->year;
        $date = new DateTime($date_of_birth);
        return $date->sub(new DateInterval('P2D'))->setTimezone(new DateTimeZone('Asia/Almaty'))->format(DateTime::ISO8601);
    }

    public function getEndDate($day, $month)
    {
        $date_of_birth = $day . '.' . $month . '.' . $this->year;
        $date = new DateTime($date_of_birth);
        return $date->add(new DateInterval('P1D'))->setTimezone(new DateTimeZone('Asia/Almaty'))->format(DateTime::ISO8601);
    }](url)

The dates are absolutely identical, and end_time sets perfectly, but start_tiime overrides as I said.

**Comment by mcross1882** [comment]
So I just tested this and can confirm the SDK is working (at least with my requests). Here are a few more notes..

- Facebook auto normalizes to UTC so you need to be aware of that when sending dates. 
- Instead of sending a dynamically built date, send a hardcoded date. Something simple like `2016-07-01` will work (although it will normalize to UTC so the value will change once you submit it).

**Comment by hekan** [comment]
@mcross1882 I have to substract two days from the date, thats why I'm using it. I'll try your advices, thanks!

**Comment by mcross1882** [comment]
Yeah I understand that but just for testing I would send static date values and then backtrack your logic from there. Good luck on the bug hunting!

**Comment by duliomatos** [comment]
Hello @hekan, I think that you created an adset with a start date in the past. When you do that the API sets the date to the creation time (which sounds more logical in my opinion) so if this was really the case the behavior is expected. 

Thx for participating in the community both to you and @mcross1882, who has been helping out a lot :-D
