### ISSUE TITLE
AdGroup Invalid parameter

### ISSUE THREAD

**Issue by murillobr** [facebook/facebook-php-ads-sdk#217]
Sorry for my English.

I'm trying to create Ad with code:

$ad = new Ad(null, $account->id);
    $ad->setData(array(
        AdFields::CREATIVE =>
        array('creative_id' => $creative->id),
        AdFields::NAME => 'My First Ad',
        AdFields::ADSET_ID => $adset->id,
    ));

    $ad->create();

shows error Invalid parameter

I tried all examples of documentation

My version is 2.6

**Comment by hekan** [comment]
The invalid parameter might be either in ad creative or in ad set, so you have to extend your error log in order to detect it. I had the same question, you may see it here https://github.com/facebook/facebook-php-ads-sdk/issues/214

**Comment by duliomatos** [comment]
Hey @murillobr, can you check the details of the exception using `getErrorUserMessage` or `getErrorUserTitle` as @mcross1882 suggested in #214?

**Comment by duliomatos** [comment]
Closing, let me know if there's anything further.
