### ISSUE TITLE
missing functions in AbstractArchivableCrudObject class in order to be able to pause and activate a Campaign or Ad

### ISSUE THREAD

**Issue by smorocho** [facebook/facebook-php-ads-sdk#218]
You need to add the following two functions to your SDK in ./src/FacebookAds/Object/AbstractArchivableCrudObject.php

```
  public function pause(array $params = array()) {
    $this->getApi()->call(
      $this->getNodePath(),
      RequestInterface::METHOD_POST,
      array_merge($params, array(
        $this->getStatusParamName() => static::STATUS_PAUSED)));
  }

  public function activate(array $params = array()) {
    $this->getApi()->call(
      $this->getNodePath(),
      RequestInterface::METHOD_POST,
      array_merge($params, array(
        $this->getStatusParamName() => static::STATUS_ACTIVE)));
  }

```

Then you can do something like
```

use FacebookAds\Object\Campaign;
$campaign = new Campaign(<CAMPAIGN_ID>);

$campaign->pause();
// or
$campaign->activate();

```

**Comment by mcross1882** [comment]
This can be done via the `$params` argument when calling `->create()` or `->update()`. However these helper functions are nice and more concise.

**Comment by duliomatos** [comment]
@smorocho For now you could just use the params as stated above, e.g.:

```php
use FacebookAds\Object\Campaign;
use FacebookAds\Object\Fields\CampaignFields;

$campaign = new Campaign($campaign_id);
$campaign->update(array(
  Campaign::STATUS_PARAM_NAME => Campaign::STATUS_ACTIVE,
));
```

The relevant docs are here:
https://developers.facebook.com/docs/marketing-api/reference/ad-campaign-group
Having helper methods may be good but maybe improving the reference docs examples could be a better option (specially as we have now a number of supported SDK's for different programming languages that ideally should behave the same), I'll keep this issue open to track.

**Comment by allentsai** [comment]
For some reason, *sometimes* updating my ad with a param does not update the status.  Is anyone else running into this issue?

**Comment by mcross1882** [comment]
@allentsai in this scenario your parent object is most likely disabled. The `effective_status` reflects the current status of the object *which may be overridden by its parent*. More info can be found here..

https://developers.facebook.com/docs/marketing-api/reference/adgroup/v2.7

The `configured_status` is synonymous to the `status` parameter and is what you should set when updating the Ad. 

If this does not fix the issue feel free to post a code example so we can see whats going on :+1:

**Comment by allentsai** [comment]
@mcross1882 - I've been setting status via 
```
$params = array(Ad::STATUS_PARAM_NAME => Campaign::STATUS_PAUSED);
$ad->update($params);
```
I'll include output of error_logs in a bit.

**Comment by mcross1882** [comment]
That looks correct, is your adset also enabled? If it isn't the adset will be paused regardless of the status you give it.

**Comment by allentsai** [comment]
@mcross1882 - No, the adset's status is set to paused.  Are you suggesting that I cannot pause an ad that belongs to a paused ad set?  This would preclude the behavior of pausing some of the ads under the adset, and then unpausing the adset.  In the dashboard, what happens is I see the adset paused, and the ads under it as active, but 'ad set paused' status.  I would expect to see the adset paused, and the ads under it paused as well.

**Comment by mcross1882** [comment]
Sorry, my wording was not super clear here. When you give an `Ad` a status via the API you are setting its `configured_status`. This will update to whatever status you give it `ACTIVE`, `PAUSED`, etc.. And this value should reflect immediately in the `configured_status` parameter via a `GET` request to the object.

With that being said, if you have an `ACTIVE` ad that is nested under a `PAUSED` adset it will inherit the `PAUSED` status and that will reflect via the `effective_status` parameter. You can update the status of an `Ad` regardless of the status of the adset. It will only inherit the status if the parent is `PAUSED` to prevent spending.

We use this daily and have had no issues so far with it (via the ads sdk and raw API requests).

**Comment by allentsai** [comment]
Ah, okay.  Yeah, so the problem I am experiencing is that sometimes, after sending a `PAUSED` status on create/update, the ad's `configured_status` is still `ACTIVE`.  I say "sometimes" because we are getting intermittent failures on one of our test suites involving ad status. Campaigns and ad sets always pause as we expect.  Maybe the Facebook API has occasional propagation issues, or a request is getting dropped without our realizing it.

Anyways, thanks for the help, and sorry for the spam.

**Comment by duliomatos** [comment]
Thx @mcross1882 for helping the community :-)
@allentsai, if this surfaces again, detailed logs could help a lot replicating an issue. What you reported could be an API bug (not restricted to the SDK) and you would be able to report here: https://developers.facebook.com/bugs/
