### ISSUE TITLE
Permission error accessing reports as analyst

### ISSUE THREAD

**Issue by siegerhansma** [facebook/facebook-php-ads-sdk#22]
I'm trying to get reports for a Facebook Ads account. I have successfully made a connection and added my account as an Analyst to the business account. 

This is the code I'm using to connect:

``` php
$session = $this->facebook->getSession();

        $ads = new Api($session);

        $account = new AdAccount('act_' . Config::get('services.facebook.adAccountId'));

        $fields = array('account_id', 'total_actions', 'spend');

        $params = array(
            'data_columns' => array (
                'account_id',
                'total_actions',
                'spend'
            ),
            'date_preset' => 'last_7_days',
        );


        $reports = $account->getReportsStats($fields, $params);

```

However I'm getting the following error when making the call: 

(#273) This Ads API call requires the user to be admin of the ad account. User xxxxxxxx not admin on ad account xxxxxxxxxxxxxxxxxxxxxxx.

Why would I need to be an admin when I can access the reports from the webinterface with an analyst account?

**Comment by AishwaryaRatheesh** [comment]
Is this solved? I have the same problem

**Comment by shalakhin** [comment]
The same here. Receive the same error message
