### ISSUE TITLE
Custom fields for adaccount insights question

### ISSUE THREAD

**Issue by AloneCoder** [facebook/facebook-php-ads-sdk#221]
Hello
I'm trying to upgrade to 2.6 from 2.5
Everything is ok except async adaccount stat

My code is
```php
$fields = array(
    \FacebookAds\Object\Fields\AdInsightsFields::AD_ID,
    \FacebookAds\Object\Fields\AdsInsightsFields::CAMPAIGN_ID,
    \FacebookAds\Object\Fields\AdsInsightsFields::IMPRESSIONS,
    \FacebookAds\Object\Fields\AdsInsightsFields::INLINE_LINK_CLICKS,
    \FacebookAds\Object\Fields\AdsInsightsFields::SPEND,
);
$timeInterval = array(
    'since' => date('Y-m-d', $tsStart),
    'until' => date('Y-m-d', $tsStart)
);
$params = array(
    'time_range' => $timeInterval,
    'level' => FacebookAds\Object\Values\AdsInsightsLevelValues::ADSET,
    'breakdowns' => [
        \FacebookAds\Object\Values\AdsInsightsBreakdownsValues::COUNTRY,
    ],
);
/** @var FacebookAds\Object\AdAccount $account */
$account = $this->getAdAccountObject($accountId);
$asyncJob = $account->getInsightsAsync($fields, $params);
```

And I'm getting error - Field ad_id is not supported
I tried to remove some of the fields and still experienced an error %field name% is not supported 

Is it a bug or what?

FYI
https://developers.facebook.com/docs/marketing-api/insights/async/v2.6 - uses deprecated in 2.6 code

**Comment by duliomatos** [comment]
Hello @AloneCoder, thx for reporting.

I tested this code with the latest from github, and it seems to work fine. Can you try cloning master to test? You could also enhance the logging by generating curl: (and share the results minus private info)
```php
use FacebookAds\Logger\CurlLogger;

Api::instance()->setLogger(new CurlLogger());
```
You may have to migrate some constants where the object changed name e.g., this two:
`FacebookAds\Object\Values\InsightsLevels::ADSET`
`\FacebookAds\Object\Values\InsightsBreakdowns::COUNTRY`

**Comment by AloneCoder** [comment]
There are no requests done yet before getting this error
My code works fine with blank array for fields, I set TYPE_CHECKER_STRICT_MODE to false and the code works fine too

Validation fails because the acceptable fields are 
```
account_id
async_percent_completion
async_status
date_start
date_stop
emails
friendly_name
id
is_bookmarked
is_running
schedule_id
time_completed
time_ref
action_attribution_windows
action_breakdowns
action_report_time
breakdowns
date_preset
default_summary
fields
filtering
level
product_id_limit
sort
summary
summary_action_breakdowns
time_increment
time_range
time_ranges
```

**Comment by duliomatos** [comment]
Awesome, it's clear now. TYPE_CHECKER_STRICT_MODE is already set to `false` for the next SDK release (v2.7), so you can keep it that way.

**Comment by AloneCoder** [comment]
Thanks for your reply

**Comment by duliomatos** [comment]
By the way, the flag is now fixed at master.
