### ISSUE TITLE
Max product count removed from Ad Creative spec

### ISSUE THREAD

**Issue by mcross1882** [facebook/facebook-php-ads-sdk#222]
From what I can see the max product count has been removed from the `2.6.0` release but this is still a valid DAT field. Is there a way to workaround this? Specifically we still need to be able to set the number of products displayed in a carousel ad.

**Comment by mcross1882** [comment]
For now I believe I can get around this via the `->setDataWithoutValidation($data)` method. However, if there is a better solution it would be greatly appreciated.

**Comment by duliomatos** [comment]
Hey @mcross1882, setting the exact number of products on a carousel is not supported anymore, from the changelog:

_Deprecated max_product_count since Facebook now automatically optimizes the number of products to show for Dynamic Product ads. In order to opt-out of carousel format, specify_ `force_single_link=true` _in object_story_spec._

**Comment by mcross1882** [comment]
@duliomatos this appears to be only for DPA ads. Will this also be happening to DAT ads as well?

**Comment by mcross1882** [comment]
Ahh it looks like the DAT documentation has been updated.

https://developers.facebook.com/docs/marketing-api/dynamic-product-ads/ads-management/v2.6

Thank you for pointing this out.

**Comment by mcross1882** [comment]
Sorry, that was the wrong link. Here is the documentation I have been referring too.

https://developers.facebook.com/docs/marketing-api/dynamic-ads-for-travel/ads-management

**Comment by duliomatos** [comment]
This change was supposed to be valid for any carousel-type creative, though the example in the link still shows the field. The doc may not be up to date, I'll follow up on that.

**Comment by mcross1882** [comment]
Thank you very much @duliomatos and thanks for the heads up. :+1:

**Comment by duliomatos** [comment]
Reported the doc example to be fixed as well. Closing
