### ISSUE TITLE
'api_update' is in PHP SDK?

### ISSUE THREAD

**Issue by newerton** [facebook/facebook-php-ads-sdk#224]
https://github.com/facebook/facebook-php-ads-sdk/blob/master/src/FacebookAds/Object/AbstractArchivableCrudObject.php#L66
https://github.com/facebook/facebook-php-ads-sdk/blob/master/src/FacebookAds/Object/AbstractArchivableCrudObject.php#L81

In my IDE, it shows that these functions are deprecated.

**Comment by duliomatos** [comment]
@newerton Now just update the parameter status of the objects
e.g.
```php
$adset->update(array(
  AdSet::STATUS_PARAM_NAME => AdSet::STATUS_DELETED,
));
```
or
```php
$adset->update(array(
  AdSet::STATUS_PARAM_NAME => AdSet::STATUS_ARCHIVED,
));

**Comment by newerton** [comment]
@duliomatos Thank you very much!
