### ISSUE TITLE
Stat fetching lasts too long

### ISSUE THREAD

**Issue by AloneCoder** [facebook/facebook-php-ads-sdk#225]
Hello
Another day, another problem 
Insights fetch lasts too long - I think there are problems with cursor
My code
```php
        $result = [];
        /** @var FacebookAds\Object\AdAccount $account */
        $account = $this->getAdAccountObject($accountId);
        /** @var \FacebookAds\Object\AsyncJobInsights $asyncJob */
        $asyncJob = $account->getInsightsAsync([], $params);
        $asyncJob->read();
        $iterationsCount = 0;
        while (!$asyncJob->isComplete()) {
            $asyncJob->read();
        }
        try {
            /** @var \FacebookAds\Cursor $stat */
            $stat = $asyncJob->getResult();
            $stat->setUseImplicitFetch(true);
            foreach ($stat as $statItem) {
                $result[] = $statItem->getData();
            }
        } catch (\FacebookAds\Http\Exception\RequestException $e) {
                throw $e;
        }
```

If I setUseImplicitFetch to false code works, but I want to use implicit fetch :)

Curl logs

```
curl \
  -F 'time_range={"since":"2016-07-06","until":"2016-07-06"}' \
  -F 'level=adset' \
  -F 'fields=["ad_id","adset_id","impressions","inline_link_clicks","spend"]' \
  -F 'breakdowns=["country"]' \
  -F 'access_token=%access_token%' \
  -F 'appsecret_proof=%appsecret_proff%' \
  https://graph.facebook.com/v2.6/act_%accountId%/insights

curl -G \
  -d 'access_token=%access token%' \
  -d 'appsecret_proof=%appsecret_proff%' \
  https://graph.facebook.com/v2.6/6052348658256

curl -G \
  -d 'access_token=%access token%' \
  -d 'appsecret_proof=%appsecret_proff%' \
  https://graph.facebook.com/v2.6/6052348658256/insights
```

What am I doing wrong?

**Comment by mcross1882** [comment]
@AloneCoder have you tried increasing the `limit` parameter? We noticed that they are quite low as defaults and can increase response latency. Upping it to a `1000` improved our performance.

**Comment by AloneCoder** [comment]
@mcross1882 It's better to say that slow means infinity in my case, cursor loops forever

**Comment by mcross1882** [comment]
Interesting how long did you let the job run for? We have been noticing some strange stuff with the insights edge lately. For instance, we can run an async report for one of our clients in 5 minutes. But if we repeat that same report with same system load, and same client it can take 2 1/2 hours to run. We have yet to pinpoint the exact issue. I will try to dig up some logs possibly related.

**Comment by AloneCoder** [comment]
7-8 hours

**Comment by AloneCoder** [comment]
Seems it was a temporal issue
Thx

**Comment by duliomatos** [comment]
Allright, @AloneCoder, ping here if this comes up again.
