### ISSUE TITLE
Instagram Ads Post Moderation delete comment issue

### ISSUE THREAD

**Issue by Hamzeh-Ahmad** [facebook/facebook-php-ads-sdk#226]
Am trying to use this call to delete  comment on an  #Instagram ad post

curl -X DELETE -G \
-d "access_token=<ACCESS_TOKEN>"\
-d "ad_id=<AD_ID>"\
"https://graph.facebook.com/<API_VERSION>/<INSTAGRAM_COMMENT_ID>"

however I get the following message 

{"error":{"message":"Unsupported delete request. Object with ID<AD_ID> does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https:\/\/developers.facebook.com\/docs\/graph-api","type":"GraphMethodException","code":100,"fbtrace_id":"At\/K4NqgQ+9"}}

am sure that the ad_id is valid and the permission are not missing. 

is there a better way to do, please advise ?

**Comment by duliomatos** [comment]
Hey @Hamzeh-Ahmad, this channel is for SDK-related bugs, can you please report this as an API bug? https://developers.facebook.com/bugs/
There you will also be able to communicate more details privately.
