### ISSUE TITLE
offline conversion api

### ISSUE THREAD

**Issue by Bolik777** [facebook/facebook-php-ads-sdk#227]
Hi guys,

do you have any roadmap when the offline conversion api will be supported by ads sdk?

thanks!

**Comment by duliomatos** [comment]
Hey @Bolik777, this API is in limited beta, that's why it's not yet on the SDK. But I will inquire further. Thx for bringing this into attention.

**Comment by duliomatos** [comment]
I don't have a date to share but it will be available when the API is finalized and open to everyone.
