### ISSUE TITLE
Update to v2.6 where no 2.6 is available

### ISSUE THREAD

**Issue by afkplus** [facebook/facebook-php-ads-sdk#228]
We have v2.5.2 installed through composer, and started getting this error this morning:

`(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v2.6.`

But I can't upgrade the SDK to 2.6 since I can't find it on github or anywhere. README file still have instructions for installing 2.5.*. Could this possible be a bug?

**Comment by duliomatos** [comment]
Hey @afkplus, you should be able to find 2.6.0 on composer or on the releases section of github: https://github.com/facebook/facebook-php-ads-sdk/releases. We just launched 2.7.1 if you want the latest.

Thx for reporting, I look into fixing the README section.

**Comment by afkplus** [comment]
Thanks. I was just writing an answer for myself. Updating composer to 2.6.* worked.
