### ISSUE TITLE
sharing audience

### ISSUE THREAD

**Issue by Bolik777** [facebook/facebook-php-ads-sdk#230]
what is the proper way to share custom audience using ads sdk? the api calls are documented here 
https://developers.facebook.com/docs/marketing-api/reference/custom-audience/adaccounts/
but they seem to be not supported by this sdk

**Comment by duliomatos** [comment]
Hey @Bolik777, please check out the api calls in these two pages:
- Create custom audience: https://developers.facebook.com/docs/marketing-api/reference/custom-audience?__mref=message_bubble
- Add/Remove people to/from a custom audience: https://developers.facebook.com/docs/marketing-api/reference/custom-audience/users/?__mref=message_bubble
