### ISSUE TITLE
AdAccount::getReachEstimate no longer returns a ReachEstimate.

### ISSUE THREAD

**Issue by kellegous** [facebook/facebook-php-ads-sdk#236]
In the 2.5 SDK, `AdAccount::getReachEstimate` returned a `ReachEstimate` object.

The 2.7.1 SDK returns a `FacebookAds\Cursor` that contains a `ReachEstimate`. This is a pretty tricky breaking change but it's also not clear that it should be returning a Cursor.

**Comment by duliomatos** [comment]
Hey @kellegous. From the 2.7 release on, we made a big structural change to auto-generate most of the objects, thx for pointing out this breaking change. I'll discuss internally the best approach on this issue.

**Comment by duliomatos** [comment]
@kellegous I am sorry we missed this in the list of breaking changes. We are now forcing the return of  all endpoints to be a Cursor to equalize the behavior. I'm updating the release message to reflect this.

**Comment by duliomatos** [comment]
New Breaking Change message:
* **Edges from an object now return a Cursor**: To equalize the behavior of edges, now all edges from an object return a `Cursor`. In the past there were exceptions to this rule, e.g.: `AdAccount::getReachEstimate` used to return a `ReachEstimate`.
