### ISSUE TITLE
why show "Invalid parameter"

### ISSUE THREAD

**Issue by kimyoonchul** [facebook/facebook-php-ads-sdk#244]
Hi

I go examples/adgroup_creation.php

but 

it error!

Fatal error: Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message 'Invalid parameter' in /var/www/fb_marketing/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php:140 Stack trace: #0 /var/www/fb_marketing/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Client.php(215): FacebookAds\Http\Exception\RequestException::create(Object(FacebookAds\Http\Response)) #1 /var/www/fb_marketing/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Request.php(282): FacebookAds\Http\Client->sendRequest(Object(FacebookAds\Http\Request)) #2 /var/www/fb_marketing/vendor/facebook/php-ads-sdk/src/FacebookAds/Api.php(152): FacebookAds\Http\Request->execute() #3 /var/www/fb_marketing/vendor/facebook/php-ads-sdk/src/FacebookAds/Api.php(194): FacebookAds\Api->executeRequest(Object(FacebookAds\Http\Request)) #4 /var/www/fb_marketing/vendor/facebook/php-ads-sdk/src/FacebookAds/Object/AbstractCrudObject.php(241): FacebookAds\Api->call('/act_5484981485...', 'GET', Array) #5 /var/www/fb_marketing/e in /var/www/fb_marketing/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php on line 140

I don't know that error

it seem to be url error point
https://graph.facebook.com/v2.7/act_548498148589528?access_token=EAABoENI2yGEBAECPxdlGeQC0iHpqGtMt6zRVRSpOVSsnsfbc2rs7fpDQrgcl99vyIVybeTkbGTF0GZBHgphu9fFYfXdZBHCHlnzXNoAydao1O3vAdy2DSIEZBhQ7rtwrWFENMcHVsIVs8ZA67Xa4BGnl1WbPsFbnM5Suh1XSZAQZDZD&appsecret_proof=d74c2abe08259e0cdca366daaa200f6bb3538e305e86d5db64524b608b5352d9

{
   "error": {
      "message": "Invalid parameter",
      "type": "OAuthException",
      "code": 100,
      "error_subcode": 1487168,
      "is_transient": false,
      "error_user_title": "The account is invalid",
      "error_user_msg": "The account is invalid",
      "fbtrace_id": "A9lRuJGtyuo"
   }
}

why it show Invalid parameter

I correct insert access_token, app_id, app_secrect, account_id

// Configurations
$access_token = 'EAABoENI2yGEBAECPxdlGeQC0iHpqGtMt6zRVRSpOVSsnsfbc2rs7fpDQrgcl99vyIVybeTkbGTF0GZBHgphu9fFYfXdZBHCHlnzXNoAydao1O3vAdy2DSIEZBhQ7rtwrWFENMcHVsIVs8ZA67Xa4BGnl1WbPsFbnM5Suh1XSZAQZDZD';
$app_id = '114421455571041';
$app_secret = '91796ca94fdd42fe4b1a6079e522f99c';
$account_id = 'act_548498148589528';

tell me what's the problem

**Comment by guxuoss** [comment]
Thanks for reporting the Ads API SDK bug!  

The ad account id you provided 548498148589528 is not ad account id but a user id.  You need to go to Ads Manager to create a new ad account.  You may also need to setup the payment method before you can create any ad.  You can create campaigns or adsets without payment.

**Comment by raokaleemullah** [comment]
I am getting he same problem any one tell how can i fix this problem 
Fatal error: Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message 'Invalid appsecret_proof provided in the API argument' in D:\wamp\www\mod\src\FacebookAds\Http\Exception\RequestException.php on line 140

FacebookAds\Http\Exception\AuthorizationException: Invalid appsecret_proof provided in the API argument in D:\wamp\www\mod\src\FacebookAds\Http\Exception\RequestException.php on line 140

i am wating for your response  if you know what changes facebook changes in api let me know thanks i

**Comment by evalenzuela** [comment]
Did anyone solve this issue?

**Comment by raokaleemullah** [comment]
you have deleted your application from the facebook. or  you are not using
current account.   if you insert correct everything then you did not insert
token. Token is expired after every hour ok Please check that one you will
be fixed
Regards Kaleemullah Software Engineer

On Sun, Jul 9, 2017 at 8:53 PM, Eduardo Valenzuela <notifications@github.com

**Comment by the-chase** [comment]
I'm getting a similar error, i've checked everything in this thread to no avail. Did anyone come right ?

Fatal error: Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message '(#3) Application does not have the capability to make this API call.' in /var/www/seoforge/facebook_runs/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php:144 Stack trace: #0 /var/www/seoforge/facebook_runs/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Client.php(215): FacebookAds\Http\Exception\RequestException::create(Object(FacebookAds\Http\Response)) #1 /var/www/seoforge/facebook_runs/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Request.php(282): FacebookAds\Http\Client->sendRequest(Object(FacebookAds\Http\Request)) #2 /var/www/seoforge/facebook_runs/vendor/facebook/php-ads-sdk/src/FacebookAds/Api.php(162): FacebookAds\Http\Request->execute() #3 /var/www/seoforge/facebook_runs/vendor/facebook/php-ads-sdk/src/FacebookAds/Api.php(204): FacebookAds\Api->executeRequest(Object(FacebookAds\Http\Request)) #4 /var/www/seoforge/facebook_runs/vendor/facebook/php-ads-sdk/src/FacebookAds/ApiReques in /var/www/seoforge/facebook_runs/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php on line 144

**Comment by raokaleemullah** [comment]
yes i can fix this issue

**Comment by the-chase** [comment]
@ raokaleemullah,  how can I go about fixing this particular problem  ?
