### ISSUE TITLE
Can we filter the Campaigns with "objective" ?

### ISSUE THREAD

**Issue by zengyi584920** [facebook/facebook-php-ads-sdk#246]
**EG.**
[FB_API_GRAPH.]/[FB_API_VERSION]/act_adaccountid/campaigns?objective=['MOBILE_APP_ENGAGEMENT','MOBILE_APP_INSTALLS']&access_token=".$this->access_token

Maybe this method is wrong. Who can  tell me what can i do ? Thanks.

**Comment by guxuoss** [comment]
Thanks for reporting the Ads API SDK bug!  

Our SDK is not supporting filtering natively for now.  We may consider to add this feature in future releases. The workaround now is to use custom param to your SDK calls. 

You need to use "filtering" param which is generally supported by all Facebook edge APIs.  In your case, the filter param will be like: `filtering=[{"field":"objective","operator":"IN","value":["MOBILE_APP_ENGAGEMENT","MOBILE_APP_INSTALLS"]}]"`
