### ISSUE TITLE
how to get list of active campaign sort by reach

### ISSUE THREAD

**Issue by ahsanrana** [facebook/facebook-php-ads-sdk#255]
hi there ,
i am using archiveable status :active , passing it to adaccount->getcampaigns(fields,param) to get active campaign , and its working 
but to get campaigns sort on bases of reach_descending i need to wort with adaccount->getinsights()
2 different requests and 2 different methods and also can not use other request ( requests mentions above) result in 2nd 1,
my question is that is there any possible way to get campaigns with status active and sort by reach_descending in single request 
if not please add some

**Comment by cloudxu** [comment]
@ahsanrana, Thanks for the feedback. insights itself is a big complicated system and sort by reach will be a very very expensive call at this moment unfortunately. We will have your feedback into our task system, but expect this request will come with some bigger infra change.

**Comment by ahsanrana** [comment]
thanks 4 ur reply ,
1)when i use insights sort by reach , i dont get campaigns with 0 reach , m working with reach descending  please reply ...

2) working with insights"limit" . i m using next() "ref=https://developers.facebook.com/docs/php/howto/example_pagination_basic"
bt in every response i m getting i m receiving a link from next(), even its the last page 
// i made some changes in ur function , (this might help to understand what i m saying)
/edited /
public function getNext() {
    $content = $this->getLastResponse()->getContent();
    if (isset($content['paging']['next'])) {
      return $content['paging']['next'];
    }
   
    return null;
  }


3) u r providing limit parameter in insights , please also provide page parameter 

please correct me where i m wrong
