### ISSUE TITLE
Deprecated version of the API

### ISSUE THREAD

**Issue by quebecblogue** [facebook/facebook-php-ads-sdk#256]
Hi,

I've tried the SDK but unfortunately I can't connect because the API is outdated. I just freshly git&compose it.

Fatal error: Uncaught FacebookAds\Http\Exception\AuthorizationException: (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v2.8.

Is it something I am not getting or the new version is coming?

Regards,

**Comment by avastamin** [comment]
There is already version 2.8. Update your composer     "facebook/php-ads-sdk": "2.8.*"

then run`composer update`.

**Comment by JiamingFB** [comment]
(Assuming issue resolved since there is no further comment.)
