### ISSUE TITLE
Missing getEndpoint() method in ProductFeedUpload

### ISSUE THREAD

**Issue by suzuki** [facebook/facebook-php-ads-sdk#259]
### Overview
- We can not create ProductFeedUpload.
### Cause
- In the "Legacy", we found `getEndpoint()` method is `ProductFeedUpload` class.
  - https://github.com/facebook/facebook-php-ads-sdk/blob/legacy/src/FacebookAds/Object/ProductFeedUpload.php#L40-L42
- But, now, we can not find this method.
  - https://github.com/facebook/facebook-php-ads-sdk/blob/837ea5db3f01a701260adf97b9018478c90b60e5/src/FacebookAds/Object/ProductFeedUpload.php
    -  This is latest commit when I wrote this issue.
### Expect
- In v2.8, we can use `uploads` endpoint.
  - https://developers.facebook.com/docs/marketing-api/reference/product-feed/uploads/v2.8
  - https://developers.facebook.com/docs/marketing-api/dynamic-product-ads/product-catalog#direct-upload-product-feed
- Add this code to `ProductFeedUpload`

``` php
    protected function getEndpoint() {
        return 'uploads';
    }
```

**Comment by daphyFB** [comment]
Thanks for reporting SDK bugs! We're working on a fix right now and should be included in the next push. Thanks again!
