### ISSUE TITLE
Hung occurred in the function isZipFile when creating an AdImage

### ISSUE THREAD

**Issue by howlittlegrass** [facebook/facebook-php-ads-sdk#263]
When i create an AdImage with the following PHP code, i found it hung in the function AdImage::create(). 

```
$account = 'act_xxxxxx';
$image = new AdImage(null, $account);
$image->{AdImageFields::FILENAME} = '/tmp/2.jpg';
$result = $image->create();
echo 'Image Hash: '.$image->{AdImageFields::HASH}.PHP_EOL;
```

Exactly, the program is blocked on the "finfo_open" statement in function AdImage::isZipFile(), 
when i comment the branch of isZipFile (like below) in AdImage::create(), it works.

```
public function create(array $params = array()) {
    if ($this->data[static::FIELD_ID]) {
      throw new \Exception("Object has already an ID");
    }

    // if ($this->isZipFile($this->data[AdImageFields::FILENAME])) {
    //   throw new \RuntimeException(
    //     "use AdImage::createFromZip to create zip files");
    // }

    $data = $this->exportData();
    $filename = $data[AdImageFields::FILENAME];
    unset($data[AdImageFields::FILENAME]);
    $params = array_merge($data, $params);
    $request = $this->getApi()->prepareRequest(
      '/'.$this->assureParentId().'/'.$this->getEndpoint(),
      RequestInterface::METHOD_POST,
      $params
    );

    $request->getFileParams()->offsetSet(AdImageFields::FILENAME, $filename);
    $response = $this->getApi()->executeRequest($request);
    var_dump($response);
    $this->clearHistory();
    $content = $response->getContent();

    $data = $content['images']
      [basename($this->{AdImageFields::FILENAME})];

    $this->data[AdImageFields::HASH] = $data[AdImageFields::HASH];

    $this->data[static::FIELD_ID]
      = substr($this->getParentId(), 4).':'.$this->data[AdImageFields::HASH];
    return $this;
  }
```

Is there somthing wrong I did? Any help will be appreciate.
Thanks!

### My OS:
 x86_64 GNU/Linux

### My PHP version:
PHP 5.6.9 (cli) (built: Jan 31 2016 01:11:22) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend Guard Loader v3.3, Copyright (c) 1998-2014, by Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies

### Facebook PHP Ads sdk version:
"facebook/php-ads-sdk": "2.7.*"

**Comment by cloudxu** [comment]
Can you do finfo_open with '/tmp/2.jpg'? I believe it is some thing related to your file. Is some other program holding a handle of this file still? Feel free to reopen the bug if that does not solve the issue.
