### ISSUE TITLE
How to fetch Report data from business.facebook.com using the Ads API?

### ISSUE THREAD

**Issue by saurabhrocksoul** [facebook/facebook-php-ads-sdk#264]
I have a business account, and a developer account on facebook.
I was able to install API (v2.8) and test it, but now I am not getting what methods (of API) shall be used to fetch data from business.facebook.com.

How dimensions, metrics and fields are used in the API?

**Comment by cloudxu** [comment]
I believe you are talking about Business Manager API. Please look at:

https://developers.facebook.com/docs/marketing-api/business-manager-api
