### ISSUE TITLE
Application does not have the capability to make this API call

### ISSUE THREAD

**Issue by manishkvaish** [facebook/facebook-php-ads-sdk#266]
trying to read my ad account.
 but getting this error:

 Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message '(#3) Application does not have the capability to make this API call.

**Comment by daphyFB** [comment]
Hi, thank you for reporting SDK issues!
The authorization exception can be from Facebook Ads APIs or other Facebook APIs. Please make sure that the user and/or ads account you used have proper permission to do what you want. Please let us know if this doesn't help. Thanks!

**Comment by daphyFB** [comment]
Hi, I'll be closing the issue; please feel free to reopen the issue if you have further questions!

**Comment by matthewfisher01** [comment]
hello! i see this was closed a month ago, I am having issues with the error:
(#3) Application does not have the capability to make this API call

it is while simply migrating pages in the business manager - no programming on my end involved.  any ideas on what I can do to?  I am the only administrator on this site.
