### ISSUE TITLE
Cannot get the attributes of AdImage by AdImage::getSelf()

### ISSUE THREAD

**Issue by howlittlegrass** [facebook/facebook-php-ads-sdk#267]
Refer to: https://developers.facebook.com/docs/marketing-api/reference/ad-image
There is no way to get attirbutes of AdImage by image ID directly. If to do so, an error as below will occur:

'{ ["message"]=> string(103) "(#803) Some of the aliases you requested do not exist: "11111111111111:2222222222222" ["type"]=> string(14) "OAuthException" ["code"]=> int(803) ["fbtrace_id"]=> string(11) "F64IVjYGDNn" } '

(_Note: the actual ID has been repaced as "11111111111111:2222222222222" here_)

My understanding, the following facebook api code uses the ID of AdImage to post a request directly, so  an exception will be raised when invoking it. 
Is there something wrong in the code? or my understanding is not correct?

```
public function getSelf(array $fields = array(), array $params = array(), $pending = false) {
    $this->assureId();
    $param_types = array(
    );
    $enums = array(
    );
    $request = new ApiRequest(
      $this->api,
      $this->data['id'],
      RequestInterface::METHOD_GET,
      '/',
      new AdImage(),
      'NODE',
      AdImage::getFieldsEnum()->getValues(),
      new TypeChecker($param_types, $enums)
    );
    $request->addParams($params);
    $request->addFields($fields);
    return $pending ? $request : $request->execute();
  }
```
-------------------------------------------

When I modified the function code as below (post a request with the account ID and specify the endpoint as "adimages"), then i got the correct AdImage attributes.
```
public function getSelf(array $fields = array(), array $params = array(), $pending = false) {
    $this->assureId();

    $param_types = array(
    );
    $enums = array(
    );

    // $request = new ApiRequest(
    //   $this->api,
    //   $this->data['id'],
    //   $this->getParentId(),
    //   RequestInterface::METHOD_GET,
    //   '/',
    //   new AdImage(),
    //   'NODE',
    //   AdImage::getFieldsEnum()->getValues(),
    //   new TypeChecker($param_types, $enums)
    // );

    // $request->addParams($params);
    // $request->addFields($fields);
    // return $pending ? $request : $request->execute();

    $request = $this->getApi()->prepareRequest(
      '/'.$this->assureParentId().'/'.$this->getEndpoint(),
      RequestInterface::METHOD_GET,
      $fields
    );

    // $request->getFileParams()->offsetSet(AdImageFields::FILENAME, $filename);
    $response = $this->getApi()->executeRequest($request);
    $this->clearHistory();
    $content = $response->getContent();

    return $content;
  }
```

Thanks!

-------------------------------------
My facebook api version is v2.7

**Comment by lintaocui** [comment]
hi @howlittlegrass , you are not calling the API properly. you cannot use the id of ad_images to retrieve it.
To retrieve specific images from an ad account, specify the hashes of the images in a "hashes" array as follows:

```
use FacebookAds\Object\AdAccount;

$account = new AdAccount('act_<AD_ACCOUNT_ID>');
$images = $account->getAdImages(
  array(),
  array(
    'hashes' => array(
      '<IMAGE_1_HASH>',
      '<IMAGE_2_HASH>',
    ),
  ));
```

**Comment by howlittlegrass** [comment]
@lintaocui, thanks for providing another method.

and also, the bug of AdImage::getSelf has been confirmed, refer to:
https://developers.facebook.com/bugs/363738700650328/

Thanks again!

**Comment by howlittlegrass** [comment]
@lintaocui,
thanks for providing a method.

The code i attached above (using id of ad_images) is the released code of facebook api (not my personal code), github link is:
https://github.com/facebook/facebook-php-ads-sdk/blob/master/src/FacebookAds/Object/AdImage.php

Please check if the method getSelf in AdImage.php has some issue or not.

More details:
https://developers.facebook.com/bugs/363738700650328/

Thanks!
