### ISSUE TITLE
Error get insights by account

### ISSUE THREAD

**Issue by Smolevich** [facebook/facebook-php-ads-sdk#268]
I want to get insights by account using facebook-php-ads-sdk v 2.8.1.
`
$date = new DateTime('-1 day');
$fields = [
            InsightsFields::ACCOUNT_ID,
            InsightsFields::ACCOUNT_NAME,
            InsightsFields::AD_NAME,
            InsightsFields::AD_ID,
            InsightsFields::CAMPAIGN_ID,
            InsightsFields::CAMPAIGN_NAME,
            InsightsFields::UNIQUE_CLICKS,
            InsightsFields::IMPRESSIONS,
            InsightsFields::SPEND,
            InsightsFields::DATE_START,
            InsightsFields::DATE_STOP
];
$params = [
   'time_range' => [
                'since' => $date->format('Y-m-d'),
                'until' => $date->format('Y-m-d')
            ],
            'time_increment' => 1,
            'level' => InsightsLevels::CAMPAIGN,
            'limit' => 150
];
$adAccount = new AdAccount(<ACCOUNT ID>);
$insights = $adAccount->getInsights($fields, $params); // Exception
foreach ($insights as $id => $insight) {
    foreach($fields as $field) {
           $result[$id][$field] = $insight->field;
    }
}
`
Method getInsights throw Exception: Unsupported get request. Object with ID <ACCOUNT ID> does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api
Debugging  class AdAccount method getInsights gave the following results:
Genarate path to Graph API - /<ACCOUNT ID>/insights?fields=account_id,account_name,ad_name,ad_id,campaign_id,campaign_name,unique_clicks,impressions,spend,date_start&level=campaign&time_increment=1&time_range={"since":"<DATE START>","until":"<DATE_END>"} 
In documenation https://developers.facebook.com/docs/marketing-api/insights/overview/v2.8 write about url insights for account must be following view
act_<ACCOUNT ID>/insights

**Comment by guxuoss** [comment]
Thanks for the feedback!  I am not fully understand your issue.  Are you saying that when you make the "getInsights" call, you got a API call like "vx.x//insights?..." or "vx.x/[number]/insights?...."?  I think the right way to initialize the ad account object is to use "act_" prefix.

Example:
https://github.com/facebook/facebook-php-ads-sdk/blob/53bee21251a9d898591708b96d1afa9e13516e3d/src/FacebookAds/Object/AdAccountGroupAccount.php

**Comment by Smolevich** [comment]
Thanks. I am undestand that to initialize the AdAccount with parameter 
` $adAccount = new AdAccount('act_' . <Account ID>);`
