### ISSUE TITLE
why i use lead ads api get the ad_name field is empty?what can i do?

### ISSUE THREAD

**Issue by anshao** [facebook/facebook-php-ads-sdk#270]
This is my code.
```
//fb lead ads api
Api::init($app_id, $app_screct, $app_page_access_token);
Api::instance();
$form = new Lead($leadgen_id);
$form_data = $form->read()->getData();
```
The `$form_data` value print_r() is:

```
Array
(
    [ad_id] =>
    [ad_name] =>
    [adset_id] =>
    [adset_name] =>
    [campaign_id] =>
    [campaign_name] =>
    [created_time] => 2016-12-19T11:59:51+0000
    [custom_disclaimer_responses] =>
    [field_data] => Array
        (
            [] => Array
                (
                    [name] => phone_number
                    [values] => Array
                        (
                            [] => +601xxxxx
                        )

                )

        )

    [form_id] =>
    [id] => 29631xxxxx2235
    [is_organic] =>
    [post] =>
)
```

I want to know why `ad_name` is empty.

from the facebook website download the .xls file，the `ad_name` is not empty.
![image](https://cloud.githubusercontent.com/assets/1137539/21313345/5920c5c2-c62c-11e6-9787-e8a9413636ed.png)

**Comment by cloudxu** [comment]
API and excel export are not 1:1 mapped functionality. And I think ad_name are not default for Lead read(). Please try to add parameters to read() and ask for the fields you want explicitly.

**Comment by egadirov** [comment]
@anshao Hello! How did you solve this problem? 

I need to get the fields:
 "**ad_name** | **adset_id** | **adset_name** | **campaign_id** | **campaign_name**". 
But the $form_data value comes without this fields, what am I doing wrong?

`
Array (

    [created_time] => 2017-08-31T12:48:55+0000
    [id] => *********************
    [field_data] => Array        (

            [0] => Array
                (

                    [name] => *********************
                    [values] => Array

                        (
                            [0] => 
                        )
                )

            [1] => Array
                (
                    [name] => email
                    [values] => Array
                        (
                            [0] => test@fb.com
                        )

                )

        )
)

`

**Comment by anshao** [comment]
@egadirov  add parameters to read() like these
```
    private $fields = array(
        LeadFields::AD_ID,
        LeadFields::ADSET_ID,
        LeadFields::FIELD_DATA,
        'ad_name',
        'adset_name',
        'campaign_name',
    );
    $form = new Lead($leadgen_id);
    $form_data = $form->read($this->fields)->getData();
```
