### ISSUE TITLE
 Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message '(#3) Application does not have the capability to make this API call.'

### ISSUE THREAD

**Issue by parveenpanwar** [facebook/facebook-php-ads-sdk#272]
Hello,

i am getting the fatal error  Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message '(#3) Application does not have the capability to make this API call.' while i am trying to get ads from my ads account with user token 

and 

i am getting the fatal error Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message 'Unsupported get request.'  while i am trying to get ads from my ads account with app token 

please can any one help me to fix this issue to get ads data from my account

**Comment by lintaocui** [comment]
@parveenpanwar Thank you for reporting the issue. Could you also provide us the code and also your ads account id and app id for with which you made the api call?

**Comment by parveenpanwar** [comment]
Hello @lintaocui 
Thank you for your reply , Now api is working fine realy do't know how but error message "Application does not have the capability to make this API call." has gone now. 

But now i am facing a new problem that is session expire of user access token after some duration . 
can you please help me out how i can resolve it bcoz i think access token should remain same for all the time for any app.

I think either i need to create and get access token manually every time i call api or anything else you can suggest.

**Comment by lintaocui** [comment]
@parveenpanwar the token is designed to expire. You have to renew it every once a while.

**Comment by dheerajagl** [comment]
Hello,

getting error

Fatal error: Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message '(#3) Application does not have the capability to make this API call.' in /var/www/html/fblead/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php:140 Stack trace: #0 /var/www/html/fblead/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Client.php(215): FacebookAds\Http\Exception\RequestException::create(Object(FacebookAds\Http\Response)) #1 /var/www/html/fblead/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Request.php(282): FacebookAds\Http\Client->sendRequest(Object(FacebookAds\Http\Request)) #2 /var/www/html/fblead/vendor/facebook/php-ads-sdk/src/FacebookAds/Api.php(151): FacebookAds\Http\Request->execute() #3 /var/www/html/fblead/vendor/facebook/php-ads-sdk/src/FacebookAds/Api.php(193): FacebookAds\Api->executeRequest(Object(FacebookAds\Http\Request)) #4 /var/www/html/fblead/vendor/facebook/php-ads-sdk/src/FacebookAds/Object/AbstractCrudObject.php(208): FacebookAds\Api->call('/act_3320919136. in /var/www/html/fblead/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php on line 140
