### ISSUE TITLE
SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by AloneCoder** [facebook/facebook-php-ads-sdk#274]
Hello!
Started to get such errors today while accessing different API endpioints  - is it a bug or certificates really need to be updated?

**Comment by AloneCoder** [comment]
Seems working now

**Comment by AloneCoder** [comment]
Currently experiencing the same problem

**Comment by pandasyr** [comment]
Hi @AloneCoder ,

Is this issue still happening and does it happen consistently or intermittently? I'm running in my own environment and it looks fine.

**Comment by AloneCoder** [comment]
I get such errors for each cronjob run on several application nodes every 15 minutes in average

**Comment by pandasyr** [comment]
I don't get the expiration message in my environment. I see the cert expires in 2018. Can you check what is the value on your servers?

`x509 -enddate -noout -in github/facebook-php-ads-sdk/fb_ca_chain_bundle.crt`
`notAfter=Aug 13 23:59:00 2018 GMT`

**Comment by JiamingFB** [comment]
Closing for now

If the issue persists and the aforementioned command shows that the cert is actually expired, feel free to reopen it and please provide more details.
