### ISSUE TITLE
Error message: Invalid parameter and Error Code: 100

### ISSUE THREAD

**Issue by sarathiscookie** [facebook/facebook-php-ads-sdk#275]
I am getting invalid parameter. Is there any issue in below code. Response I am getting is
"Using this account: act_1216109 Campaign ID:23842537285790170 AdSet ID: 23842537285830170 
Warning: finfo_file(D:\xampp\htdocs\facebook-php-ads-sdk\examples/../test/misc/1.jpg): failed to open stream: No such file or directory in D:\xampp\htdocs\facebook-php-ads-sdk\vendor\facebook\php-ads-sdk\src\FacebookAds\Object\AdImage.php on line 205
Error message: couldn't open file "D:\xampp\htdocs\facebook-php-ads-sdk\examples/../test/misc/1.jpg" 
Error Code: 26
Error message: Invalid parameter 
Error Code: 100"
Error message: Invalid parameter 
Error Code: 100"

Full code 

// Configurations
$access_token = 'token';
$app_id           = 'appid';
$app_secret     = 'secret';
// should begin with "act_" (eg: $account_id = 'act_1234567890';)
$account_id   = 'act_1216109';
define('SDK_DIR', __DIR__ . '/..'); // Path to the SDK directory
$loader       = include SDK_DIR.'/vendor/autoload.php';
date_default_timezone_set('America/Los_Angeles');
// Configurations - End
if(is_null($access_token) || is_null($app_id) || is_null($app_secret)) {
    throw new \Exception(
        'You must set your access token, app id and app secret before executing'
    );
}
if (is_null($account_id)) {
    throw new \Exception(
        'You must set your account id before executing');
}
use FacebookAds\Api;
Api::init($app_id, $app_secret, $access_token);
/**
 * Step 1 Read the AdAccount (optional)
 */
use FacebookAds\Object\AdAccount;
use FacebookAds\Object\Fields\AdAccountFields;
$account = (new AdAccount($account_id))->read(array(
    AdAccountFields::ID,
    AdAccountFields::NAME,
    AdAccountFields::ACCOUNT_STATUS,
));
echo "\nUsing this account: ";
echo $account->id."\n";
// Check the account is active
if($account->{AdAccountFields::ACCOUNT_STATUS} !== 1) {
    throw new \Exception(
        'This account is not active');
}
/**
 * Step 2 Create the Campaign
 */
use FacebookAds\Object\Campaign;
use FacebookAds\Object\Fields\CampaignFields;
//use FacebookAds\Object\Values\CampaignObjectiveValues;
try{
    $campaign  = new Campaign(null, $account->id);
    $campaign->setData(array(
        CampaignFields::NAME => 'My First Campaign',
        CampaignFields::OBJECTIVE => 'LINK_CLICKS',
        //CampaignFields::OBJECTIVE => CampaignObjectiveValues::LINK_CLICKS,
    ));
    $campaign->validate()->create(array(
        Campaign::STATUS_PARAM_NAME => Campaign::STATUS_PAUSED,
    ));
    echo "Campaign ID:" . $campaign->id . "\n";
}
catch (Exception $e) {
    echo 'Error message: ' .$e->getMessage() ."\n" . "<br/>";
    echo 'Error Code: ' .$e->getCode() ."<br/>";
}
/**
 * Step 3 Search Targeting
 */
use FacebookAds\Object\Targeting;
use FacebookAds\Object\Fields\TargetingFields;
$targeting = new Targeting();
$targeting->setData(array(
    TargetingFields::GEO_LOCATIONS => array(
        'countries' => array('JP'),
        'regions' => array(array('key' => '3886')),
        'cities' => array(
            array(
                'key' => '2420605',
                'radius' => 10,
                'distance_unit' => 'mile',
            ),
        ),
    ),
));
/**
 * Step 4 Create the AdSet
 */
use FacebookAds\Object\AdSet;
use FacebookAds\Object\Fields\AdSetFields;
use FacebookAds\Object\Values\AdSetBillingEventValues;
use FacebookAds\Object\Values\AdSetOptimizationGoalValues;
try{
    $adset = new AdSet(null, $account->id);
    $adset->setData(array(
        AdSetFields::NAME => 'My First AdSet',
        AdSetFields::CAMPAIGN_ID => $campaign->id,
        AdSetFields::DAILY_BUDGET => '500',
        AdSetFields::TARGETING => $targeting,
        AdSetFields::OPTIMIZATION_GOAL => AdSetOptimizationGoalValues::REACH,
        AdSetFields::BILLING_EVENT => AdSetBillingEventValues::IMPRESSIONS,
        AdSetFields::BID_AMOUNT => 100,
        AdSetFields::START_TIME =>
            (new \DateTime("+1 week"))->format(\DateTime::ISO8601),
        AdSetFields::END_TIME =>
            (new \DateTime("+2 week"))->format(\DateTime::ISO8601),
    ));
    $adset->validate()->create(array(
        //AdSet::STATUS_PARAM_NAME => AdSet::STATUS_ACTIVE,
        AdSet::STATUS_PARAM_NAME => AdSet::STATUS_PAUSED,
    ));
    echo 'AdSet  ID: '. $adset->id . "\n";
}
catch (Exception $e) {
    echo 'Error message: ' .$e->getMessage() ."\n" . "<br/>";
    echo 'Error Code: ' .$e->getCode() ."<br/>";
}
/**
 * Step 5 Create an AdImage
 */
use FacebookAds\Object\AdImage;
use FacebookAds\Object\Fields\AdImageFields;
try {
    $image = new AdImage(null, $account->id);
    $image->{AdImageFields::FILENAME}
        = SDK_DIR.'/test/misc/1.jpg';
    $image->create();
    echo 'Image Hash: '.$image->hash . "\n";
    //echo 'Image Hash: '.$image->{AdImageFields::HASH}.PHP_EOL;
}
catch (Exception $e) {
    echo 'Error message: ' .$e->getMessage() ."\n" . "<br/>";
    echo 'Error Code: ' .$e->getCode() ."<br/>";
}
/**
 * Step 6 Create an AdCreative
 */
use FacebookAds\Object\AdCreative;
use FacebookAds\Object\Fields\AdCreativeFields;
try{
    $creative = new AdCreative(null, $account->id);
    $creative->setData(array(
        AdCreativeFields::NAME => 'Sample Creative',
        AdCreativeFields::TITLE => 'Welcome to the Jungle',
        AdCreativeFields::BODY => 'We\'ve got fun \'n\' games',
        AdCreativeFields::IMAGE_HASH => $image->hash,
        AdCreativeFields::OBJECT_URL => 'http://www.example.com/',
    ));
    $creative->create();
    echo 'Creative ID: '.$creative->id . "\n";
}
catch (Exception $e) {
    echo 'Error message: ' .$e->getMessage() ."\n" . "<br/>";
    echo 'Error Code: ' .$e->getCode() ."<br/>";
}
/**
 * Step 7 Create an Ad
 */
use FacebookAds\Object\Ad;
use FacebookAds\Object\Fields\AdFields;
try {
    $ad = new Ad(null, $account->id);
    $ad->setData(array(
        AdFields::CREATIVE =>
            array('creative_id' => $creative->id),
        AdFields::NAME => 'My First Ad',
        AdFields::ADSET_ID => $adset->id,
    ));
    $ad->create();
    echo 'Ad ID:' . $ad->id . "\n";
}
catch (Exception $e) {
    echo 'Error message: ' .$e->getMessage() ."\n" . "<br/>";
    echo 'Error Code: ' .$e->getCode() ."<br/>";
}

**Comment by JiamingFB** [comment]
Hi @sarathiscookie ,

Are you running on a Windows machine? I see in the file path 
`Warning: finfo_file(D:\xampp\htdocs\facebook-php-ads-sdk\examples/../test/misc/1.jpg)`

Both slash (/) and backslash (\\) are used. You should probably only use one in your code. Can you fix your step 5 and retry?

**Comment by JiamingFB** [comment]
closing for now

The issue should be fixed after replacing the slashes (/). If that doesn't resolve the issue, feel free to reopon the issue and we'll further investigate.
