### ISSUE TITLE
How to get ad-action-stats for campaign from insights api?

### ISSUE THREAD

**Issue by litan1106** [facebook/facebook-php-ads-sdk#278]
How to get ad-action-stats for campaign from insights api? Thanks

Here is my example code:

            $campaign = new Campaign($campaignId);

            $fields = [
                AdsInsightsFields::CAMPAIGN_ID,
                AdsInsightsFields::CAMPAIGN_NAME,
                AdsInsightsFields::REACH,
                AdsInsightsFields::IMPRESSIONS,
                AdsInsightsFields::CLICKS,
                AdsInsightsFields::SPEND,
                AdsInsightsFields::CPM,
                AdsInsightsFields::CPC,
                AdsInsightsFields::ACTIONS, 
               // How to get action such as offsite_conversion.fb_pixel_purchase: Purchases
            ];
            $params = [
                'time_range' => [ 'since' => $startDate, 'until' => $endDate ],
            ];

            $response = $campaign->getInsights($fields, $params)->getLastResponse();

https://developers.facebook.com/docs/marketing-api/insights/fields/v2.8

actions: list<AdsActionStats>
The total number of actions people took that are attributed to your ads. Actions may include engagement, clicks or conversions.

**Comment by liangjiali** [comment]
Hi,can you tell me how to solve  this problem?Thinks.

**Comment by litan1106** [comment]
I just used the php graph sdk instead of the ad sdk.

**Comment by liangjiali** [comment]
font{
        line-height: 1.7;
    }


    
How to use the php graph sdk? Thank you for your reply.



    On 8/25/2017 07:53，Li Tan<notifications@github.com> wrote： 


I just used the php graph sdk instead of the ad sdk.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  






        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
