### ISSUE TITLE
Get Campaigns - Batch Request Support

### ISSUE THREAD

**Issue by litan1106** [facebook/facebook-php-ads-sdk#280]
Is the batch available for get campaigns in the php-ads-sdk?

#Batch
https://developers.facebook.com/docs/marketing-api/asyncrequests/v2.8#adinsights

**Comment by daphyFB** [comment]
Thanks for reporting Ads API SDK issues!

We currently don't support batch in php (only in Python and Java now).

You could can kind of set the array of api calls and still use the php SDK Api Object, like here:
https://github.com/facebook/facebook-php-ads-sdk/blob/master/src/FacebookAds/Object/AbstractCrudObject.php#L401

Is batch-requests an important features for you?

**Comment by litan1106** [comment]
yes, because we need to fetch a lot of campaign insights for our dashboard.

**Comment by daphyFB** [comment]
Hi, thank you for you feedback. We'll add this feature quest to our queue. In the mean time, please consider using other languages, or from the sample I pasted above. Sorry for the inconvenience.

**Comment by litan1106** [comment]
Thanks for the help.
