### ISSUE TITLE
How can i bind  account at the SDK

### ISSUE THREAD

**Issue by guoweibo** [facebook/facebook-php-ads-sdk#289]
I hava  app_id ,app_secret and $access_token, I didn't find facebook account  with my app binding examples

**Comment by cloudxu** [comment]
@guoweibo, Sorry, I don't quite understand you question

**Comment by cloudxu** [comment]
@guoweibo, Please try our Getting Started example wizard to get a working code.
https://developers.facebook.com/docs/marketing-api/insights-api/getting-started/v2.10
