### ISSUE TITLE
GetAdset Exception for  nonexisting field

### ISSUE THREAD

**Issue by agarwalsudeep** [facebook/facebook-php-ads-sdk#294]
API call to get Adsets of an account raises exception. Adding Request details and exception.
Please help!!

curl -G \
  -d 'fields=account_id,adlabels,adset_schedule,attribution_window_days,bid_amount,bid_info,billing_event,budget_remaining,campaign,campaign_id,configured_status,created_time,creative_sequence,daily_budget,effective_status,end_time,frequency_cap,frequency_cap_reset_period,frequency_control_specs,id,is_autobid,is_average_price_pacing,lifetime_budget,lifetime_frequency_cap,lifetime_imps,name,optimization_goal,pacing_type,promoted_object,recurring_budget_semantics,rf_prediction_id,rtb_flag,start_time,status,targeting,time_based_ad_rotation_id_blocks,time_based_ad_rotation_intervals,updated_time,use_new_app_click,daily_imps,execution_options,redownload' \
  -d 'access_token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' \
  -d 'appsecret_proof=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' \
  https://graph.facebook.com/v2.8/act_10929295/adsets

FacebookAds\Exception\Exception
=============================================== 
'(#100) Tried accessing nonexisting field (daily_imps) on node type (AdCampaign)'

**Comment by daphyFB** [comment]
Thanks for reporting Ads API SDK bugs.

Please change the daily_imps to daily_imp and you should be able to get the result; please re-open this issue if this doesn't help.

On a side note, this is an API issue, not SDK issue; if you could visit 
https://developers.facebook.com/docs/marketing-api/using-the-api
it'll be wonderful! Thanks again!
