### ISSUE TITLE
Facebook php ads sdk

### ISSUE THREAD

**Issue by RamaAnumalla** [facebook/facebook-php-ads-sdk#295]
Getting error when use custom_audience.php page::

Fatal error: Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message '(#3) Application does not have the capability to make this API call.' in /var/www/html/Facebookads/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php:163 Stack trace: #0 /var/www/html/Facebookads/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Client.php(217): FacebookAds\Http\Exception\RequestException::create(Array, 400) #1 /var/www/html/Facebookads/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Request.php(282): FacebookAds\Http\Client->sendRequest(Object(FacebookAds\Http\Request)) #2 /var/www/html/Facebookads/vendor/facebook/php-ads-sdk/src/FacebookAds/Api.php(152): FacebookAds\Http\Request->execute() #3 /var/www/html/Facebookads/vendor/facebook/php-ads-sdk/src/FacebookAds/Api.php(194): FacebookAds\Api->executeRequest(Object(FacebookAds\Http\Request)) #4 /var/www/html/Facebookads/vendor/facebook/php-ads-sdk/src/FacebookAds/Object/AbstractCrudObject.php(236): FacebookAds\Api->call('/act_1015 in /var/www/html/Facebookads/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php on line 163

**Comment by daphyFB** [comment]
Hi @RamaAnumalla ,

Thanks for reporting Ads API SDK bugs.

This error message looks like a permission issue; could you double check if you can achieve the same thing via Ads Manager/ Power Editor on Facebook? If not, please check your account ability and capabilities.

Please let us know if you can perform the same thing via Facebook UI, but not with SDK, and I'll be happy to look further into it.

Thanks!

**Comment by JiamingFB** [comment]
This is permission related issue. You can try the same API call in Graph Explorer (https://developers.facebook.com/tools/explorer)

If you believe that the error is caused by SDK, feel free to reopen the issue.

Thanks!
