### ISSUE TITLE
[Feature Request] "Copies" field and related functions

### ISSUE THREAD

**Issue by ultraN** [facebook/facebook-php-ads-sdk#296]
According to https://developers.facebook.com/docs/marketing-api/reference/ad-campaign
Now we are capable to create a duplicate of an AdSet just through **POST** _/adset-id/copies_ endpoint.
However, there's no sign of this feature in SDK. Can you guys please add this? because this is super useful.

**Comment by daphyFB** [comment]
Thanks for reporting Ads API SDK issues.  We're indeed working on adset copies. Please stay tuned!
