### ISSUE TITLE
BC breaking changes between 2.8.1 and 2.8.2

### ISSUE THREAD

**Issue by mzstic** [facebook/facebook-php-ads-sdk#298]
Hi, facebook-ads-api started to throw errors that function doesn't exist. Specifically this
`Attempted to call an undefined method named "getResult" of class "FacebookAds\Object\AdReportRun".`

Mentioned function disappeared in this commit:
https://github.com/facebook/facebook-php-ads-sdk/commit/d51193b19d730ae9274d45540986e1ac311b074d#diff-3b22cc30bb634c0a86e53391924fb0d6L120

First It's not clear to me what function to use, second and more important - this kind of changes shouldn't appear only in this kind of version change. Correct me if I'm wrong.

**Comment by daphyFB** [comment]
Thanks for reporting Ads API SDK bugs. You're right; the error message doesn't make sense here. I'm looking into this. Thanks!

**Comment by JiamingFB** [comment]
Hi, you can use 'getInsights()' instead. Thanks!
