### ISSUE TITLE
CustomAudiences wrong in documentation and examples

### ISSUE THREAD

**Issue by swordbeta** [facebook/facebook-php-ads-sdk#300]
Marketing API documentation says:

```php
use FacebookAds\Object\CustomAudience;
use FacebookAds\Object\Values\CustomAudienceTypes;

$emails = array(
  'test1@example.com',
  'test2@example.com',
  'test3@example.com',
);

$audience = new CustomAudience(<CUSTOM_AUDIENCE_ID>);

$audience->createUser($emails, CustomAudienceTypes::EMAIL);
```

Outputs:

```
Type error: Argument 2 passed to FacebookAds\Object\CustomAudience::createUser() must be of the type array, string given
```

All functions are wrongly documentated, not only `createUser`. The documentation is only correct for `CustomAudienceMultiKey`.
Source: https://developers.facebook.com/docs/marketing-api/audiences-api

How it actually works:

```php
$emails = array(
  'test1@example.com',
  'test2@example.com',
  'test3@example.com',
);
$customAudience->createUser([], [
  'payload' => [
    'schema' => CustomAudienceTypes::EMAIL,
    'data' => array_map(function($email) {
      return hash(HashNormalizer::HASH_TYPE_SHA256, $email);
    }, $emails),
  ]
])
```

This example is also wrong: https://github.com/facebook/facebook-php-ads-sdk/blob/master/examples/custom_audiences.php

Custom Audiences is correctly documented here: https://developers.facebook.com/docs/marketing-api/reference/custom-audience/users/

**Comment by swordbeta** [comment]
@duliomatos Seems to be removed in this commit: https://github.com/facebook/facebook-php-ads-sdk/commit/837ea5db3f01a701260adf97b9018478c90b60e5 Was this intended?

**Comment by kvnvandenbrande** [comment]
I stumble upon this problem as well. I wasted a few hours trying to make it work. All documentation beside a few calls work correctly. 

Almost every call documented here ( https://developers.facebook.com/docs/marketing-api/audiences-api ) gives you an error. Quit annoying when you start developing.

@swordbeta 
Custom Audiences is correctly documented here: https://developers.facebook.com/docs/marketing-api/reference/custom-audience/users/
You could be right, but this page at the start of the development process is hard..

Will someone update these examples someday or?

**Comment by swordbeta** [comment]
@kvnvandenbrande Looks like they will, posted it yesterday on the facebook bug tracker: https://developers.facebook.com/bugs/158663737997848/

**Comment by kvnvandenbrande** [comment]
@swordbeta nice to hear. Looking forward to it. The example you wrote is quit different from the syntax they documented.

**Comment by swordbeta** [comment]
@kvnvandenbrande I actually didn't end up using the code I wrote but I'm always using `CustomAudienceMultiKey`. It's almost the same except that you have to define what the schema looks like.

**Comment by kvnvandenbrande** [comment]
@swordbeta Well after quit some trying and debugging and having no clue, I got the CustomAudienceMultiKey working and that's where I am building on at the moment as well.

**Comment by nikksan** [comment]
I wasted a few hours myself, but eventually got it to work..
I couldnt figure out a way to get audience_id, so I created a method inside FacebookAds\Object\CustomAudience.php
` public function getAudienceId(){
    return $this->data['id'];
  }`
This is the algortythm for creating audience and adding users to it.
1.Create CustomAudience
`$audience = new CustomAudience(null, 'act_' . $account_id);
	$audience->setData(array(
	  CustomAudienceFields::NAME => 'My new CA',
	  CustomAudienceFields::SUBTYPE => CustomAudienceSubtypes::CUSTOM,
	  CustomAudienceFields::DESCRIPTION => 'People who bought from my website',
	));

	$audience->create();`
2.Create CustomAudienceMultiKey using the id from CustomAudience
`$audience = new CustomAudienceMultiKey( $audience->getAudienceId() );
	$users = array(
	  array('fname', 'lname'  , 'someone@example.com'),
	  array('fname', 'lname'  , 'someone_new@example.com'),
	);
	$schema = array(
	  CustomAudienceMultikeySchemaFields::FIRST_NAME,
	  CustomAudienceMultikeySchemaFields::LAST_NAME,
	  CustomAudienceMultikeySchemaFields::EMAIL,
	);
    $audience->addUsers($users, $schema);`

**Comment by daphyFB** [comment]
Thanks for reporting Ads API SDK issues. We are working on documentations. I'll pass this information along. Thanks a lot!

**Comment by xiaotchen** [comment]
Hey guys, I made a new release just now and this should be fixed. Now you could just call:

```
use FacebookAds\Object\CustomAudience;
use FacebookAds\Object\Values\CustomAudienceTypes;

$emails = array(
  'test1@example.com',
  'test2@example.com',
  'test3@example.com',
);

$audience = new CustomAudience(<CUSTOM_AUDIENCE_ID>);

$audience->addUsers($emails, CustomAudienceTypes::EMAIL);
```

I also fixed the documentation but the fix will be available a bit later on the website. Thanks!

**Comment by kvnvandenbrande** [comment]
Top, thx!
