### ISSUE TITLE
Add notice of InsightsLevels being removed in 2.8.2 release notes

### ISSUE THREAD

**Issue by benjaminluck** [facebook/facebook-php-ads-sdk#301]
The class FacebookAds\Object\Values\InsightsLevels has been deprecated since (IIRC) 2.7.1 and seems to have been removed (intentionally I suppose) in the the most recent tag 2.8.2. I'm not sure if there's some kind of unwritten rule about not mentioning the actual removal of deprecated logic, but I suppose it wouldn't hurt to briefly mention it somewhere.

**Comment by daphyFB** [comment]
Hi, thanks for reporting Ads API SDK issues.
SDK basically follows the Ads API (marketing API) deprecation policies:
https://developers.facebook.com/docs/marketing-api/versions

Please feel free to reopen the task if there are further questions. Thanks!
