### ISSUE TITLE
Campaign and AdSet empty when querying AdAccount insights 

### ISSUE THREAD

**Issue by gugaiz** [facebook/facebook-php-ads-sdk#305]
Hi, I am trying to query adAccount's insights at adset level.. here is the code

      $ad_account = new AdAccount($row['ad_account_fb_id']);
    
      //Setting fields
      $fields = array(
        AdsInsightsFields::SPEND,
        AdsInsightsFields::IMPRESSIONS,
        AdsInsightsFields::CLICKS,
        AdsInsightsFields::REACH,
        AdsInsightsFields::SOCIAL_CLICKS,
        AdsInsightsFields::VIDEO_P100_WATCHED_ACTIONS,
        AdsInsightsFields::VIDEO_AVG_PERCENT_WATCHED_ACTIONS,
        AdsInsightsFields::VIDEO_10_SEC_WATCHED_ACTIONS,
        AdsInsightsFields::CAMPAIGN_ID,
        AdsInsightsFields::CAMPAIGN_NAME,
        AdsInsightsFields::ADSET_ID,
        AdsInsightsFields::ADSET_NAME,
        AdsInsightsFields::DATE_START
      );   
      $params = array(
        'time_range' => array(
          'since' => '2017-01-01',
          'until' => '2017-02-01
        ),   
        'time_increment' => 1,
        'limit' => 9999999,
        'sort' => 'date_start',
        'breakdowns' => AdsInsightsBreakdownsValues::IMPRESSION_DEVICE
      );   

      //Getting insights
      try{ 
        $insights = $ad_account->getInsights($fields, $params);
        $insights->setUseImplicitFetch(true);
      }
      catch (Exception $e) {
        out('Error message: ' .$e->getMessage() .PHP_EOL,'error');
        out('Error Code: ' .$e->getCode().PHP_EOL,'error');
      }
      foreach ($insights as $insight) {
         echo $insight->{AdsInsightsFields::CAMPAIGN_NAME} //it is allways null!!!
         echo $insight->{AdsInsightsFields::CAMPAIGN_ID} //it is allways null!!!
         echo $insight->{AdsInsightsFields::ADSET_NAME} //it is allways null!!!
         echo $insight->{AdsInsightsFields::ADSET_ID} //it is allways null!!!
      }
As you can see I am always getting empty values for campaign and adset fields, all the other fields work correctly. If I try the same on the Graph API Explorer, it works fine.

**Comment by JiamingFB** [comment]
Hi @gugaiz 

Did you set the 'level' param? I don't see that in your code...

You may check this page https://developers.facebook.com/docs/marketing-api/reference/ad-account/insights/

**Comment by gugaiz** [comment]
Sorry, you right, I was missing the level param, and it was present on the graph api that is way it worked there. 
Thanks!
