### ISSUE TITLE
$parent_id required AND deprecated?

### ISSUE THREAD

**Issue by a-kinder** [facebook/facebook-php-ads-sdk#314]
When passing in a $parent_id to a new object that inherits from AbstractCrudObject, an error message displays: `$parent_id as a parameter of constructor is being deprecated, please try not to use this in new code.` yet when $parent_id is null, it throws an Exception:  `A parent ID is required.`

**Comment by Vijaysinh** [comment]
any updates on this thread?

**Comment by guxufb** [comment]
We are depreciating creation with parent_id.  We are seeing multiple endpoints that can create the same type of object.  We do not have good ways to decide which one we should use if you are creating new object with parent_id.  Moving forward, please instantiate the parent object with the parent_id and call create_XXX function to create the object you want.

**Comment by stacybot123** [comment]
@guxufb  Do you have an example for this? The developer tutorial still shows the same steps.

**Comment by broncha** [comment]
What I have come to understand is, don't use the instantiation as described in the docs.

```
$campaign = new Campaign(null, "act_XXXXXX");
```
Instead just do


```
$campaign = new Campaign();
```

**Comment by elegos** [comment]
According to [the SDK docs](https://developers.facebook.com/docs/marketing-api/reference/custom-audience/#Creating) I should call `new CustomAudience(null, 'act_AD_ACCOUNT_ID')`, but going down the code to `AbstractCrutObject.php` the second parameter is the deprecated `parent_id` argument. How should I reference the given ad account id?

Thanks

**Comment by dva00jnd** [comment]
That gives me:
Error message: A parent ID is required.

(Using the sandbox account)

**Comment by ebisbe** [comment]
Still an issue...

**Comment by rauaha** [comment]
I am trying to create lookalike audience and getting this error message. I am using facebook_business and how can I solve this in python?

**Comment by juanluseres** [comment]
same problem after this

`$user = new AdAccountUser();
        $user->setId($id);

        $accounts = $user->getAdAccounts(array(
          AdAccountFields::ID,
          AdAccountFields::NAME,
        ));`

**Comment by mrstask** [comment]
> I am trying to create lookalike audience and getting this error message. I am using facebook_business and how can I solve this in python?

same problem in python, and no answer
