### ISSUE TITLE
AdSetOptimizationGoalValues::LEAD_GENERATION Doesn't work

### ISSUE THREAD

**Issue by asendari** [facebook/facebook-php-ads-sdk#324]
Hi,

When I tried to create an adset with Optimization Goal setted to : AdSetOptimizationGoalValues::LEAD_GENERATION the API return an "Invalid parameter" error.

But if I use AdSetOptimizationGoalValues::REACH it's work fine.

Here a example code:
```
$adset->setData(array(
  AdSetFields::NAME => "test",
  AdSetFields::CAMPAIGN_ID => $campaignId,
  AdSetFields::DAILY_BUDGET => '150',
  AdSetFields::TARGETING => $targeting,
  AdSetFields::OPTIMIZATION_GOAL =>AdSetOptimizationGoalValues::LEAD_GENERATION,
  AdSetFields::BILLING_EVENT => AdSetBillingEventValues::IMPRESSIONS,
  AdSetFields::IS_AUTOBID => true
));
```

I don't know why, I tried differents combinaisons with anothers params to identify if you need another params but not concluent...

Thank you

**Comment by guxufb** [comment]
We need more details to repo the issue.  Are you using the LEAD_GENERATION objective @ campaign level?

**Comment by asendari** [comment]
I use "CampaignObjectiveValues::CONVERSIONS".

**Comment by Harikumar90** [comment]
Hi,
If you want to create a LEAD_GENERATION type AdSet, you need to add "PROMOTED_OBJECT" AdSetFileds additionally.

Refer the below code

$adset->setData(array(
        AdSetFields::NAME => 'Lead campaign adset',
        AdSetFields::CAMPAIGN_ID => '6071267689258',
        AdSetFields::DAILY_BUDGET => 4000,
        AdSetFields::TARGETING => $targeting,
        AdSetFields::OPTIMIZATION_GOAL => AdSetOptimizationGoalValues::LEAD_GENERATION,
        AdSetFields::BILLING_EVENT => AdSetBillingEventValues::IMPRESSIONS,
        AdSetFields::BID_AMOUNT => 1000,
        AdSetFields::START_TIME =>
            (new \DateTime("+1 week"))->format(\DateTime::ISO8601),
        AdSetFields::END_TIME =>
            (new \DateTime("+2 week"))->format(\DateTime::ISO8601),
        AdSetFields::PROMOTED_OBJECT => array(
            'page_id' => '1440015652687985',
        ),    
    ));
    $adset->create();

**Comment by asendari** [comment]
OK thank you.

But the message "Invalid parameter" is not very clear :-p

Thank you
