### ISSUE TITLE
How can I override the default CURLOPT_CONNECTTIMEOUT?

### ISSUE THREAD

**Issue by ryancwalsh** [facebook/facebook-php-ads-sdk#328]
I have a cron job that pulls data from Facebook many times per day.

A substantial percentage of those requests throughout the day results in an error like this one:

    FacebookAds\Exception\Exception: Connection timed out after 10001 milliseconds in /vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Adapter/CurlAdapter.php:196
    Stack trace:
    #0 /vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Client.php(204): FacebookAds\Http\Adapter\CurlAdapter->sendRequest(Object(FacebookAds\Http\Request))
    #1 /vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Request.php(282): FacebookAds\Http\Client->sendRequest(Object(FacebookAds\Http\Request))
    #2 /vendor/facebook/php-ads-sdk/src/FacebookAds/Api.php(151): FacebookAds\Http\Request->execute()
    #3 /vendor/facebook/php-ads-sdk/src/FacebookAds/Api.php(193): FacebookAds\Api->executeRequest(Object(FacebookAds\Http\Request))
    #4 /vendor/facebook/php-ads-sdk/src/FacebookAds/ApiRequest.php(183): FacebookAds\Api->call('/act_1010015700...', 'GET', Array, Array)
    #5 /app/Helpers/FacebookHelper.php(173): FacebookAds\ApiRequest->execute()
    #6 /app/Helpers/FacebookHelper.php(271): App\Helpers\FacebookHelper->getInsights('AdAccount', 'act_10100157003...', 'ad', '2017-06-23', '2017-06-23', Array)
    #7 /app/Helpers/FacebookHelper.php(360): App\Helpers\FacebookHelper->getReport('AdAccount', 'act_10100157003...', 'ad', '2017-06-23', '2017-06-23', Array)
    #8 /app/Console/Commands/CheckWhetherFacebookAdsStartedRunning.php(50): App\Helpers\FacebookHelper->getDashAds('2017-06-23', '2017-06-23')
    #9 [internal function]: App\Console\Commands\CheckWhetherFacebookAdsStartedRunning->handle()
    #10 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
    #11 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
    #12 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
    #13 /vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
    #14 /vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
    #15 /vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
    #16 /vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
    #17 /vendor/symfony/console/Application.php(869): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #18 /vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\CheckWhetherFacebookAdsStartedRunning), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #19 /vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #20 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #21 /artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #22 {main}
    Level
    ----------------
    ERROR

I see [here in the Facebook API][1] that `CURLOPT_CONNECTTIMEOUT` is set to 10 seconds.

I'd like to try adjusting the timeout to 20 seconds.

I've been unable to figure out how to change that value without editing the source code in that library (which I definitely don't want to do because then it will be overwritten on the next upgrade).

I'm calling `$ad->getInsights($fields, $params, true);` ([code][2]) and then executing that request.

**How can I override the Curl options that Facebook uses as a default?**

  [1]: https://github.com/facebook/facebook-php-ads-sdk/blob/2.8.2/src/FacebookAds/Http/Adapter/CurlAdapter.php#L71
  [2]: https://github.com/facebook/facebook-php-ads-sdk/blob/2.8.2/src/FacebookAds/Object/Ad.php#L168

**Comment by guxufb** [comment]
The easiest way is to make some local change on the SDK code. https://github.com/facebook/facebook-php-ads-sdk/blob/53bee21251a9d898591708b96d1afa9e13516e3d/src/FacebookAds/Http/Adapter/CurlAdapter.php#L71

If you want to avoid local changes, you should be able to do that with the following code.
```
$curl = Api::instance()->getHttpClient()->getAdapter();
$curl->setOpts(new \ArrayObject(array(
  CURLOPT_CONNECTTIMEOUT => 20,
  CURLOPT_TIMEOUT => 60,
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_HEADER => true,
  CURLOPT_CAINFO => $curl->getCaBundlePath(),
)));```

**Comment by ryancwalsh** [comment]
This problem hasn't happened in a while, but **I appreciate your answer** and have jotted down your suggestion for later in case it happens again. Thanks!
