### ISSUE TITLE
 User is not admin on ad account

### ISSUE THREAD

**Issue by saidrajafallah** [facebook/facebook-php-ads-sdk#329]
Fatal error: Uncaught FacebookAds\Http\Exception\AuthorizationException: (#273) This Ads API call requires the user to be admin of the ad account. User is not admin on ad account

**Comment by daphyFB** [comment]
Thanks for reporting Ads API SDK issues.

Like the error message said, please make sure that the user id is an admin of the ads account you access, and had probably logged in.

If you believe this is an error, please feel free to re-open the task and kindly provide us more information like the user id and ad account id, and the fb trace id when the api call fails.
