### ISSUE TITLE
semver

### ISSUE THREAD

**Issue by marekpetras** [facebook/facebook-php-ads-sdk#331]
Hey, 

how about not introducing breaking changes between minor versions?

2.7 -> 2.9 = broken

http://semver.org/

Thanks
Cheers

**Comment by daphyFB** [comment]
Thanks for reporting Ads API SDK issues.
SDK versioning follows Facebook marketing api versions:
https://developers.facebook.com/docs/marketing-apis

We're also working on a better communication channel and a better breaking change detector.

Thanks for your feedback!
