### ISSUE TITLE
Can't create Adset

### ISSUE THREAD

**Issue by nkmswot** [facebook/facebook-php-ads-sdk#338]
I'm using ads api 2.9
Campaign is successfully created. But adset can't be created still.

My Code:
-------------------------------------
$set = new AdSet(null, $account_id);
$set->setData(array(
  AdSetFields::NAME => 'My Test AdSet',
  AdSetFields::OPTIMIZATION_GOAL => AdSetOptimizationGoalValues::REACH,
  AdSetFields::BILLING_EVENT => BillingEvents::IMPRESSIONS,
  AdSetFields::CAMPAIGN_ID => $campaign_id,
  AdSetFields::DAILY_BUDGET => 10,
  AdSetFields::TARGETING => (new Targeting())->setData(array(
    TargetingFields::GEO_LOCATIONS => array(
      'countries' => array(
        'US',
      ),
    ),
  )), 
));
$set->create(array(
  AdSet::STATUS_PARAM_NAME => AdSet::STATUS_PAUSED,
));

**the code returns :**
----------------------
Error message: Invalid parameter
Error Code: 100

What can i do?

**Comment by bartclaeys** [comment]
Use this for better debug info:

+    echo 'Error User Title for new AdSet(): ' .$e->getErrorUserTitle() ."<br/>";
+    echo 'Error User Message for new AdSet(): ' .$e->getErrorUserMessage() ."<br/>";

**Comment by nkmswot** [comment]
Now the error comes:
Error User Title for new AdSet(): Budget Is Too Low
Error User Message for new AdSet(): The budget for this ad set must be at least â‚¹40.00. Please edit your budget in your ad set to enable delivery of your ads.

After i have set my budget is 40
+ AdSetFields::DAILY_BUDGET => 40,

now too the same error coming...?!

**Comment by guxufb** [comment]
I would assume that your ad account is in USD.  The unit should be cent.  Thus it should be 4000 rather than 40.  More information about minumal budget:
https://developers.facebook.com/docs/marketing-api/reference/minimum-budget/

**Comment by behnamizadii** [comment]
@guxufb you are a savior.
