### ISSUE TITLE
What to download when "build failing"?

### ISSUE THREAD

**Issue by ryancwalsh** [facebook/facebook-php-ads-sdk#340]
I see v2.10.1 "build failing" at 2017-07-22 07:51:27 ET at https://github.com/facebook/facebook-php-ads-sdk right now.

**When this page shows "build failing", does that mean I should NOT download the latest release (e.g. https://github.com/facebook/facebook-php-ads-sdk/tree/2.10.1)?**

My composer currently says `"facebook/php-ads-sdk": "2.9.*"` but I was thinking of upgrading to the latest.

**Comment by guxufb** [comment]
Is this issue still there?

**Comment by ryancwalsh** [comment]
@guxufb For some reason, I did not receive a Github notification when you asked "Is this issue still there?" 14 days ago.

Yes, I see v2.10.1 "build failing" at 2017-08-08 12:35 ET at https://github.com/facebook/facebook-php-ads-sdk right now.

Can you please answer:

**When this page shows "build failing", does that mean I should NOT download the latest release (e.g. https://github.com/facebook/facebook-php-ads-sdk/tree/2.10.1)?**
