### ISSUE TITLE
TargetingSearchTypes ??

### ISSUE THREAD

**Issue by saidrajafallah** [facebook/facebook-php-ads-sdk#341]
i'm using 👍 
use FacebookAds\Object\TargetingSearch;
use FacebookAds\Object\Search\TargetingSearchTypes;

$result = TargetingSearch::search(
  TargetingSearchTypes::TARGETING_CATEGORY,
  'interests');

get all interests only anglais ,can not pass parm lang (fr or nl)

i want get interests (FR or NL)

**Comment by guxufb** [comment]
It looks more like an issue related to API usage.  It would be better to post in this public group. https://www.facebook.com/groups/pmdcommunity.
