### ISSUE TITLE
Targeting Based on City Error 

### ISSUE THREAD

**Issue by stacybot123** [facebook/facebook-php-ads-sdk#345]
I am trying to add City to Add Target based on the City Input by the user . For example I need to target all peoples in Fort Lauderdale , Florida. But I am getting error as

"Invalid data for field geo_locations. Invalid Targeting Spec: The specified targeting spec is not valid because: Normalization does not allow the value city"

Here is the Code I am using to create AdSet

  $adset = new AdSet(null, $account->id);
  $adset->setData(array(
    AdSetFields::NAME => 'Seller Ads ' . $city,
    AdSetFields::IS_AUTOBID  => true,
    AdSetFields::BILLING_EVENT => BillingEvents::IMPRESSIONS,
    AdSetFields::OPTIMIZATION_GOAL => OptimizationGoals::LEAD_GENERATION,
    AdSetFields::DAILY_BUDGET => $budget,
    AdSetFields::CAMPAIGN_ID => $campaign_id,
    AdSetFields::PROMOTED_OBJECT => array('page_id' => $page_id),
  AdSetFields::TARGETING => (new Targeting())->setData(array(
    TargetingFields::GEO_LOCATIONS => array(
         
        'city' => array(
        'Fort Lauderdale',
      ),
       ),

    TargetingFields::AGE_MIN => 27,
    TargetingFields::AGE_MAX => 65,
        TargetingFields::FLEXIBLE_SPEC => array(
      array(
	TargetingFields::BEHAVIORS => array(
          array(
            'id' => 6009218310699,
            'name' => 'Likely to move',
          ),
        ),
	TargetingFields::HOME_OWNERSHIP => array(
          array(
            'id' => 6009989303132,
            'name' => 'Homeowners',
          ),
        ),
      ),
    ),      
	  
      TargetingFields::EXCLUSIONS => array(
	  
	  TargetingFields::HOME_TYPE => $tgt,

    ),
  )),

  ));    
    
    
$adset->create();
$ad_set = $adset->id;

**Comment by cloudxu** [comment]
Please look at

https://developers.facebook.com/docs/marketing-api/targeting-search/v2.10

Try to see if 'cities' is right parameter. And may be you need TargetingSearch::search

**Comment by cloudxu** [comment]
Also, we encourage you to ask this type of question in the FB group:
https://www.facebook.com/groups/pmdcommunity/
