### ISSUE TITLE
Empty data response while fetching home listings from catalog listing set

### ISSUE THREAD

**Issue by niravpatel2008** [facebook/facebook-php-ads-sdk#349]
I have listing in listing set ("1914108028614481") but when i am trying to fetch using api it returns blank response. is there other function to fetch realestate listings ?

```
$productSet = new ProductSet("1914108028614481", null, $api);;
$pres = $productSet->getProducts();

// response:
{"data":[]}
```

**Comment by cloudxu** [comment]
Hi, you may look at the test code:
https://github.com/facebook/facebook-php-ads-sdk/blob/53bee21251a9d898591708b96d1afa9e13516e3d/test/FacebookAdsTest/Object/ProductSetTest.php

for example. Thanks.

**Comment by niravpatel2008** [comment]
@cloudxu Thanks for the reply 
I have created catalog of real estate listings and product set from that that catalog now i am able to get set name filter and count of listing from created set but not the list of listings.

`$productSet = new ProductSet("1914108028614481", null, $api);;
$pres = $productSet->getProducts();

// response:
{"data":[]}`

i have checked test code ref link provided by you but it does not help me to get listings can you please check guide me is there any diffrent method or function to get real estate listing ?
