### ISSUE TITLE
LeadgenForm GetLeads($filter), error

### ISSUE THREAD

**Issue by dev-skinna** [facebook/facebook-php-ads-sdk#351]
Hi guys, I need help I'm trying to filter the leads by date range, but I do not get it.

Does anyone have an example?

```
$filter => how pass an filter range date.


$form = new LeadgenForm($form_id);
$leads = $form->getLeads($filter);
```

**Comment by guxufb** [comment]
Please reference https://developers.intern.facebook.com/docs/marketing-api/guides/lead-ads/retrieving#bulk-read.
