### ISSUE TITLE
Default Graph Version format is same with graph-sdk

### ISSUE THREAD

**Issue by oanhnn** [facebook/facebook-php-ads-sdk#353]
I using both `graph-sdk` and `php-ads-sdk` with same config.
But i get error `Unknown path components: /me/adaccounts`.
Reason of error is:
- `graph-sdk` using default graph version format `v2.10`
- `php-ads-sdk` using default graph version format `2.10`

I think it is uncomfortable for developer. Better, it should are same.

**Comment by guxufb** [comment]
It does make sense and we should change it.  Since it is a breaking change on SDK, we need to have a better plan.
