### ISSUE TITLE
Unsupported get request

### ISSUE THREAD

**Issue by ivarsmas** [facebook/facebook-php-ads-sdk#354]
Hi, When trying to use the Facebook Marketing API I'm getting always the error: 
**"Unsupported get request"**

I have last version of API v2.10 installed with composer in CodeIgniter, a test app in the same version, a extended new long-lived access token that will never expire, and I use 'act_' before account_id number, but it is not working. 

This is my code (extracted from sample code I get of https://developers.facebook.com/apps/<MY_APP_ID>/marketing-api/):

```
$api = Api::init($app_id, $app_secret, $access_token);
$api->setLogger(new CurlLogger());

$fields = array(
	'account_id',
	'campaign_group_id',
	'campaign_group_name',
	'reach',
	'cost_per_result',
	'spend',
	'impressions',
	'total_actions',
	'clicks',
	'results',
	'actions:like',
	'actions:post_engagement',
);
$params = array(
	'time_range' => array('since' => '2017-08-09','until' => '2017-08-16'),
	'filtering' => array(),
	'level' => 'campaign',
	'breakdowns' => array('days_1'),
);
echo json_encode((new AdAccount($account_id))->getInsights(
	$fields,
	$params
)->getResponse()->getContent(), JSON_PRETTY_PRINT);
```

**Comment by guxufb** [comment]
did you add the "act_" prefix in your $adaccount_id?

**Comment by ivarsmas** [comment]
Yes @guxufb, I have added the "act_" prefix.

**Comment by guxufb** [comment]
I cannot repo your issue with my own information.  Maybe you need to use Facebook bug report tool so that you can share more details on this request.
