### ISSUE TITLE
Unsupported get request. Please read the Graph API documentation

### ISSUE THREAD

**Issue by cornernote** [facebook/facebook-php-ads-sdk#36]
Here is my example code:

``` php
\FacebookAds\Api::init($app_id, $app_secret, $access_token);
$account = (new \FacebookAds\Object\AdAccount($account_id))->read(array(
    \FacebookAds\Object\Fields\AdAccountFields::ID,
    \FacebookAds\Object\Fields\AdAccountFields::NAME,
    \FacebookAds\Object\Fields\AdAccountFields::ACCOUNT_STATUS
));
```

Gives the following error:
FacebookAds\Http\Exception\AuthorizationException
Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

I thought perhaps my access_token had expired, so I followed these steps:
-  get the code from the URL after going here: https://www.facebook.com/dialog/oauth?client_id=APP_ID&scope=ads_management&redirect_uri=https://www.mydomain.com/
- get the access token from the URL after going here: https://graph.facebook.com/oauth/access_token?client_id=APP_ID&redirect_uri=https://www.mydomain.com/&client_secret=APP_SECRET&code=AUTHORIZATION_CODE

I tried with the new access token but got the same message.

**Comment by timothymarois** [comment]
@cornernote This needs to be explained in the documentation. I just came across this issue wasting an hour trying to figure it out. Honestly, it shouldn't even be a problem. Just build a check in the method. Let the whole thing come crumbling down because you didn't append a string to an integer, stupid.
