### ISSUE TITLE
How to debug when I get the error ((#3) Application does not have the capability to make this API cal) ?

### ISSUE THREAD

**Issue by tianyiwangnova** [facebook/facebook-php-ads-sdk#363]
I'm trying to get facebook ads insights with the `facebookads` package in Python. But I got the error:
`(#3) Application does not have the capability to make this API call.`. I referred to the [question](https://github.com/facebook/facebook-php-ads-sdk/issues/266) but still couldn't find a solution. Besides, I have ticked the ads management and ads read options when I got my user access token. 

I would like to know how to debug and fix this. I think maybe it's not about coding but simply some manual settings in the ads manager. But I don't know where it is...

If you have solved this kind of problem before, can you plz share some tricks? Thanks!

**Comment by cloudxu** [comment]
I believe your App does not have capability of managing ads. Go to developer.facebook.com and manage your App. On the left pane, you should see "Marketing API". If you can't see it, you will need to "+ Add Product" to include "Marketing API". After that, in the Marketing API section, you can try the getting started wizard on Ads Insights.

**Comment by embatbr** [comment]
@cloudxu I had the same problem. I already made the permissions subscriptions and I am waiting. One of the developers who worked with FB api said that FB itself grants these permissions and they're taking several weeks to analyze.
