### ISSUE TITLE
Facebook php ads sdk CurlLogger.php

### ISSUE THREAD

**Issue by bogdandin** [facebook/facebook-php-ads-sdk#372]
`Warning: fwrite() expects parameter 1 to be resource, string given in /var/www/myapp/vendor/facebook/php-ads-sdk/src/FacebookAds/Logger/CurlLogger.php on line 182
`
I have this error... how fix that ? and this code is in on that line

`fwrite($this->handle, $buffer.PHP_EOL.PHP_EOL);`

I tried to debug and return this:

`curl -G \ -d 'level=account' \ -d 'filtering=[]' \ -d 'breakdowns=["age","gender"]' \ -d 'time_range={"since":"2017-09-06","until":"2017-10-06"}' \ -d 'fields=results,result_rate,reach,frequency,impressions,delivery,social_reach,social_impressions,total_actions,total_unique_actions,relevance_score:score,relevance_score:positive_feedback,relevance_score:negative_feedback,spend,today_spend,cost_per_result,cpp,cpm,cost_per_total_action,actions:page_engagement,actions:like,actions:mention,actions:tab_view,actions:comment,actions:post_engagement,actions:post_reaction,actions:post,actions:photo_view,actions:rsvp,actions:receive_offer,actions:checkin,cost_per_action_type:page_engagement,cost_per_action_type:like,cost_per_action_type:mention,cost_per_action_type:tab_view,cost_per_action_type:comment,cost_per_action_type:post_engagement,cost_per_action_type:post_reaction,cost_per_action_type:post,cost_per_action_type:photo_view,cost_per_action_type:rsvp,cost_per_action_type:receive_offer,cost_per_action_type:checkin,actions:video_view,video_10_sec_watched_actions:video_view,video_30_sec_watched_actions:video_view,video_p25_watched_actions:video_view,video_p50_watched_actions:video_view,video_p75_watched_actions:video_view,video_p95_watched_actions:video_view,video_p100_watched_actions:video_view,video_avg_time_watched_actions:video_view,video_avg_percent_watched_actions:video_view,canvas_avg_view_time,canvas_avg_view_percent,canvas_component_avg_pct_view:canvas_view,cost_per_action_type:video_view,cost_per_10_sec_video_view:video_view,actions:link_click,unique_actions:link_click,outbound_clicks:outbound_click,website_ctr:link_click,unique_link_clicks_ctr,call_to_action_clicks,clicks,unique_clicks,ctr,unique_ctr,social_clicks,unique_social_clicks,cost_per_action_type:link_click,cost_per_unique_action_type:link_click,cpc,cost_per_unique_click,estimated_ad_recallers,estimated_ad_recall_rate,cost_per_estimated_ad_recallers' \ -d 'access_token=aaaaaaaaa' \ -d 'appsecret_proof=aaaaaa' \ https://graph.facebook.com/v2.8/act_aaaaaaa/insights
`

Code of my file:

`<?php

require __DIR__ . '/vendor/autoload.php';

use FacebookAds\Object\AdAccount;
use FacebookAds\Object\AdsInsights;
use FacebookAds\Api;
use FacebookAds\Logger\CurlLogger;

$access_token = 'hidden';
$ad_account_id = 'hidden';
$app_secret = 'hidden';

$api = Api::init($app_id, $app_secret, $access_token);
$api->setLogger(new CurlLogger());

$fields = array(
  'actions:link_click',
  'unique_actions:link_click',
  'clicks',
);
$params = array(
  'level' => 'account',
  'filtering' => array(),
  'breakdowns' => array('age','gender'),
  'time_range' => array('since' => '2017-09-06','until' => '2017-10-06'),
);
echo json_encode((new AdAccount($ad_account_id))->getInsights($fields,$params)->getResponse()->getContent(), JSON_PRETTY_PRINT);`

This code is generated by facebook marketing api Screenshot here https://prnt.sc/gtqbf5 and use php 5.6.3

**Comment by hakimio** [comment]
By default CurlLogger writes to console and obviously if you are running a web app that will not work.
Instantiate CurlLogger with file pointer resource (see "fopen()" php function) or simply don't set the logger to your Api instance.
Also, you have some invalid fields in your "$fields" array.
