### ISSUE TITLE
new AdAccountUser("me"); Will throw an error now

### ISSUE THREAD

**Issue by ontraportgithub** [facebook/facebook-php-ads-sdk#387]
$me = new AdAccountUser("me"); Worked fine before but now requires an id.

If I remove that restriction within AbstractCrudObject the endpoint still takes it and it works.

**Comment by Eldair** [comment]
This is a breaking change since 2.11

**Comment by Eldair** [comment]
Why closed?

**Comment by Eldair** [comment]
@windsfantasy6

**Comment by Tlapi** [comment]
I agree with @Eldair, why is this closed? @windsfantasy6 ?

**Comment by ontraportgithub** [comment]
I'm unaware why also. Is still a problem. @windsfantasy6

**Comment by Tlapi** [comment]
@ontraportgithub There is a solution here #394
