### ISSUE TITLE
To create campaign $parent_id is required but the AbstractCrudObject construct with null and $parent_id is deprecated...

### ISSUE THREAD

**Issue by LNDev** [facebook/facebook-php-ads-sdk#391]
Creating campaign $parent_id is required. 

With :

$campaign = new Campaign();

the _create_ method throw new Exception :

> Exception: A parent ID is required.

Doing :

$campaign = new Campaign(null, "act_XXXXXX");

> $parent_id as a parameter of constructor is being deprecated, please try not to use this in new code.

What should I do?

**Comment by windsfantasy6** [comment]
Hi,
I think we have a 'adaccount.createCampaign' method. Maybe you should try this?
ex. Campaign campaign = new AdAccount(ad_account_id, context).createCampaign().setSomethingParams().execute()
