### ISSUE TITLE
Method getAssignedPages from class FacebookAds\Object\Business was deleted  

### ISSUE THREAD

**Issue by igortregub** [facebook/facebook-php-ads-sdk#392]
Hi,
I tried to update facebook/php-ads-sdk to the latest version 2.11.1.
I found that method getAssignedPages from class FacebookAds\Object\Business was deleted.
Is it OK? Because I need for this method in my application.

**Comment by windsfantasy6** [comment]
According to the change log for v2.11:

> Deprecated endpoints for managing assets belonging to another business:
> 
> BUSINESS_ID/assigned_ad_accounts
> BUSINESS_ID/assigned_pages
> BUSINESS_ID/assigned_product_catalogs
> Instead, use BUSINESS_USER_ID/assigned_ASSET

You can find it here: https://developers.facebook.com/docs/graph-api/changelog/version2.11#mapi

**Comment by igortregub** [comment]
Thank you

**Comment by igortregub** [comment]
Hi, I tried to find any docks about this endpoind BUSINESS_USER_ID/assigned_ASSET but I didn't find it.
Where can I find docks about this?
