### ISSUE TITLE
CurlAdapter failed

### ISSUE THREAD

**Issue by bmbraga** [facebook/facebook-php-ads-sdk#412]
Can someone help me with this error?
I've done several tests and nothing happens.

PHP Notice:  Use of undefined constant STDOUT - assumed 'STDOUT' in _libs/facebook-ads-sdk/FacebookAds/Logger/CurlLogger.php on line 84
PHP Warning:  fwrite() expects parameter 1 to be resource, string given in _libs/facebook-ads-sdk/FacebookAds/Logger/CurlLogger.php on line 199
PHP Fatal error:  Uncaught FacebookAds\\Exception\\Exception in _libs/facebook-ads-sdk/FacebookAds/Http/Adapter/CurlAdapter.php:196\nStack trace:\n#0 _libs/facebook-ads-sdk/FacebookAds/Http/Client.php(204): FacebookAds\\Http\\Adapter\\CurlAdapter->sendRequest(Object(FacebookAds\\Http\\Request))\n#1 _libs/facebook-ads-sdk/FacebookAds/Http/Request.php(282): FacebookAds\\Http\\Client->sendRequest(Object(FacebookAds\\Http\\Request))\n#2 _libs/facebook-ads-sdk/FacebookAds/Api.php(162): FacebookAds\\Http\\Request->execute()\n#3 _libs/facebook-ads-sdk/FacebookAds/Api.php(204): FacebookAds\\Api->executeRequest(Object(FacebookAds\\Http\\Request))\n#4 _libs/facebook-ads-sdk/FacebookAds/ApiRequest.php(183): FacebookAds\\Api->call('/act_6030462131...', 'GET', Array, Array)\n#5 _libs/facebook-ads-sdk/FacebookAds/Object/AdAccount.php(1368): FacebookAds\\ApiRequest->execute in _libs/facebook-ads-sdk/FacebookAds/Http/Adapter/CurlAdapter.php on line 196

`$access_token = '...';
$ad_account_id = '...';
$app_secret = '...';
$app_id = '...';

$api = Api::init($app_id, $app_secret, $access_token);
$api->setLogger(new CurlLogger());

$fields = array(
  'delivery'
);
$params = array(
);
echo json_encode((new AdAccount($ad_account_id))->getInsights(
  $fields,
  $params
)->getResponse()->getContent(), JSON_PRETTY_PRINT);

var_export((new AdAccount($ad_account_id)));`

**Comment by windsfantasy6** [comment]
Fixed by https://github.com/facebook/facebook-php-ads-sdk/commit/234d33cef20a30bf729ef7b76d6e67ea133dc04f
