### ISSUE TITLE
 Object with ID does not exist, cannot be loaded due to missing permissions, or does not support this operation

### ISSUE THREAD

**Issue by eComEvo** [facebook/facebook-php-ads-sdk#424]
I've generated a token and I'm trying to call the `AdAccount` but each time I do, I get this error:
Unsupported get request. Object with ID '1234567890' does not exist, cannot be loaded due to missing permissions, or does not support this operation.

That account ID definitely exists and I added the account ID under the "Settings" > "Ads API Account Configuration" area for the Marketing API, but still no bueno.

This is my code:
```
Api::init(
    config('facebook.app_id'),
    config('facebook.app_secret'),
    config('facebook.app_token')
);
$api = Api::instance();

$adAccount = new AdAccount('1234567890');
$fields = [
    AdAccountFields::ID,
    AdAccountFields::NAME,
    AdAccountFields::AMOUNT_SPENT,
];

dd($adAccount->read($fields));
```

What could be wrong here?

**Comment by wei-fb** [comment]
Were you able to read the AdAccount from graph API explorer https://developers.facebook.com/tools/explorer with your access token?

**Comment by joserosapt** [comment]
Maybe related to this:
https://developers.facebook.com/bugs/179937509459076/

**Comment by eComEvo** [comment]
I tried with the app's access token on the Graph API Explorer, but when I do I get this error
```
{
  "error": {
    "message": "(#2) Service temporarily unavailable",
    "type": "OAuthException",
    "is_transient": true,
    "code": 2,
    "fbtrace_id": "HHUyI6LX5S8"
  }
}
```

When I try to do it with my user access token, I get this error:
```
{
  "error": {
    "message": "Unsupported get request.",
    "type": "GraphMethodException",
    "code": 100,
    "fbtrace_id": "E5pb3WKjQb1"
  }
}
```

The GET request I'm making is simply to `/act_1234567890`. When I changed `new AdAccount('1234567890');` in my code to `new AdAccount('act_1234567890');` the error switches to the `Unsupported get request` so at least that progress.

**Comment by wei-fb** [comment]
Have you verified that you have the permission to the requested ad account? You might need to ask the owner/admin to grant you the access and then you should be able to read the ad account.

This does not appear to be a sdk issue since you get consistent behavior from both graph api explorer and sdk, I'd suggest you verify the permission first and engage graph api support https://developers.facebook.com/tools-and-support/ for additional help.

**Comment by eComEvo** [comment]
When I switched to using the account owner's user token, it all worked correctly. Apparently permissions weren't set or working for mine even tho I was added as an admin.
