### ISSUE TITLE
error when creating custom audience

### ISSUE THREAD

**Issue by cornernote** [facebook/facebook-php-ads-sdk#43]
The code:

``` php
use \FacebookAds\Api;
use \FacebookAds\Object\CustomAudience;
use \FacebookAds\Object\Fields\CustomAudienceFields;

Api::init($app_id, $app_secret, $access_token);

$audience = new CustomAudience(null, $account_id);
$audience->setData(array(
    CustomAudienceFields::NAME => 'test',
    CustomAudienceFields::DESCRIPTION => 'test',
    CustomAudienceFields::DATA_SOURCE => array('EVENT_BASED' => 'WEB_PIXEL_HITS'),
));
$audience->create();
```

The error:

```
(#2655) Terms of service has not been accepted
```

I have 2 questions:
1) How do I agree to the terms of service?  When I create a custom audience through the web interface there is a checkbox each time I create one.
2) Am I setting the DATA_SOURCE correctly? I want an audience based on hits to a single page. The code I used is based of the docs here, but there is no clear example for the specific scenario I want:
https://developers.facebook.com/docs/reference/ads-api/custom-audience-targeting/#data_source

**Comment by IAmMukeshKumar** [comment]
PHP Fatal error:  Uncaught FacebookAds\Http\Exception\AuthorizationException: (#2663) Terms of service has not been accepted. To accept, go to https://www.facebook.com/customaudiences/app/tos/?act=105142470269795 in /Users/williammukesh/facebook-php-ads-sdk/src/FacebookAds/Http/Exception/RequestException.php:144


After hitting:https://www.facebook.com/customaudiences/app/tos/?act=105142470269795
![screen shot 2017-11-26 at 3 41 50 pm](https://user-images.githubusercontent.com/13366065/33239076-7d448ff0-d2c0-11e7-89c5-43677be97b9b.png)

but the below url shows I have accepted TOS.
https://www.facebook.com/customaudiences/app/tos/

**Comment by IAmMukeshKumar** [comment]
Plz tell me If you guys have any idea to fix this issue.

**Comment by Taytay** [comment]
If you are using a sandbox, you need to follow these steps (grabbed from this StackOverflow answer: https://stackoverflow.com/a/42766604/544130):
"To accept custom audiences ToS go to the application management -> Marketing API -> Tools -> Sandbox Ad Account Management -> Actions -> Accept TOS"

**Comment by sonhgc00016** [comment]
@Taytay I have already Accept TOS like the step you describe but  I still facing error when using sandbox. Do you solve the problem? 
```
{
  "error": {
    "message": "Permissions error",
    "type": "OAuthException",
    "code": 200,
    "error_subcode": 1870034,
    "is_transient": false,
    "error_user_title": "Custom Audience Terms Not Accepted",
    "error_user_msg": "You'll need to agree to the Custom Audience terms before you can create or edit an audience of CUSTOM type. To accept, go to https://www.facebook.com/ads/manage/customaudiences/tos/?act=313575366050779.",
    "fbtrace_id": "CQhFmQpzyoS"
  }
}
```
