### ISSUE TITLE
Location of fb_ca_chain_bundle.crt

### ISSUE THREAD

**Issue by tharlinsmith** [facebook/facebook-php-ads-sdk#47]
Suggest that you move the certificate file to Http/Adapter so that the src directory can be a self-contained distribution.  This also matches the convention used by the PHP SDK for the Graph API.

**Comment by pruno** [comment]
Hi @tharlinsmith,

that has been avoided on purpose. Certificate changes should not require a new code update. What i believe is currently missing is the ability to set a custom path to a certificate. I'll try to add it to the new minor release. If you install thru composer (which is the preferred way) everything will be set. If you need to manually include, i advice in storing the cert in a different location and set a custom path for it in the SDK (as soon as this feature will be available)

**Comment by pruno** [comment]
https://github.com/facebook/facebook-php-ads-sdk/commit/360b5d1d9e4728e4ab61dbe98dbbc8de455c5563
