### ISSUE TITLE
AdsInsightsFields out of sync with API

### ISSUE THREAD

**Issue by edbizarro** [facebook/facebook-php-ads-sdk#481]
The fields in [AdsInsightsFields](https://github.com/facebook/facebook-php-business-sdk/blob/master/src/FacebookAds/Object/Fields/AdsInsightsFields.php) do not reflect the latest [API version](https://developers.facebook.com/docs/marketing-api/reference/ads-insights/)

```
1) FacebookAds\Http\Exception\AuthorizationException: (#100) app_store_clicks, deeplink_clicks, newsfeed_avg_position, newsfeed_clicks, newsfeed_impressions, unique_impressions, video_complete_watched_acti
ons, website_clicks are not valid for fields param. please check https://developers.facebook.com/docs/marketing-api/reference/ads-insights/ for all valid values
```

**Comment by jingping2015** [comment]
Can you provide what the code you get this error.
