### ISSUE TITLE
no data returned when calling $adCreative->read() without specifying fields

### ISSUE THREAD

**Issue by cornernote** [facebook/facebook-php-ads-sdk#49]
I try to read an AdCreative like this:

``` php
Api::init($app_id, $app_secret, $access_token);
$adCreative = new AdCreative($ad_creative_id, $account_id);
$adCreative->read();
print_r($adCreative->getData());
```

But it results in:

```
Array
(
    [id] => THE ID
    [title] => 
    [actor_id] => 
    [actor_name] => 
    [name] => 
    [object_id] => 
    [object_story_id] => 
    [object_story_spec] => 
    [body] => 
    [image_hash] => 
    [image_file] => 
    [image_url] => 
    [image_crops] => 
    [video_id] => 
    [actor_image_hash] => 
    [link_url] => 
    [object_url] => 
    [url_tags] => 
    [preview_url] => 
    [follow_redirect] => 
    [object_store_url] => 
    [link_deep_link_url] => 
    [call_to_action_type] => 
    [object_type] => 
)
```

I then try using `$adCreative->getFields()` as an argument to `$adCreative->read()`:

``` php
Api::init($app_id, $app_secret, $access_token);
$adCreative = new AdCreative($ad_creative_id, $account_id);
$adCreative->read($adCreative->getFields());
print_r($adCreative->getData());
```

Which throws an exception:

```
Array
        (
            [message] => (#100) Tried accessing nonexisting field (image_file) on node type (AdCreative)
            [type] => OAuthException
            [code] => 100
        )
```

I then remove `image_file` from the list of fields:

``` php
Api::init($app_id, $app_secret, $access_token);
$adCreative = new AdCreative($ad_creative_id, $account_id);
$fields = $adCreative->getFields();
foreach ($fields as $k => $v) {
    if ($v = 'image_file') {
        unset($fields[$k]);
    }
}
$adCreative->read($fields);
print_r($adCreative->getData());
```

Which results again in no data:

```
Array
(
    [id] => THE ID
    [title] => 
    [actor_id] => 
    [actor_name] => 
    [name] => 
    [object_id] => 
    [object_story_id] => 
    [object_story_spec] => 
    [body] => 
    [image_hash] => 
    [image_file] => 
    [image_url] => 
    [image_crops] => 
    [video_id] => 
    [actor_image_hash] => 
    [link_url] => 
    [object_url] => 
    [url_tags] => 
    [preview_url] => 
    [follow_redirect] => 
    [object_store_url] => 
    [link_deep_link_url] => 
    [call_to_action_type] => 
    [object_type] => 
)
```

I try making my own fields array, and then remove any that cause an exception, and end up with this list:

``` php
Api::init($app_id, $app_secret, $access_token);
$adCreative = new AdCreative($ad_creative_id, $account_id);
$fields = array(
    AdCreativeFields::ID,
    AdCreativeFields::TITLE,
    AdCreativeFields::ACTOR_ID,
    AdCreativeFields::ACTOR_NAME,
    AdCreativeFields::NAME,
    AdCreativeFields::OBJECT_ID,
    AdCreativeFields::OBJECT_STORY_ID,
    AdCreativeFields::OBJECT_STORY_SPEC,
    AdCreativeFields::BODY,
    AdCreativeFields::IMAGE_HASH,
    //AdCreativeFields::IMAGE_FILE,
    AdCreativeFields::IMAGE_URL,
    AdCreativeFields::IMAGE_CROPS,
    AdCreativeFields::VIDEO_ID,
    AdCreativeFields::ACTOR_IMAGE_HASH,
    AdCreativeFields::LINK_URL,
    AdCreativeFields::OBJECT_URL,
    AdCreativeFields::URL_TAGS,
    //AdCreativeFields::PREVIEW_URL,
    //AdCreativeFields::FOLLOW_REDIRECT,
    AdCreativeFields::OBJECT_STORE_URL,
    AdCreativeFields::LINK_DEEP_LINK_URL,
    AdCreativeFields::CALL_TO_ACTION_TYPE,
    AdCreativeFields::OBJECT_TYPE,
);
$adCreative->read($fields);
print_r($adCreative->getData());
```

Now I get what is expected (i have replaced the actual data incase of any security issue sharing it):

```
Array
(
    [id] => THE ID
    [title] => AD TITLE
    [actor_id] => THE ACTOR ID
    [actor_name] => 
    [name] => AD NAME
    [object_id] => 
    [object_story_id] => 
    [object_story_spec] => 
    [body] => AD BODY
    [image_hash] => IMAGE HASH
    [image_file] => 
    [image_url] => https://fbcdn-creative-a.akamaihd.net/REMOVED-PATH.png
    [image_crops] => 
    [video_id] => 
    [actor_image_hash] => 
    [link_url] => 
    [object_url] => http://www.example.com/
    [url_tags] => 
    [preview_url] => 
    [follow_redirect] => 
    [object_store_url] => 
    [link_deep_link_url] => 
    [call_to_action_type] => 
    [object_type] => DOMAIN
)
```

My question is, is this the expected behaviour?  Or should I be able to do `$adCreative->read()` without specifying a field list?

**Comment by bibibaonam** [comment]
hi cornernote,
where can I get $access_token to put into Api::init($app_id, $app_secret, $access_token); ?
thank you very much

**Comment by cornernote** [comment]
hey @bibibaonam,

It's explained here:
https://developers.facebook.com/docs/reference/ads-api/overview#access_token

**Comment by cornernote** [comment]
here is my quick guide:

1) get the AUTHORIZATION_CODE from the URL after going here:
https://www.facebook.com/dialog/oauth?client_id=YOUR_APP_ID&scope=ads_management&redirect_uri=http://yourdomain.com/

2) get the access token from the URL after going here:
https://graph.facebook.com/oauth/access_token?client_id=YOUR_APP_ID&redirect_uri=https://yourdomain.com/&client_secret=YOUR_CLIENT_SECRET&code=AUTHORIZATION_CODE

**Comment by bibibaonam** [comment]
thank you, cornernote.
I do everything you said, but when I run:

$acces_token = 'CAAGV4BN8ZBicBAC5HOZAnwLefwcakyVhAZAs12d4aZCZAm2NTY5AFVx8iCxvl4zKrq4VXZC7H9N1rpikTuo9IpKM06p0BAq9ob71LFAvrhEF3LnTIS5BvHxquHnautHhxwdHrdH6ZBpZBpg9jVGfFTjnWJBdZCxr99qssIvOZBdQVUaEqudDRVUx6o8HYxf3w2nteCayvnVXOfZBuBbZApeEt8AI';
		Api::init($this->config->fb->appId, $this->config->fb->secret, $acces_token);
		$api = Api::instance();

		$account = new AdAccount('113715605471367');
		$adaccount = $account->read();
		echo '-------------- adaccount ----------------<br>';
		pr($adaccount);
		die;

Errors happen like below, please help me, thanks:

Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api
#0 I:\Working\baonam\vendor\facebook\php-ads-sdk\src\FacebookAds\Http\Client.php(216): FacebookAds\Http\Exception\RequestException::create(Array, 400)
#1 I:\Working\baonam\vendor\facebook\php-ads-sdk\src\FacebookAds\Http\Request.php(282): FacebookAds\Http\Client->sendRequest(Object(FacebookAds\Http\Request))
#2 I:\Working\baonam\vendor\facebook\php-ads-sdk\src\FacebookAds\Api.php(152): FacebookAds\Http\Request->execute()
#3 I:\Working\baonam\vendor\facebook\php-ads-sdk\src\FacebookAds\Api.php(194): FacebookAds\Api->executeRequest(Object(FacebookAds\Http\Request))
#4 I:\Working\baonam\vendor\facebook\php-ads-sdk\src\FacebookAds\Object\AbstractCrudObject.php(288): FacebookAds\Api->call('/11371560547136...', 'GET', Array)
#5 I:\Working\baonam\app\controllers\IndexController.php(28): FacebookAds\Object\AbstractCrudObject->read()
#6 [internal function]: BaoNam\Controllers\IndexController->indexAction()
#7 [internal function]: Phalcon\Dispatcher->dispatch()
#8 I:\Working\baonam\public\index.php(34): Phalcon\Mvc\Application->handle()
#9 {main}

**Comment by paulbain** [comment]
Please don't share access tokens publicly. That's a quick way to get your account into a lot of trouble.
You should consider changing your FB password to invalidate the token you just shared, or uninstalling the app from your FB settings.

**Comment by paulbain** [comment]
To answer your question, prefix the account ID with act_ like in all the examples:

    $account = new AdAccount('act_<YOUR ACCOUNT ID>);
    $fields_you_want_to_read = array('name');
    $adaccount = $account->read($fields_you_want_to_read);
    echo $adaccount->name;

**Comment by bibibaonam** [comment]
Thank you very much Paulbain.
I removed app from my account https://www.facebook.com/settings?tab=applications 
Your reply worked, tks again.

**Comment by victorarthur** [comment]
Hi @paulbain 
I have the same issue, I would like to clone the AdCreative (to rename the url_tags and this parameter doesn't available on the /copies node) so I have do download the object and recreate with a different url_tags parameter. In advance, I don't know what fields does the AdObject has so I can not pre-define the fields I would request.

Do you know any solution for this issue?
