### ISSUE TITLE
Ads Report Stats  Error

### ISSUE THREAD

**Issue by sandy69** [facebook/facebook-php-ads-sdk#51]
I am getting PHP Parse error: syntax error, unexpected T_USE, expecting T_FUNCTION in /FacebookAds/Object/AdAccount.php on line 34

I am on PHP Version 5.3.5

Below is the PHP Code, where I am accessing the class. Please let me know, if you see any issues with the code. I am not a PHP Expert. Thanks.

<?php

require_once "FacebookAds/Object/AdAccount.php";

$account =529158;
$fields = array('account_id', 'total_actions', 'spend');

$params = array(
    'data_columns' => array (
        'account_id',
        'total_actions',
        'spend'
    ),
    'date_preset' => 'last_7_days',
);

 $account = new AdAccount('act_' . $accountID);
 $reports = $account->getReportsStats($fields, $params);
 $response = array();
   foreach($reports as $report) {
        $response[] = $report->getData();
    }
    return json_encode($response);  
   
?>

**Comment by pruno** [comment]
hi @sandy69,

your script doesn't include the composer autoloader:

  //  <PROJECT_DIRECTORY> is the dir in which your composer.json is stored
  include <PROJECT_DIRECTORY>.'/vendor/autoload.php';

Also take note that 'act_5291585038833333' is not the account name but the id:
Please take a look at this gist: https://gist.github.com/pruno/de102291ddc7539b0583/revisions

If you have any other inherent query, feel free to reply here, i'll will reopen if necessary.

**Comment by sandy69** [comment]
Hi,

Thanks for your reply. I made the changes, as you said.

require_once( '/tmp/vendor/autoload.php' );

use FacebookAds\Object\AdAccount;

$account = new AdAccount();
$account->name = 'pinger';
echo $account->name;


Now, I get a different error

PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'An Api instance must be provided as argument or set as instance in the \FacebookAds\Api' in /tmp/vendor/facebook/php-ads-sdk/src/FacebookAds/Object/AbstractCrudObject.php:105
Stack trace:
#0 /tmp/vendor/facebook/php-ads-sdk/src/FacebookAds/Object/AbstractCrudObject.php(68): FacebookAds\Object\AbstractCrudObject::assureApi(NULL)
#1 /tmp/vendor/facebook/php-ads-sdk/src/FacebookAds/fb.php(7): FacebookAds\Object\AbstractCrudObject->__construct()
#2 {main}
  thrown in /tmp/vendor/facebook/php-ads-sdk/src/FacebookAds/Object/AbstractCrudObject.php on line 105


Thank you.

**Comment by pruno** [comment]
hi @sandy69,

you also need to initialize the SDK.

i've updated the gist with the necessary code: https://gist.github.com/pruno/de102291ddc7539b0583/revisions

You can obtain your APP_ID and APP_SECRET from https://developers.facebook.com/apps/
And generate a token from https://developers.facebook.com/tools/explorer/  (remember to select the same app form the select input on top)

Also remember to set your ad_account id:

~~~
$account = new AdAccount('act_5291585038833333');
~~~
