### ISSUE TITLE
While create adset then I got error 'Invalid parameter'

### ISSUE THREAD

**Issue by anillabs** [facebook/facebook-php-ads-sdk#52]
Hello,
I am using FB Ads API, and successfully created campaigns and get the ID from Facebook. In the next step to create adset with below code then got error.

// Call create using an array of parameters.
$data = array(
  AdSetFields::NAME => 'My AdSet',
  AdSetFields::BID_TYPE => 'CPC',
  AdSetFields::BID_INFO => array(
    'CLICKS' => 500,
  ),
  AdSetFields::CAMPAIGN_STATUS => AdSet::STATUS_ACTIVE,
  AdSetFields::DAILY_BUDGET => 200,
  AdSetFields::CAMPAIGN_GROUP_ID => $campaign_id,
  AdSetFields::TARGETING => array(
    'geo_locations' => array(
      'countries' => array(
        'US',
        'GB',
      ),
    ),
  ),
);
$ad_set = new AdSet(null, $account->id);
$ad_set->create($data);

Fatal error: Uncaught exception 'FacebookAds\Http\Exception\AuthorizationException' with message 'Invalid parameter' in /www/facebookads/src/FacebookAds/Http/Exception/RequestException.php:129

**Comment by idanhen** [comment]
thanks for posting this issue.

version 2.5 still have the same error.

**Comment by gnumoksha** [comment]
In 2.11.* version this message is still the same, unfortunately. See https://github.com/facebook/facebook-php-ads-sdk/issues/362
