### ISSUE TITLE
I can't create ad group!

### ISSUE THREAD

**Issue by airdomain** [facebook/facebook-php-ads-sdk#72]
With Facebook Ad Api, I can't create ad(group) although I have created the Campaign, AdSet, and AdCreative. I have followed instruction of facbook guide(with the all required parameters). I can't find the answer by any googling.... What's wrong? (I just found the change that ADGROUP_STATUS is required now.)

------------ PHP Codes ------------------

use FacebookAds\Object\AdGroup;
use FacebookAds\Object\Fields\AdGroupFields;

$adgroup = new AdGroup(null, $account->id);
$adgroup->setData(array(
  AdGroupFields::CREATIVE => array('creative_id' => $creative->id),
  AdGroupFields::NAME => 'My First AdGroup',
  AdGroupFields::CAMPAIGN_ID => $adset->id,
  AdGroupFields::ADGROUP_STATUS => 'ACTIVE',
));

$adgroup->create();

**Comment by minhsepteni** [comment]
Can you tell me the error message? Have you enter a valid credit card in facebook billing form?

**Comment by pruno** [comment]
Hi @airdomain,

as mentioned by @minhsepteni, the details of the error you are facing are necessary to understand the issue. Few notes:
- in order to create an AdGroup, the parent AdAccount needs to have a valid payment method associated with it:
- to fully understand issues you need to catch the RequestException that the SDK throws:

~~~
use FacebookAds\Http\Exception\RequestException;

try {

// Your code here

} catch (RequestException $e) {
  echo 'Caught Exception: '.$e->getMessage().PHP_EOL
    .'Code: '.$e->getCode().PHP_EOL
    .'HTTP status Code: '.$e->getHttpStatusCode().PHP_EOL
    .'Error Subcode: '.$e->getErrorSubcode().PHP_EOL
    .'Error User Title: '.$e->getErrorUserTitle().PHP_EOL
    .'Error User Message: '.$e->getErrorUserMessage().PHP_EOL;
}

**Comment by airdomain** [comment]
Ok, Thanks for your attention.

I show you my some results and error codes as following,

using this account : act_3xxxxxxxx
Campaign ID : 6xxxxxxxxxxxx
AdSet ID : 6xxxxxxxxxxxx
Image Hash : 3dxxxxxxxxxxxxxxxxxxxxxxxxxx
Creative ID : 6xxxxxxxxxxxx

Caught Exception : Invalid parameter
Code : 100
HTTP status Code : 500
Error Subcode:1487989
Error User Title : Adgroup Targeting and Bidding Not Supported
Error User Message : As of API version 2.2, targeting and bid_type are no longer configured
                                   on Ad Groups. Instead, they must be set on the Ad Set.


Here is the entire codes,

<?php
/**
 * Copyright 2014 Facebook, Inc.
 *
 * You are hereby granted a non-exclusive, worldwide, royalty-free license to
 * use, copy, modify, and distribute this software in source code or binary
 * form for use in connection with the web services and APIs provided by
 * Facebook.
 *
 * As with any software that integrates with the Facebook platform, your use
 * of this software is subject to the Facebook Developer Principles and
 * Policies [http://developers.facebook.com/policy/]. This copyright notice
 * shall be included in all copies or substantial portions of the software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

// Set your access token here:
$access_token = $_REQUEST['access_token'];
$app_id = $_REQUEST['app_id'];
$app_secret = $_REQUEST['app_secret'];
$account_id = $_REQUEST['account_id'];

if(is_null($access_token) || is_null($app_id) || is_null($app_secret)) {

  throw new \Exception(
    'You must set your access token, app id and app secret before executing'
  );
}

//echo $access_token."/".$app_id."/".$app_secret."<br />";


if (is_null($account_id)) {
  throw new \Exception(
    'You must set your account id before executing');
}

define('SDK_DIR', __DIR__ . '/..'); // Path to the SDK directory
$loader = include SDK_DIR.'/../../../vendor/autoload.php';

//echo "__DIR__:".__DIR__."\n";
//echo "SDK_DIR:".SDK_DIR."\n";
//echo "PARA : ".$access_token."/".$app_id."/".$app_secret."/".$account_id."\n";


use FacebookAds\Api;

Api::init($app_id, $app_secret, $access_token);

//echo $access_token."/".$app_id."/".$app_secret."<br />";
/**
 * Step 1 Read the AdAccount (optional)
 */
use FacebookAds\Object\AdAccount;
use FacebookAds\Object\Fields\AdAccountFields;


$account = (new AdAccount($account_id))->read(array(
  AdAccountFields::ID,
  AdAccountFields::NAME,
  AdAccountFields::ACCOUNT_STATUS
));

echo "\nUsing this account: ";
echo $account->id."\n";

// Check the account is active
if($account->{AdAccountFields::ACCOUNT_STATUS} !== 1) {
  throw new \Exception(
    'This account is not active');
}

/**
 * Step 2 Create the AdCampaign
 */
use FacebookAds\Object\AdCampaign;
use FacebookAds\Object\Fields\AdCampaignFields;
use FacebookAds\Object\Values\AdObjectives;

$campaign  = new AdCampaign(null, $account->id);
$campaign->setData(array(
  AdCampaignFields::NAME => 'My First Campaign',
  AdCampaignFields::OBJECTIVE => AdObjectives::WEBSITE_CLICKS,
  AdCampaignFields::STATUS => AdCampaign::STATUS_PAUSED,
));

$campaign->validate()->create();
echo "Campaign ID:" . $campaign->id . "\n";
//echo "Name : " . $campaign->{AdCampaignFields::NAME};

/**
 * Step 3 Search Targeting
 */
use FacebookAds\Object\TargetingSearch;
use FacebookAds\Object\Search\TargetingSearchTypes;

$results = TargetingSearch::search(
  $type = TargetingSearchTypes::INTEREST,
  $class = null,
  $query = 'facebook');

// we'll take the top result for now
$target = (count($results)) ? $results->current() : null;

echo "Using target: ".$target->name."\n";

use FacebookAds\Object\TargetingSpecs;
use FacebookAds\Object\Fields\TargetingSpecsFields;

$targeting = new TargetingSpecs();
$targeting->{TargetingSpecsFields::GEO_LOCATIONS}
  = array('countries' => array('KR'));
$targeting->{TargetingSpecsFields::INTERESTS} = array(
  'id' => $target->id,
  'name' => $target->name
);


/**
 * Step 4 Create the AdSet
 */
use FacebookAds\Object\AdSet;
use FacebookAds\Object\Fields\AdSetFields;
use FacebookAds\Object\Fields\AdGroupBidInfoFields;
use FacebookAds\Object\Values\BidTypes;


$adset = new AdSet(null, $account->id);

$adset->setData(array(
	AdSetFields::NAME => 'My AdSet',
	AdSetFields::CAMPAIGN_GROUP_ID => $campaign->id,
	AdSetFields::CAMPAIGN_STATUS => AdSet::STATUS_ACTIVE,
	AdSetFields::DAILY_BUDGET => 1000,
	AdSetFields::TARGETING => array('geo_locations' => array('countries' => array('KR'),),),
	AdSetFields::BID_TYPE => BidTypes::BID_TYPE_CPM,
	AdSetFields::BID_INFO => array(AdGroupBidInfoFields::IMPRESSIONS => 2),
	//AdSetFields::BID_TYPE => BidTypes::BID_TYPE_CPC,							
	//AdSetFields::BID_INFO => array(
	//								'CLICKS' => 500,
	//								),
	//AdSetFields::BID_INFO => array(AdGroupBidInfoFields::CLICKS => 500),
	AdSetFields::START_TIME => (new \DateTime("+1 week"))->format(\DateTime::ISO8601),
	AdSetFields::END_TIME => (new \DateTime("+2 week"))->format(\DateTime::ISO8601),

));


$adset->validate()->create();
//$adset->validate()->create2();
echo 'AdSet  ID: '. $adset->id . "\n";


/**
 * Step 5 Create an AdImage
 */
use FacebookAds\Object\AdImage;
use FacebookAds\Object\Fields\AdImageFields;

$image = new AdImage(null, $account->id);
//$image->{AdImageFields::FILENAME} = SDK_DIR.'/test/misc/FB-f-Logo__blue_512.png';
//=========================================================================================> Modify AdImage.php by yjingold
$image->{AdImageFields::FILENAME} = SDK_DIR.'/test/misc/image.png';

$image->create();
echo 'Image Hash: '.$image->hash . "\n";

/**
 * Step 5 Create an AdCreative
 */
use FacebookAds\Object\AdCreative;
use FacebookAds\Object\Fields\AdCreativeFields;

$creative = new AdCreative(null, $account->id);
$creative->setData(array(
  AdCreativeFields::NAME => 'Sample Creative',
  AdCreativeFields::TITLE => 'Welcome to the Jungle',
  AdCreativeFields::BODY => 'We\'ve got fun \'n\' games',
  AdCreativeFields::IMAGE_HASH => $image->hash,
  AdCreativeFields::OBJECT_URL => 'http://www.example.com',
));

$creative->create();
echo 'Creative ID: '.$creative->id . "\n";


/**
 * Step 7 Create an AdGroup
 */
use FacebookAds\Object\AdGroup;
use FacebookAds\Object\Fields\AdGroupFields;
use FacebookAds\Http\Exception\RequestException;


try {
$adgroup = new AdGroup(null, $account->id);
$adgroup->setData(array(
  AdGroupFields::CREATIVE => array('creative_id' => $creative->id),
  AdGroupFields::NAME => 'My First AdGroup',
  AdGroupFields::CAMPAIGN_ID => $adset->id,
  AdGroupFields::ADGROUP_STATUS => AdGroup::STATUS_ACTIVE,
  	AdGroupFields::BID_TYPE => BidTypes::BID_TYPE_CPM,
	AdGroupFields::BID_INFO => array(AdGroupBidInfoFields::IMPRESSIONS => 2),
//  AdGroupFields::OBJECTIVE => AdObjectives::WEBSITE_CLICKS,
//  AdGroupFields::TARGETING => array('geo_locations' => array('countries' => array('KR'),),),
//	AdGroupFields::BID_TYPE => BidTypes::BID_TYPE_CPC,							
//	AdGroupFields::BID_INFO => array(AdGroupBidInfoFields::CLICKS => 500),
));

$adgroup->create();

} catch (RequestException $e) {
  echo 'Caught Exception: '.$e->getMessage().PHP_EOL
    .'Code: '.$e->getCode().PHP_EOL
    .'HTTP status Code: '.$e->getHttpStatusCode().PHP_EOL
    .'Error Subcode: '.$e->getErrorSubcode().PHP_EOL
    .'Error User Title: '.$e->getErrorUserTitle().PHP_EOL
    .'Error User Message: '.$e->getErrorUserMessage().PHP_EOL;
}



echo 'AdGroup ID:' . $adgroup->id . "\n";

?>

And I have not entered payment method yet because I'm just in code-test step.
Is it critical?

**Comment by pruno** [comment]
@airdomain, as mentioned above, you need to setup a payment method for your ad account.
You can do it here: https://www.facebook.com/ads/manager/billing/payment_methods/
