### ISSUE TITLE
Graph API resolving to IPV6 sometime.

### ISSUE THREAD

**Issue by iamtrk** [facebook/facebook-php-ads-sdk#74]
Graph API requests are resolving to IPV6 some times. 

We can force the API to resolve to IPV4 by adding following code snippet after curl_init
curl_setopt($this->handle, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);

**Comment by paulbain** [comment]
Resolving to IPV6 is completely acceptable. If your server is IPV6 capable, then this behavior is actually beneficial. We will not provide methods to force IPV4 in the SDK unfortunately.

**Comment by iamtrk** [comment]
Lots of data centres in India are not IPV6 capable yet, we have recently faced this issue. May be you can mention this in the documentation.

**Comment by paulbain** [comment]
Could you configure your servers to not use IPV6 in that case? It shouldn't resolve to IPV6 if you aren't IPV6 capable, so it sounds like a misconfiguration.

**Comment by rohit1290** [comment]
Can you tell me where exactly to put the code: 
curl_setopt($this->handle, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);

**Comment by iamtrk** [comment]
Hi Rohit,

    I am not working with the SDK currently. If you trace back the method calling, you should be able to identify a code snippet where there will be a HTTP call to FB APIs which is based on curl.

    Or you can simply grep for curl_init.

**Comment by iamtrk** [comment]
Hi Rohit,
I am not working with the SDK currently. If you trace back the method calling, you should be able to identify a code snippet where there will be a HTTP call to FB APIs which is based on curl.

Or you can simply grep for curl_init. 

Thanks,
Ravikumar.
