### ISSUE TITLE
Building phar: curl: error setting certificate verify locations

### ISSUE THREAD

**Issue by diimpp** [facebook/facebook-php-ads-sdk#80]
Hi,
I'm building phar with usage of ads sdk and unfortunately I've this error.

```
  [FacebookAds\Exception\Exception]                                                                                                                                                   
  error setting certificate verify locations:                                                                                                                                         
    CAfile: phar:///home/username/workdir/build/acme.phar/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/Adapter/../../../../fb_ca_chain_bundle.crt  
    CApath: /etc/ssl/certs                                                                                                                                                              
```

I think it's totally the same error as this one https://github.com/FriendsOfPHP/Goutte/issues/88

Regards.

**Comment by pruno** [comment]
Hi @diimpp,

This is a known issue of php-curl: https://bugs.php.net/bug.php?id=69035
As discussed in https://github.com/facebook/facebook-php-ads-sdk/issues/47, certificates and SDK release cycles are completely different. We do provide the crt in the repo as a commodity (the default loading path doesn't really fit all situations).
My advice is to package the SDK without the certificate and install the certificate aside on your server(s).
Than, after loading the phar:

~~~
use FacebookAds\Api;

Api::init('<APP_ID>', '<APP_SECRET>', '<ACCESS_TOKEN>')
  ->getHttpClient()->setCaBundlePath('<PATH_TO_CERT>');
~~~

**Comment by diimpp** [comment]
Thank you, @pruno.
I'll follow your advice.

**Comment by andreladocruz** [comment]
@pruno,

I'm getting the same error here and my code is like this:

```php
private function initApi($accessToken)
    {
        Api::init(
            config('dmg.facebook.app_id'),
            config('dmg.facebook.app_secret'),
            $accessToken)
        ->getHttpClient()
        ->setCaBundlePath(base_path('vendor/facebook/php-business-sdk/fb_ca_chain_bundle.crt'));
    }
```

It worked for 2 days and now stoped again. Acctually it's an intermitent error.

What do you recommend me to do?
