### ISSUE TITLE
Get start day for Campaign

### ISSUE THREAD

**Issue by kentmt** [facebook/facebook-php-ads-sdk#81]
Hi ,

$campaign_new = new AdCampaign($campaign->id) ;
$fields = array(
	 'actions','spent','clicks','impressions','end_time','start_time',
 );
$params = array();
$stats = $campaign_new->getStats($fields,$params);
var_dump($stats);

But function doesn't show start_time and how to parse data from ojbect :
object(FacebookAds\Cursor)#483 (9) { ["response":protected]=> object(FacebookAds\Http\Response)#482 (5) { ["request":protected]=> object(FacebookAds\Http\Request)#480 (10) { ["client":protected]=> object(FacebookAds\Http\Client)#456 (6) { ["requestPrototype":protected]=> object(FacebookAds\Http\Request)#458 (10) { ["client":protected]=> *RECURSION* ["headers":protected]=> NULL ["method":protected]=> string(3) "GET" ["protocol":protected]=> string(8) "https://" ["domain":protected]=> NULL ["path":protected]=> NULL ["graphVersion":protected]=> NULL ["queryParams":protected]=> NULL ["bodyParams":protected]=> NULL ["fileParams":protected]=> NULL } ["responsePrototype":protected]=> object(FacebookAds\Http\Response)#468 (5) { ["request":protected]=> NULL ["statusCode":protected]=> NULL ["headers":protected]=> NULL ["body":protected]=> NULL ["content":protected]=> NULL } ["defaultRequestHeaders":protected]=> object(FacebookAds\Http\Headers)#470 (1) { ["storage":"ArrayObject":private]=> array(2) { ["User-Agent"]=> string(16) "fb-php-ads-2.3.0" ["Accept-Encoding"]=> string(1) "*" } } ["adapter":protected]=> object(FacebookAds\Http\Adapter\CurlAdapter)#466 (3) { ["curl":protected]=> object(FacebookAds\Http\Adapter\Curl\Curl)#467 (1) { ["handle":protected]=> resource(245) of type (curl) } ["opts":protected]=> object(ArrayObject)#471 (1) { ["storage":"ArrayObject":private]=> array(5) { [78]=> int(10) [13]=> int(60) [19913]=> bool(true) [42]=> bool(true) [10065]=> string(109) "/Users/Ken/Sites/adsfacebook/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/../../../fb_ca_chain_bundle.crt" } } ["client":protected]=> *RECURSION* } ["caBundlePath":protected]=> string(109) "/Users/Ken/Sites/adsfacebook/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/../../../fb_ca_chain_bundle.crt" ["defaultGraphBaseDomain":protected]=> string(12) "facebook.com" } ["headers":protected]=> object(FacebookAds\Http\Headers)#484 (1) { ["storage":"ArrayObject":private]=> array(2) { ["User-Agent"]=> string(16) "fb-php-ads-2.3.0" ["Accept-Encoding"]=> string(1) "*" } } ["method":protected]=> string(3) "GET" ["protocol":protected]=> string(8) "https://" ["domain":protected]=> string(18) "graph.facebook.com" ["path":protected]=> string(20) "/6025149646418/stats" ["graphVersion":protected]=> string(3) "2.3" ["queryParams":protected]=> object(FacebookAds\Http\Parameters)#481 (1) { ["storage":"ArrayObject":private]=> array(3) { ["fields"]=> string(52) "actions,spent,clicks,impressions,end_time,start_time" ["access_token"]=> string(213) "CAALZCQzTpi7UBAK3F6rjTXORgIJnXF1wxq3BluUUtQH2Cm0YMVgdcWuB7f83vERjPSPd3m1VVZBxAsuRw5oNez0wa37mZCgMRJ87guLCnhfI6ehd5a1vLVv4B6Oq1PQmnG5pKB4uGzbEwp7hpMWTg6cI7YTJxuAbrXtUwwJ6D2GUrpOtBhFUjnF3DqXAYWfBfdeD7QjZBxnQiR0pRb59" ["appsecret_proof"]=> string(64) "9e135d0c4855dbd73575646fc37b71b2947541f27d75864696a4c3236301021b" } } ["bodyParams":protected]=> NULL ["fileParams":protected]=> NULL } ["statusCode":protected]=> int(200) ["headers":protected]=> object(FacebookAds\Http\Headers)#485 (1) { ["storage":"ArrayObject":private]=> array(14) { ["http_code"]=> string(15) "HTTP/1.1 200 OK" ["Content-Type"]=> string(31) "application/json; charset=UTF-8" ["Access-Control-Allow-Origin"]=> string(1) "*" ["X-FB-Rev"]=> string(7) "1669049" ["ETag"]=> string(42) ""290ffcc1aa378a2302f6353daf5639ec8f3bc774"" ["Pragma"]=> string(8) "no-cache" ["Cache-Control"]=> string(44) "private, no-cache, no-store, must-revalidate" ["Facebook-API-Version"]=> string(4) "v2.3" ["Expires"]=> string(29) "Sat, 01 Jan 2000 00:00:00 GMT" ["Vary"]=> string(15) "Accept-Encoding" ["X-FB-Debug"]=> string(88) "l5nXrAemhNdrH4UUmegGQTPpfiG/ErEjfonPYfS8RLVrbSRlJgcRymlrchpQvCXKOo5IGTbgVE7eCqOC3w/f7w==" ["Date"]=> string(29) "Wed, 01 Apr 2015 01:39:14 GMT" ["Connection"]=> string(10) "keep-alive" ["Content-Length"]=> string(3) "182" } } ["body":protected]=> string(182) "{"data":[{"actions":{"photo_view":4,"post":1,"post_like":4,"page_engagement":9,"post_engagement":9},"spent":358,"clicks":16,"impressions":422,"end_time":"2015-04-01T01:39:14+0000"}]}" ["content":protected]=> array(1) { ["data"]=> array(1) { [0]=> array(5) { ["actions"]=> array(5) { ["photo_view"]=> int(4) ["post"]=> int(1) ["post_like"]=> int(4) ["page_engagement"]=> int(9) ["post_engagement"]=> int(9) } ["spent"]=> int(358) ["clicks"]=> int(16) ["impressions"]=> int(422) ["end_time"]=> string(24) "2015-04-01T01:39:14+0000" } } } } ["objects":protected]=> array(1) { [0]=> object(FacebookAds\Object\AdStats)#487 (1) { ["data":protected]=> array(5) { ["actions"]=> array(5) { ["photo_view"]=> int(4) ["post"]=> int(1) ["post_like"]=> int(4) ["page_engagement"]=> int(9) ["post_engagement"]=> int(9) } ["spent"]=> int(358) ["clicks"]=> int(16) ["impressions"]=> int(422) ["end_time"]=> string(24) "2015-04-01T01:39:14+0000" } } } ["indexLeft":protected]=> int(0) ["indexRight":protected]=> int(0) ["position":protected]=> int(0) ["after":protected]=> NULL ["before":protected]=> NULL ["objectPrototype":protected]=> object(FacebookAds\Object\AdStats)#486 (1) { ["data":protected]=> array(0) { } } ["useImplicitFectch":protected]=> NULL }
Thanks

**Comment by paulbain** [comment]
As with the other issue you reported, the start_time is the start of the reporting period, not the start_time of campaign. This will be empty or missing if you did not request a specific start time for your report.

**Comment by kentmt** [comment]
hi Paulbain !
How to get start_time of campaign 
Thanks

**Comment by paulbain** [comment]
$campaign = new AdCampaign($id) ;
    $fields = array(
      AdCampaignFields::START_TIME
    );
    $campaign->read($fields);
    echo $campaign->start_time

**Comment by stshmakov** [comment]
In AdCampaignFields undefined constant 'START_TIME'

**Comment by javiervelaz** [comment]
hi kentmt, did you fix the problem? i have the same error on campaign creation

FacebookAds\Http\Request Object ( [client:protected] => FacebookAds\Http\Client Object ( [requestPrototype:protected] => FacebookAds\Http\Request Object ( [client:protected] => FacebookAds\Http\Client Object *RECURSION* [headers:protected] => [method:protected] => GET [protocol:protected] => https:// [domain:protected] => [path:protected] => [graphVersion:protected] => [queryParams:protected] => [bodyParams:protected] => [fileParams:protected] => ) [responsePrototype:protected] => FacebookAds\Http\Response Object ( [request:protected] => [statusCode:protected] => [headers:protected] => [body:protected] => [content:protected] => ) [defaultRequestHeaders:protected] => FacebookAds\Http\Headers Object ( [storage:ArrayObject:private] => Array ( [User-Agent] => fb-php-ads-2.5.1 [Accept-Encoding] => * ) ) [adapter:protected] => FacebookAds\Http\Adapter\CurlAdapter Object ( [curl:protected] => FacebookAds\Http\Adapter\Curl\Curl Object ( [handle:protected] => Resource id #217 ) [opts:protected] => ArrayObject Object ( [storage:ArrayObject:private] => Array ( [78] => 10 [13] => 60 [19913] => 1 [42] => 1 [10065] => /home/digital6/public_html/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/../../../fb_ca_chain_bundle.crt ) ) [client:protected] => FacebookAds\Http\Client Object *RECURSION* ) [caBundlePath:protected] => /home/digital6/public_html/vendor/facebook/php-ads-sdk/src/FacebookAds/Http/../../../fb_ca_chain_bundle.crt [defaultGraphBaseDomain:protected] => facebook.com ) [headers:protected] => FacebookAds\Http\Headers Object ( [storage:ArrayObject:private] => Array ( [User-Agent] => fb-php-ads-2.5.1 [Accept-Encoding] => * ) ) [method:protected] => POST [protocol:protected] => https:// [domain:protected] => graph.facebook.com [path:protected] => /act_4069523148218/campaigns [graphVersion:protected] => 2.5 [queryParams:protected] => FacebookAds\Http\Parameters Object ( [storage:ArrayObject:private] => Array ( ) ) [bodyParams:protected] => FacebookAds\Http\Parameters Object ( [storage:ArrayObject:private] => Array ( [name] => febrero [objective] => LINK_CLICKS [status] => PAUSED [access_token] => CAABveNcNunkBALkSgPwungfY0EYnOXhdJZAnngw3u1Jsoq5xXS27BfDbDSOIiSpZChcupCL1XN0kfeIZCYH97zqnQLuVmqsrCNDA6D5TtasnFanzu7Q8OKFrYjPr5Nzue8wN1yLGvhh3ehXm37lsszWjaJ2POSJjKM0xZCrox5C0G82QWNhP70rlDVP6yMQZD [appsecret_proof] => 25cad600012e4e51769e3e71e8b06e51c4fc2e5dd22f6ad39051e893e9228dfa ) ) [fileParams:protected] => FacebookAds\Http\Parameters Object ( [storage:ArrayObject:private] => Array ( ) ) )
