### ISSUE TITLE
Start Time is Null when getStats 

### ISSUE THREAD

**Issue by kentmt** [facebook/facebook-php-ads-sdk#82]
Hi ,

$adsets = $campaign->getAdSets(array(
		  	AdSetFields::ACCOUNT_ID,
		  	AdSetFields::CAMPAIGN_STATUS,
		  	AdSetFields::BID_TYPE,
		  	AdSetFields::BID_INFO,
		  	AdSetFields::BUDGET_REMAINING,
		  	AdSetFields::NAME,
		  	AdSetFields::DAILY_BUDGET,
		  	AdSetFields::PROMOTED_OBJECT,
		  	AdSetFields::UPDATED_TIME,
		  	AdSetFields::LIFETIME_BUDGET,
		  	AdSetFields::IS_AUTOBID,
		),$params);
		foreach ($adsets as $key => $adset) {
			var_dump($adset->getStats());
			echo '<br>';
		}

Result 
object(FacebookAds\Object\AdStats)#483 (1) { ["data":protected]=> array(18) { ["id"]=> string(32) "6025149647218/stats/0/1427871600" ["impressions"]=> int(218) ["topline_id"]=> NULL ["clicks"]=> int(7) ["spent"]=> int(198) ["social_impressions"]=> int(0) ["social_clicks"]=> int(0) ["social_spent"]=> int(0) ["unique_impressions"]=> int(212) ["social_unique_impressions"]=> int(0) ["actions"]=> array(2) { ["post_like"]=> int(2) ["photo_view"]=> int(2) } ["inline_actions"]=> array(14) { ["title_clicks"]=> int(0) ["like"]=> int(0) ["rsvp_yes"]=> int(0) ["rsvp_maybe"]=> int(0) ["post_like"]=> int(3) ["comment"]=> int(0) ["photo_view"]=> int(2) ["link_click"]=> int(0) ["video_play"]=> int(0) ["question_vote"]=> int(0) ["cta_click"]=> int(0) ["item_click_1"]=> int(0) ["item_click_2"]=> int(0) ["item_click_3"]=> int(0) } ["unique_clicks"]=> int(7) ["social_unique_clicks"]=> int(0) ["campaign_id"]=> string(13) "6025149647218" ["start_time"]=> NULL ["end_time"]=> string(24) "2015-04-01T07:00:00+0000" ["is_completed"]=> bool(false) } } 

I see start time  = NULL 

How to get start_time for adset

Thanks

**Comment by paulbain** [comment]
The start_time is the start time of the stats report you are requesting in this case, not the start time of the adset. You can configure this when making the initial request in the params array.

If you want to know the start time and end time of an adset, then just request that as a param of the object:

    $adsets = $campaign->getAdSets(array(
      AdSetFields::ACCOUNT_ID,
      AdSetFields::CAMPAIGN_STATUS,
      AdSetFields::BID_TYPE,
      AdSetFields::BID_INFO,
      AdSetFields::BUDGET_REMAINING,
      AdSetFields::NAME,
      AdSetFields::DAILY_BUDGET,
      AdSetFields::PROMOTED_OBJECT,
      AdSetFields::UPDATED_TIME,
      AdSetFields::LIFETIME_BUDGET,
      AdSetFields::IS_AUTOBID,
      AdSetFields::START_TIME,
      AdSetFields::END_TIME,
      ));

    foreach ($adsets as $key => $adset) {
        echo 'Start Time: '. $adset->start_time 
          . ' End Time: '. $adset->end_time.PHP_EOL;
    }
