### ISSUE TITLE
What is the error in the following code

### ISSUE THREAD

**Issue by khanwasim1992** [facebook/facebook-php-ads-sdk#84]
function gogingtoevent() {
        FB.login(function(response) {
            if (response.status == 'connected') {
                FB.api('/816891388384961/attending', 
                 function (response) {
                   if (response && !response.error) {
                        alert('Attending');
                       }else{
                            alert (JSON.stringify(response));   
                       }
                    });
            }else{
                alert('Not Responding');
            }
        });
    }

**Comment by paulbain** [comment]
Unfortunately this is the GitHub repo for the PHP SDK. This looks like a javascript SDK and would probably be a question best asked on StackOverflow:
stackoverflow.com/questions/tagged/facebook
