### ISSUE TITLE
Get an access token server side

### ISSUE THREAD

**Issue by yamsellem** [facebook/facebook-php-ads-sdk#85]
It may sound trivial, but where / how are we supposed to get an access_token?
The doc says "To instantiate an Api object you will need a valid access token" but do not say how.

Is it possible to get one from server-to-server?

ps. [this page](https://developers.facebook.com/docs/facebook-login/access-tokens#apptokens) explains how to generate tokens, but it seems that a web interface is always needed to do so

**Comment by yamsellem** [comment]
This steps are working.

* Get a short-lived token (_with the `manage_pages` permission_) though the [Graph API Explorer](https://developers.facebook.com/tools/explorer)
* Convert this short-lived access token into a long-lived one though https://graph.facebook.com/oauth/access_token?client_id=&client_secret=&grant_type=fb_exchange_token&fb_exchange_token=
* Convert this long-lived access token in a permanent one (Expires: Never) though https://graph.facebook.com/me/accounts?access_token=

**Comment by meetPrasanth** [comment]
@yamsellem how are you getting a Permanent Long-lived access token, Can you explain it
