### ISSUE TITLE
List a tag's campaigns

### ISSUE THREAD

**Issue by yamsellem** [facebook/facebook-php-ads-sdk#88]
The following code:
```
(new AdTag($id))->getAdCampaigns($fields);
```

Returns this error:
```
(#275) Ad account cannot be determined for this request
```

Is there a way to limit the tag campaigns list to a given account to avoid this?
Are we supposed to add some permission to the account?

_Bonus point: [In the tag's docs](https://developers.facebook.com/docs/marketing-api/adtag/v2.3), it's also said one can list every tags with_ `https://graph.facebook.com/<API_VERSION>/act_<AD_ACCOUNT_ID>/adtags`. 
_Is there a way to do so with this library? Account does not expose a_ `getTags()` _method_

_Bonus point: is there a way to find a tag by name?_

**Comment by pruno** [comment]
@yamsellem,

1- Are you sure you are providing a valid ad tag ID? if you could share your tag ID it will be easier to debug.
2 - I'll implement AdAccount::getAdTags()

**Comment by yamsellem** [comment]
Thanks for your quick feedback, and for the `getAdTags` method ;-).

I'm sure to provide a valid tag ID because the Graph API explorer give me the same error but I don"t understand why. The issue is also [discussed here](https://developers.facebook.com/bugs/830847373647988).

**Comment by pruno** [comment]
As it appears to be an issue with the API i'll close here, feel free to reopen if necessary.
You can't search a tag by name: if you plan to make an extensively dynamic use of tags i suggest to store the ID-Name pair on your side and use to the API to fetch their content (or update it's associations).
