### ISSUE TITLE
Create AdAccount

### ISSUE THREAD

**Issue by alexkappa** [facebook/facebook-php-ads-sdk#89]
Hello,

I was wondering why ad accounts cannot be created using the SDK. 

From the [API documentation](https://developers.facebook.com/docs/marketing-api/businessmanager/v2.3#adaccounts-create) it seems allowed to create an ad account but in the SDK the [AdAccount class](https://github.com/facebook/facebook-php-ads-sdk/blob/master/src/FacebookAds/Object/AdAccount.php#L35) uses the `CannotCreate` trait.

Thanks,
Alex

**Comment by pruno** [comment]
Hi @alexkappa,

Through the API, only accounts owned by a business (not a user) can be created. Despite we are working on it, the SDK doesn't yet support the business manager API objects. 

If you need to access that endpoint i suggest you temporary create the account through a direct API call (you i'll be able to read and update the account through the AdAccount class).

~~~
$response = Api::instance()->call(
  '/<BUSINESS_ID>/adaccounts',
  RequestInterface::METHOD_POST,
 array('fields' => array(
   AdAccountFields::NAME => 'My Business Account',
   // All other required params 
  ))
);

$account_id = $response->getContent()[AdAccountFields::ID];

$account = new AdAccount($account_id);
~~~

Note: i haven't tested this code :)

**Comment by alexkappa** [comment]
Thanks @pruno, we'll work around it for the time being and will be looking forward to having support for business manager objects in the SDK.

Cheers!

**Comment by allentsai** [comment]
Quick note for anyone who stumbles upon this issue.  The example uses  `'/<BUSINESS_ID>/adaccounts'`, but the path should really be ` '/<BUSINESS_ID>/adaccount'` (no 's').

**Comment by newerton** [comment]
It is possible to create the user uses AdAccount?

My code?
```php
$fieldsRequired = [
    'name' => 'My Ad Account',
    'currency' => 'USD',
    'timezone_id' => 7,
];
$accounts = $fb->post('/me/adaccounts', $fieldsRequired);
```

`(#275) Cannot determine the target object for this request. Currently supported objects include ad account, business account and associated objects.`

Where am I going wrong? It is obligatory to have the **BUSINESS_ID** instead of **/me**?

Sorry my English!

**Comment by newerton** [comment]
@alexkappa Solve this problem of creating Account?

**Comment by happierall** [comment]
@newerton Did you solve this? I can't create with my business id too...

**Comment by newerton** [comment]
@happierall Without solution. In my case, I direct the client to Facebook Ads, automatically creates the account for the user.

My project is stopped. I was using version 2.6. Today it is in version 2.9, and did not solve this problem.

In the documentation, it would have to work.
Https://developers.facebook.com/docs/marketing-api/reference/ad-account#Creating

**Comment by happierall** [comment]
I found solution. You need application with Standart Access. Not basic, not
development

**Comment by newerton** [comment]
The code below should be implemented. Using the user session.
```php
$fieldsRequired = [
    'name' => 'My Ad Account',
    'currency' => 'USD',
    'timezone_id' => 7,
];
$accounts = $fb->post('/me/adaccounts', $fieldsRequired);
```

**Comment by GuangStack** [comment]
(#275) Cannot determine the target object for this request. Currently supported objects include ad account, business account and associated objects.
       Why ?
