### ISSUE TITLE
Reservation of ReachFrequencyPrediction not working.

### ISSUE THREAD

**Issue by monitotxi** [facebook/facebook-php-ads-sdk#92]
The method `ReachFrequencyPrediction::reserve()` throws an exception 'Array to string conversion' on *line 116*.

`$response->getContent()` returns an associative array with the ID of the prediction, but it's typecasted to a string.

**Comment by pruno** [comment]
@monitotxi, can you provide a code to reproduce this?

**Comment by monitotxi** [comment]
@pruno For an existing prediction:
```php
use FacebookAds\Object\ReachFrequencyPrediction;

$prediction_id = 'XXX';
$adaccount_id = 'XXX';
$prediction = new ReachFrequencyPrediction($prediction_id, $adaccount_id);
$prediction->reserve(); //throws the exception
```
