### ISSUE TITLE
API v2.4

### ISSUE THREAD

**Issue by red-crown** [facebook/facebook-php-ads-sdk#95]
Api v2.4 came out yesterday, and the previous week some fields in the insights edge v2.3 were *SILENTLY* removed resulting in requests failing: `InsightsFields::RESULTS` and `InsightFields::ACTIONS_PER_IMPRESSION` for example. These fields were even listed as valid in the insights documentation.

When will this sdk be updated, and when it does, how can we be confident that the graph api isn't going to be changed quietly without a version bump.

**Comment by paulbain** [comment]
If fields are removed that are documented and are not listed in breaking change that is a bug. In the case that this happens, please file a bug and we can follow up. http://developers.facebook.com/bugs

**Comment by paulbain** [comment]
Also, there will be a 2.4 release of the SDK imminently

**Comment by paulbain** [comment]
v2.4 is out. if you find undocumented changes, please do open a bug report and comment with the URL here.
